### ISSUE TITLE
Documentation should mention how to populate a tree from a plain HTML <ul><li> tree.

### ISSUE THREAD

**Issue by shlomif** [mbraak/jqTree#101]
Hi all.

As can be seen in this StackOverflow question with no replies: http://stackoverflow.com/questions/13791528/how-to-get-jqtree-to-read-the-initial-tree-from-the-htmls-source  the documentation does not cover how to populate a tree from an existing &lt;ul&gt;&lt;li&gt; HTML tree data structure, which is still required to support user-agents with JavaScript disabled/blacklisted/etc. 

Please cover it there. Feel free to reply on the StackOverflow question so I (and other people) can upvote, select and star your answer.

Regards,

— Shlomi Fish

**Comment by shlomif** [comment]
@mbraak : hi! Why was this issue closed and without a comment?

**Comment by mbraak** [comment]
I have no plans to fix this issue.
