### ISSUE TITLE
Keyboard Navigation

### ISSUE THREAD

**Issue by ColinGardner** [mbraak/jqTree#117]
I am trapping up/down/left/right keystoke events to navigate the treeview and all works well when running on the client side.  However sometimes I trigger a page reload when a node is selected and although the state is preserved the treeview is no longer in focus which means the user has to click the treeview again before they can continue with keyboard navigation.  I can't seem to reset the focus to the treeview on page load - any suggestions?

Fantastic plugin btw

**Comment by jitugupta** [comment]
How you are trying to capture the key up/down events? can you please share your code? i have to use it in my code. i want to make the selected node of white color. so i am handling this click event but i am not able to change the color of node when i use keyboard navigation.

Thanks in advance!

**Comment by mbraak** [comment]
The last version of jqTree has keyboard support: see the [keyboardSupport](http://mbraak.github.io/jqTree/#options-keyboardsupport) option.

**Comment by jitugupta** [comment]
Sorry for late replying. I am looking for events for keyboard. for example OnKeyDown() or OnKeyUp().
is there any events like this which i can make use of?

**Comment by mbraak** [comment]
JqTree has no events for the keyboard.

You can of course catch the events yourself. Then you have to set ``keyboardSupport`` to false

```js
$('#tree1').tree({
  data: data,
  keyboardSupport: false
});

$(document).bind('keydown', function(e) {
  if (e.which == 40) {
    // down
    $('#tree1').tree('moveDown');
  }
  else if (e.which == 38) {
    // up
    $('#tree1').tree('moveUp');
  }
});
```

**Comment by jitugupta** [comment]
Its hitting the line "$('#tree1').tree('moveDown');" but not doing any thing...
$(document).bind('keydown', function (event) {
        if (event.which == 40) {
            // down
            $tree.tree('moveDown',true);
        }
        else if (event.which == 38) {
            // up
            $tree.tree('moveUp',true);
        }
    });

**Comment by jitugupta** [comment]
This is what i am trying to achieve:
i have three accordion and every accordion is having a different tree:


Screen clipping taken: 3/6/2015 3:51 PM

![untitled picture](https://cloud.githubusercontent.com/assets/2351385/6523769/c50baa6c-c418-11e4-8d37-cff98d3c56d8.png)

**Comment by jitugupta** [comment]
Actually why i require keyboard events is because my requirement is:
Selected item text in tree should be in white color, so to change black to white and vice-versa. i require keyboard events.
i am changing node color black to white for mouse event already but i want for keyboard also. how can i achieve that?

**Comment by mbraak** [comment]
Perhaps you use css to set the color:

```css
ul.jqtree-tree li.jqtree-selected > .jqtree-element .jqtree-title {
    color: #fff;
    text-shadow: none;
}
```

**Comment by jitugupta** [comment]
Thanks Again!
I am new to javascript and css.

It solved my problem in just 4 lines where i was writing many lines of code.

thanks a ton!

**Comment by mbraak** [comment]
ok. great!
