### ISSUE TITLE
Bootstrap Compatible?

### ISSUE THREAD

**Issue by bane73** [mbraak/jqTree#13]
I am attempting to insert the demo jqtree code into a div in a project using Twitter's Bootstrap.

It's not rendering, though; the exact reason I have been unable to determine, but it's clear that attempting to attach the data to the tree-div is terminating early and not actually attaching the data.

Has this problem been seen before?  Is there any kind of workaround or anything?

**Comment by samhuawey** [comment]
Hi,

I also got the issue recently:

TypeError: AJS.$(...).tree is not a function

My source code is as following:

var my_data = [
            {
                label: 'node1',
                children: [
                    { label: 'child1' },
                    { label: 'child2' }
                ]
            },
            {
                label: 'node2',
                children: [
                    { label: 'child3' }
                ]
            }
        ];

        AJS.$('#tree-goal-container').tree({ data: my_data,});

Can you please comment?

**Comment by mbraak** [comment]
You can get this error if ``tree.jquery.js`` is not loaded correctly. It can also happen if you multiple ``jQuery`` instances.

I have not seen ``AJS.$`` before. Could you tell me what it is?

**Comment by samhuawey** [comment]
It is the namespace in my framework that contains jquery.

**Comment by samhuawey** [comment]
The code is called from inside 

AJS.$(document).ready(function() {
}

**Comment by mbraak** [comment]
jqTree uses the `$` global variable. Is that variable also defined?

**Comment by samhuawey** [comment]
No, it is undefined.

**Comment by mbraak** [comment]
Hmm. That's strange. JqTree cannot work without the $ variable.
