### ISSUE TITLE
will you implement double click?

### ISSUE THREAD

**Issue by eskaigualker** [mbraak/jqTree#181]
thank you

**Comment by rpb-dev** [comment]
Just correcting @mbraak example: 
`$('#tree1').bind(
    'tree.dblclick',
    function(event) {
        // e.node is the clicked node
        console.log(event.node);
    }
);`

**Comment by rpb-dev** [comment]
> Just correcting @mbraak example:
```javascript
$('#tree1').bind( 'tree.dblclick', function(event) { 
    // e.node is the clicked node 
    console.log(event.node); 
});
```
