### ISSUE TITLE
Collapsing the tree?

### ISSUE THREAD

**Issue by sebakerckhof** [mbraak/jqTree#19]
Hello,

Thanks for this plugin!
Is there a way to collapse the tree or certain nodes of the tree?

Thanks in advance,
seba

**Comment by arunkumar2014** [comment]
Hello 
I need to append my child node below their parent node dynamically from db through ajax call. I tried with openNode, addNodeAfter its not viewing. But i tried with append node its showing the child node last of all the parent node.

**Comment by mbraak** [comment]
Let me see if I understand you correctly. You want to add a child node to a parent node; the new node must be the first child.

Is that correct?

**Comment by arunkumar2014** [comment]
yes

**Comment by mbraak** [comment]
There is no 'add-first-child' function. But you can use the [addNodeBefore](https://mbraak.github.io/jqTree/#functions-addnodebefore) function.

Here is an example:

```js
// appendNodeFirst: add 'new_node' as first child to 'parent_node'
function appendNodeFirst($tree, new_node, parent_node) {
    if (parent_node.children && parent_node.children.length != 0) {
        // Parent has children; add before first child
        var first_child = parent_node.children[0];

        $tree.tree('addNodeBefore', new_node, first_child);
    }
    else {
        // Parent has no children; append node
        $tree.tree('appendNode', new_node, parent_node);
    }
}

var parent_node = $tree.tree('getNodeById', 1);

var new_node = {
    label: 'new child',
    id: 6
};
```

**Comment by urprasu** [comment]
how to merge the nodes

**Comment by urprasu** [comment]
how to replace rootnode child nodes

**Comment by mbraak** [comment]
@urprasu 
Can you give give an example of how you want to merge nodes?
