### ISSUE TITLE
Is possible to drag and drop node to outside, for example to  div?

### ISSUE THREAD

**Issue by ihurskyi** [mbraak/jqTree#234]

**Comment by mbraak** [comment]
This is merged in the dev branch

**Comment by gautiermichelin** [comment]
Hi @mbraak, this is not documented anywhere :-(

Could you drop a link to there in :
https://github.com/mbraak/jqTree/tree/gh-pages/_entries
?

**Comment by mbraak** [comment]
I see that this is indeed not documented. I will add this to the documentation.

**Comment by gautiermichelin** [comment]
Hi back,

Just dropping here my simple use case if you need an example : 

````javascript

        var targetCollisionDiv = jQuery("#targetDiv");

        function HandleStop(node, e) {
            // Basic detection collision with target
            if(
                e.clientX > targetCollisionDiv.position().left &&
                e.clientX < targetCollisionDiv.position().left + targetCollisionDiv.width()) &&
                e.clientY > targetCollisionDiv.position().top &&
                e.clientY < targetCollisionDiv.position().top + targetCollisionDiv.height())
            ) {
                console.log("the tree leef is over the targetDiv");
            }
        }
````

**Comment by mbraak** [comment]
Thanks!

**Comment by u19900101** [comment]
> Hi back,
> 
> Just dropping here my simple use case if you need an example :
> 
> ```js
>         var targetCollisionDiv = jQuery("#targetDiv");
> 
>         function HandleStop(node, e) {
>             // Basic detection collision with target
>             if(
>                 e.clientX > targetCollisionDiv.position().left &&
>                 e.clientX < targetCollisionDiv.position().left + targetCollisionDiv.width()) &&
>                 e.clientY > targetCollisionDiv.position().top &&
>                 e.clientY < targetCollisionDiv.position().top + targetCollisionDiv.height())
>             ) {
>                 console.log("the tree leef is over the targetDiv");
>             }
>         }
> ```

can drag and drop node to iframe?THANKS
