### ISSUE TITLE
Allow setting option after tree has been created.

### ISSUE THREAD

**Issue by comanche** [mbraak/jqTree#251]
Please allow setting options after tree has been created like this:

``` javascript
$tree.tree('setOption', {
    dragAndDrop    : false,
    openFolderDelay: 1000
});
```

Thanks.

**Comment by evaneykelen** [comment]
For the sake of clarity (I myself was confused for a short moment) the `setOption` method does not accept a hash, instead it accepts key and value parameters.

This means that @comanche's code example:

```
$tree.tree('setOption', {
    dragAndDrop    : false,
    openFolderDelay: 1000
});
```

has to be written as follows in @mbraak's actual implementation:

```
$tree.tree('setOption', 'dragAndDrop', false);
$tree.tree('setOption', 'openFolderDelay', 1000);
```
