### ISSUE TITLE
Can I set image icon to Root & Child node ?

### ISSUE THREAD

**Issue by ChetanChaudhari03** [mbraak/jqTree#281]
Hi,
Right now in current JQTree we can specified only openIcon & closedIcon but we cann't set child icon 
so can you please tell me how can i set Icon/Image to child node?

I change your code that function name is "ElementsRenderer.prototype.createNodeLi" so can you please change that as per of the code "ElementsRenderer.prototype.createFolderLi" and set new option for "childIcon". so we can set new childIcon.

Is am I right or wrong please tel me? if right then please change your code respective what i say.

Thanks,
Chetan

**Comment by javierRomano** [comment]
Thank you @mbraak, that helped me a lot

**Comment by ChetanChaudhari03** [comment]
@javierRomano that's y this portal is there...


Ur always welcome here & questions. :)

**Comment by ChetanChaudhari03** [comment]
@javierRomano that's y this portal is there...


Ur always welcome here & questions. :)
