### ISSUE TITLE
Change the icon from treeRightTriangleBlack.png to ui-icon-plus?

### ISSUE THREAD

**Issue by gnumonk** [mbraak/jqTree#30]
Hi, 
How can I change the icon set to (+ and -), for example if I click it will automatically to (ui-icon-minus) and for collapse (ui-icon-plus).

--
Thanks

**Comment by mbraak** [comment]
Note that it is now possible to change the icons for the toggle buttons. See #240, #125 and #127.

**Comment by masum188** [comment]
$(function() {
    $('#tree1').tree({
        data: data,
		closedIcon: '+',
		openedIcon: '-',
    });
});
