### ISSUE TITLE
To add new example:

### ISSUE THREAD

**Issue by romelgomez** [mbraak/jqTree#321]
Hi! friend. To add new example:

Demo:
http://jqtree-spring-mvc-gae-example.appspot.com/

Code:
https://github.com/romelgomez/jqtree-spring-mvc-gae-example

Best wishes.

**Comment by romelgomez** [comment]
Hi, can i make a pull request to add uses cases of this project ?, i just make another: 

https://github.com/romelgomez/jqtree-angularjs-firebase-example

Best regards.

**Comment by mbraak** [comment]
Do you want to add example code?

Greetings,
Marco

**Comment by romelgomez** [comment]
Yes, 

Maybe something like this: 

/_examples/usesCases.md

# Uses Cases or Implementations of JqTree

## With AngularJS and FireBase 
https://github.com/romelgomez/jqtree-angularjs-firebase-example

## With CakePHP and OpenShift
Code: https://github.com/romelgomez/jqtree-cakephp-openshift-example
Demo: http://jqtreecakephpexample-theteacher.rhcloud.com/

## With Spring MVC and Google App Engine 
Code: https://github.com/romelgomez/jqtree-spring-mvc-gae-example
Demo: http://jqtree-spring-mvc-gae-example.appspot.com/


What do you think about that?

Best regards.

**Comment by mbraak** [comment]
Yes, I think it's a good idea to add links in the documentation to these examples.

**Comment by romelgomez** [comment]
Super, i will start make that file and the pull request. 

Many thanks and Best regards.
