### ISSUE TITLE
Nodes should have a copy method (to allow copy on drag, rather than move)

### ISSUE THREAD

**Issue by bnovc** [mbraak/jqTree#329]
Nodes should have a copy method (to allow copy on drag, rather than move)

There doesn't seem to be a decent way to copy.  You can append the current element under itself, but it doesn't preserve the hierarchy.

**Comment by jakemuntadriftforgood** [comment]
Thnks mbraak, its working...

**Comment by jakemuntadriftforgood** [comment]
One more question, can you please tell me how to move a node with its all nested nodes from one jqtree to another jqtree... please help me ASAP.

**Comment by mbraak** [comment]
Moving from one tree to another is not supported. I think it would be really difficult to implement.

**Comment by jakemuntadriftforgood** [comment]
Thanks for your response 
But I did it in another way... when I clicked it on a node of tree1 its copied into tree2 selected node.. code is below : 
.bind(
                      'tree.dblclick',
                      function (event) {
                          
                         
                          var selectedNode = $('#tree2').tree('getSelectedNode');
                          
                          // copy node
                          var duplicate_node = $('#tree2').tree(
                              'addNodeAfter',
                              {
                                  label: event.node.name,
                              },
                              selectedNode
                          );

                          // copy children
                          // $('#tree2').tree('loadData', event.node.children, duplicate_node);
                          

                       
                      });

but now I got a problem when I copied it into tree2 its copied but its copied outside of selected node... but it should be copied into within the selected node.
PLEASE HELP?

**Comment by mbraak** [comment]
I see that you use the [addNodeAfter](https://mbraak.github.io/jqTree/#functions-addnodeafter) function to add the node. I think you should use [appendNode](https://mbraak.github.io/jqTree/#functions-appendnode):

```js
var duplicate_node = $('#tree2').tree(
  'appendNode',
  { label: event.node.name },
  selectedNode
);
```

Please let me know if this works.

**Comment by jakemuntadriftforgood** [comment]
Great, Its really working, I am grateful for you. :+1:

**Comment by mbraak** [comment]
ok great
