### ISSUE TITLE
How to use get/setState with a tree using autoOpen = false (loadOnDemand)?

### ISSUE THREAD

**Issue by brett-walker** [mbraak/jqTree#334]
Before rebuilding/refreshing a tree I save the state of open nodes. The tree is then rebuilt/refreshed.

I want to restore the state of open nodes but cannot because of the autoOpen = false.

Code A - Naive

	var treeState = jQuery("#availableBATree").tree('getState');

        // destroy the tree and build a new one
	refreshTree("#availableBATree", "ba/get-business-activities", baItemCreated, true, true);
	jQuery("#availableBATree").tree('setState', treeState);

Code B - Improvement

	var treeState = jQuery("#availableBATree").tree('getState');

        // destroy the tree and build a new one with an init callback
	refreshTree("#availableBATree", "ba/get-business-activities", baItemCreated, true, true,
		function() {
			console.log("tree.init callback triggered");

			for (var i in treeState.open_nodes) {
				var node = jQuery("#availableBATree").tree("getNodeById", treeState.open_nodes[i]);
				jQuery("#availableBATree").tree("openNode", node);
			}
	});

Code A doesn't open any node. Code B is an improvement in that it open the first level of nodes, where appropriate. For second level and deep into the tree I cannot open the nodes easily?

I am open to suggestions. Any help appreciated.

**Comment by mbraak** [comment]
Closing this issue because it's probably the same as issue #273. Note that issue #273 is fixed.
