### ISSUE TITLE
Should not require jQuery to be global

### ISSUE THREAD

**Issue by adius** [mbraak/jqTree#338]
This does not work in browserify:
```
$ = require 'jquery'
jqtree = require 'jqtree'
```
This throws: `Uncaught ReferenceError: $ is not defined    simple.widget.js:99`

This, however, works:
```
global.$ = require 'jquery'
jqtree = require 'jqtree'
```
jqtree should require jQuery itself so that it's a proper dependency!

**Comment by ScarfaceIII** [comment]
I have had the same issue trying to wrap this widget in a Dojo widget (actually Aikau, a framework used in Alfresco).
I didn't have any issues when wrapping a jqueryui widget, if this is of any help.
