### ISSUE TITLE
is there a mouseover function?

### ISSUE THREAD

**Issue by CHAAAAA** [mbraak/jqTree#345]

**Comment by mbraak** [comment]
JqTree does not support the mouseover event. But you can use the standard event from your browser:

```
    $('#tree1').on('mouseover', function(e) {
        console.log(e);
    });
```

**Comment by CHAAAAA** [comment]
OK Thanks!

**Comment by melston** [comment]
What about moseover on specific nodes?  I want to show a floating div on mouseenter but the content of the div is specific to the node the cursor is over.

**Comment by mbraak** [comment]
You can use the [getNodeByHtmlElement](https://mbraak.github.io/jqTree/#functions-getnodebyhtmlelement) for this.

Something like this (i have not tried it, but it should work):

```js
$tree.on('mouseover', function(e) {
  var node = $tree.tree('getNodeByHtmlElement', e.target);
});
```

**Comment by melston** [comment]
Thanks.  I'll give it a try.

**Comment by melston** [comment]
Thanks, @mbraak.  This works reasonably well.  There seem to be some interactions with Electron that sometimes prevent the div from showing up but the snippet you gave seems to give the correct results all the time (at least in the debugger).

**Comment by mbraak** [comment]
I'm glad that it works.
