### ISSUE TITLE
appendNode function issue

### ISSUE THREAD

**Issue by SergeyBan** [mbraak/jqTree#346]
I have the following issue. The tree has some nodes. Using function 'addNodeAfter' I add new node. Then using function 'appendNode' I add child node to just added node. After this I try to move my child node to another, but I can't. Only after some attempts it starts working. A tried to debug and found out that 'event.move_info.target_node' is root node (the whole tree). Why could that occur?

**Comment by mbraak** [comment]
I could not reproduce this. I had no problem moving the child node.

This is the code I used:

```js
$(function() {
    var data = [
        {
            label: 'node1', id: 1,
            children: [
                { label: 'child1', id: 2 },
                { label: 'child2', id: 3 }
            ]
        },
        {
            label: 'node2', id: 4,
            children: [
                { label: 'child3', id: 5 }
            ]
        }
    ];

    var $tree = $('#tree1');

    $tree.tree({
        data: data,
        dragAndDrop: true
    });

    var child2 = $tree.tree('getNodeById', 3);

    $tree.tree('addNodeAfter', {id: 100, label: 'new1'}, child2);

    var new1 = $tree.tree('getNodeById', 100);

    $tree.tree('appendNode', {id: 100, label: 'new2'}, new1);
});
```

**Comment by SergeyBan** [comment]
OK. But I add some html into 'li' as described here http://mbraak.github.io/jqTree/#options-oncreateli
there is 10 different html tags such as input[type="text"] and select and another hidden fields. Can it cause problems?
Sorry, that I didn't wrote about it in my first message

**Comment by mbraak** [comment]
I would certainly try it without ``oncreateli``. It should not be a problem, but you never know.

**Comment by SergeyBan** [comment]
Ok. But I really need to append this html tags to each tree item. How to do that without using onCreateLi?

**Comment by mbraak** [comment]
Of course you should use oncreateli. But if it works without oncreateli, then we have isolated the problem.
