### ISSUE TITLE
Is there away to append "a node with its children"?

### ISSUE THREAD

**Issue by danielmahadi** [mbraak/jqTree#347]
I had a node data as follow

```javascript
{
  label: 'New Node',
  children: [
     { label: 'Child 1' },
     { label: 'Child 2', children: [ ... ] }
  ]
}
```

I tried:
* addNodeAfter
* addNodeBefore
* appendNode

None works.

I found that the children data is not being transform into a node object, thus failed in the creating the UI element for this children.

Am I looking at wrong method?

**Comment by mbraak** [comment]
You can use the [loadData](http://mbraak.github.io/jqTree/#functions-loaddata) function to load a subtree:

```js
// Get node by id (this assumes that the nodes have an id)
var parent_node = $('#tree1').tree('getNodeById', 100);

// Add new nodes
// Note that this data can also include children
var data = [
    { label: 'new node' },
    { label: 'another new node' }
];

$('#tree1').tree('loadData', data, parent_node);
```

**Comment by danielmahadi** [comment]
Hi @mbraak 

Thanks for your help. :)
