### ISSUE TITLE
How to recursive open Nodes until perticular node in case of lazy loaded node.

### ISSUE THREAD

**Issue by sanjaysemilo** [mbraak/jqTree#350]
$('#tree').tree({
    dataUrl: '/api/Controller',
    dragAndDrop: false,
    useContextMenu: false,  
   });

var node = $('#tree').tree('getNodeById', 10);
$('#tree').tree('scrollToNode', node);

On tree loading I want to show node as a selected in child hierarchy. 
I have tried like this but I am getting following error:
Uncaught TypeError: Cannot read property 'scrollToNode' of undefined.

Is it possible to show child node as selected in case of lazy loading nodes ?

**Comment by mbraak** [comment]
I think you should use the [tree.init](http://mbraak.github.io/jqTree/#event-tree-init) event:

```js
$('#tree').tree({
  dataUrl: '/api/Controller',
  dragAndDrop: false,
  useContextMenu: false
});
$('#tree').on('tree.init', function() {
  var node = $('#tree').tree('getNodeById', 10);

  if (node) {
    $('#tree').tree('scrollToNode', node);
  }
});
```

Does this work better?

**Comment by sanjaysemilo** [comment]
Node id "10" is yet not there as it is lazy loading.....it is inside 2 -> 5 -> 10. Is it possible directly to provide this hierarchy in function like "scrollToNode [2,5,10]", so that it will first opens all the parent nodes and then select last node i.e 10 ? i.e it will keep on expanding all required nodes until our node which we have to show as selected.

**Comment by mbraak** [comment]
Jqtree does not support that.

I'm wondering if I could add a ``on_opened`` callback to the ``openNode`` fuction. Then you could do something like this:

```js
var $tree = $('#tree1');

$tree.tree('openNode', false, $tree.tree('getNodeById', 2), function() {
  // node with id 2 is now opened
  $tree.tree('openNode', false, $tree.tree('getNodeById', 5), function() {
    // node with id 5 is now opened
    $tree.tree('scrollToNode', $tree.tree('getNodeById', 10));
  });
));
```

**Comment by atlantageek** [comment]
I think this is what I need as well. I have a use case where the user does a search and if the node is found in the database I load the tree and open all the way to the searched node.  However mine is in a scroll window and the scroll is not working.  I wonder if I need a callback so it wont do the scroll until the node is opened.
