### ISSUE TITLE
Is there anyway to tie data to a node ?

### ISSUE THREAD

**Issue by Chocapic** [mbraak/jqTree#352]
Beside the name, can I add a value to a node so when it get selected I can return its value instead of his name ?

**Comment by mbraak** [comment]
Yes, you can add attributes to the tree data. This example sets the attributes ``color`` and ``height``:

```js
var data = [
    {
        label: 'node1',
        id: 1,
        color: 'green',
        height: 2
    }
];

$('#tree1').tree({data: data});
```

Now you can access these attributes:

```js
var node = $('#tree1').tree('getNodeById', 1);

console.log(node.color);
console.log(node.height);
```

And in the ``tree.select`` event:

```js
$('#tree1').bind(
    'tree.select',
    function(event) {
        if (event.node) {
           console.log(node.color);
        }
    }
);
```

**Comment by Chocapic** [comment]
I am so glad you thought of everything. Thanks a lot for your work !
