### ISSUE TITLE
Different Icons for different node types

### ISSUE THREAD

**Issue by natemccallum** [mbraak/jqTree#354]
I am trying to assign different icons based on the type of node. I am able to add the icon (font-awesome) with the .prepend but the arrow is still present. How to turn off the default arrows for open and closed so just my font-awesome icons are present.

**Comment by mbraak** [comment]
You can set the [openedIcon](http://mbraak.github.io/jqTree/#options-openedicon) and [closedIcon](http://mbraak.github.io/jqTree/#options-closedicon) options for that. Also see [this example](http://mbraak.github.io/jqTree/examples/10_icon_buttons.htm).

But these icons are then the same for the whole tree. You can't change them based on for example the node type.

**Comment by ehrenfeu** [comment]
Different icons based on the node type or e.g. the node level would indeed be very nice! I'd love to see this feature!

**Comment by ehrenfeu** [comment]
I found a way to achieve this: if nodes are having a "class" entry, you can use the [onCreateLi](http://mbraak.github.io/jqTree/#options-oncreateli) function to process the node's HTML part and insert a custom icon.
I'll finish up my code and post an example here!

**Comment by mbraak** [comment]
I'm certainly interested in that.
