### ISSUE TITLE
In case of Lazy Loading tree, Load some nodes initially and show particular node as a selected.

### ISSUE THREAD

**Issue by sanjaysemilo** [mbraak/jqTree#355]
I am calling GetType Method from Js as follows:

$('#tree').tree({
    dataUrl: '/api/GetType',
    dragAndDrop: false,
    useContextMenu: false 
});

My controller implementation is like this:

       public IEnumerable<TypeTreeViewModel> Get()
        {
            return this.Get(null);
        }

        public IEnumerable<TypeTreeViewModel> Get(int? node)
        {
            var children = this.typeService.GetTypes(node);                

            return children.Select(x =>
                new TypeTreeViewModel
                {
                    Id = x.Id,
                    Code =  x.Number ,
                    Name = x.Name,                   
                    LoadOnDemand = true,                  
                });
        }

On page load I want to show one child node as a selected.

I dont on to load all other unrelated node. only parent nodes related to node which we want to select should be there.

How we will achive this using jqtree?

**Comment by mbraak** [comment]
I don't recognize your controller code. Is it written in Java?

**Comment by sanjaysemilo** [comment]
It is a c# code. This functions returns data in the json foramt as follow:
[{"id":13,"label":"D type","code":"D","load_on_demand":true}, {"id":23,"label":"M type","code":"M ", "load_on_demand":true }]

We have view model for conversion as follow:

 [DataContract]
    public class TypeTreeViewModel
    {
        [DataMember(Name = "id")]
        public int Id { get; set; }
     
        [DataMember(Name = "label")]
        public string Name { get; set; }

        [DataMember(Name = "code")]
        public string Code { get; set; }     

        [DataMember(Name = "load_on_demand")]
        public bool LoadOnDemand { get; set; } 
    }

**Comment by sanjaysemilo** [comment]
It is a c# code. This functions returns data in the json foramt as follow:
[{"id":13,"label":"D type","code":"D","load_on_demand":true}, {"id":23,"label":"M type","code":"M ", "load_on_demand":true }]

We have view model for conversion as follow:

[DataContract]
public class TypeTreeViewModel
{
[DataMember(Name = "id")]
public int Id { get; set; }

    [DataMember(Name = "label")]
    public string Name { get; set; }

    [DataMember(Name = "code")]
    public string Code { get; set; }     

    [DataMember(Name = "load_on_demand")]
    public bool LoadOnDemand { get; set; } 
}

**Comment by sanjaysemilo** [comment]
It is a c# code. This functions returns data in the json foramt as follow:
[{"id":13,"label":"D type","code":"D","load_on_demand":true}, {"id":23,"label":"M type","code":"M ", "load_on_demand":true }]

We have view model for conversion as follow:

[DataContract]
public class TypeTreeViewModel
{
    [DataMember(Name = "id")]
    public int Id { get; set; }

    [DataMember(Name = "label")]
    public string Name { get; set; }

    [DataMember(Name = "code")]
    public string Code { get; set; }     

    [DataMember(Name = "load_on_demand")]
    public bool LoadOnDemand { get; set; } 
}

**Comment by mbraak** [comment]
I can't help you with the c# code.

Does your server code know which node is selected?

**Comment by sanjaysemilo** [comment]
If I put load_on_demand = false for some nodes. in that case this nodes will load initially ?

**Comment by sanjaysemilo** [comment]
I mean, if i will add load_on_demand = false for some nodes then in that case this nodes children's will load on the initialization?

**Comment by mbraak** [comment]
No, it will not do that. In that case jqtree will assume that the node has no children.

Note that you don't have to specify ``load_on_demand = false`` because it's the default value.

**Comment by sanjaysemilo** [comment]
In case of lazy loading is it possible to lode some node explicitly and some node on demand in the tree.

for eg:

-A
 '-- AB
       '--ABC
-B
-c

In above example load hierarchy A->AB->ABC explicitly and show "ABC" as selected and Node "B" and 
"C" will load on demand(on click of node)

**Comment by mbraak** [comment]
Yes, your json data should look something like this:

```js
[
  "label": "A"
  "children": [
    {
      "label": "B",
      "children": [
        {
          "label": "C"
        }
      ]
    }
  ],
  {
    "label": "B",
    "load_on_demand": true
  },
  {
    "label": "c",
    "load_on_demand": true
  }
]
```

**Comment by sanjaysemilo** [comment]
ok......thanks for the help :+1:
