### ISSUE TITLE
JqTree breaks on drag after nodeUpdate

### ISSUE THREAD

**Issue by Pulstarter** [mbraak/jqTree#356]
Hi!

I have a JqTree with update options and drag and drop which breaks when I try to drag an element after execute nodeUpdate function. I have prepared a demo site here:

http://datatool.presenciadigital.es/familias

The way to reproduce the problem is:

1- Double-click on the last node (VARIOS) and press "Guardar"
2- Try to drag it and insert after ELECTRÓNICA

The tree breaks and console launch this error:

tree.jquery.js:2179 Uncaught TypeError: Cannot read property 'addChildAtPosition' of null

Tested on latest versions of Firefox, Chrome and IE

Glad you could help. 

Best regards,
Iker

**Comment by mbraak** [comment]
I added a fix to the *dev* branch. Hopefully this will the bug.

Greetings,
Marco

**Comment by Pulstarter** [comment]
Tested and works fine now! 

Thanks a lot and best regards,
Iker
