### ISSUE TITLE
appendNode with AutoOpen = True, AutoOpen is not working

### ISSUE THREAD

**Issue by jitugupta** [mbraak/jqTree#359]
I have created the tree with property set as autoOpen = TRUE(say a "ParentCategory" created, as of now which doesnt have any child nodes), now i am trying to append some child nodes to "ParentCategory" and wanted parent to be autoOpen.

But when i do appendNode, its still shows closed. How can i make the "ParentCategory" in opened state after adding child nodes.

**Comment by mbraak** [comment]
The ``autoOpen`` option only works when you initially create the tree. It doesn't work when you later add nodes.

So, this example works:

```js
var data = [
    {
        label: 'node1', id: 1,
        children: [
            { label: 'child1', id: 2 },
            { label: 'child2', id: 3 }
        ]
    },
    {
        label: 'node2', id: 4,
        children: [
            { label: 'child3', id: 5 }
        ]
    }
];

$('#tree1').tree({
    data: data,
    autoOpen: true
});
```

You can also open nodes using the [openNode](http://mbraak.github.io/jqTree/index.html#functions-opennode) function.

**Comment by jitugupta** [comment]
Thanks a lot!
It worked.
