### ISSUE TITLE
$tree.tree('getSelectedNode'); has a bug?

### ISSUE THREAD

**Issue by CHAAAAA** [mbraak/jqTree#361]
$tree.tree('getSelectedNode'); it can't return the result when the selected NODE has parent. It always return FALSE.

**Comment by mbraak** [comment]
I will try to reproduce the bug. How do you select the node? With a mouse click?

**Comment by CHAAAAA** [comment]
Yes . With a mouse click.

**Comment by CHAAAAA** [comment]
I get why. When I click a NODE the page will refresh,so it can't get the selected NODE. I'm sorry...

**Comment by mbraak** [comment]
ok. great

**Comment by CHAAAAA** [comment]
Can I remove a NODE's background color? Is there a function?

**Comment by mbraak** [comment]
It's best to style the tree using css. Also [jqtree.css](https://github.com/mbraak/jqTree/blob/master/jqtree.css)

**Comment by CHAAAAA** [comment]
OK. Thanks for your reply.
