### ISSUE TITLE
moving node - parent id

### ISSUE THREAD

**Issue by jkardynia** [mbraak/jqTree#362]
When i try to get value of moved node parent id then I get old parent id. 
I bind to event:
```
$('#tree').bind('tree.move', function(event) {
    console.log(event.move_info.moved_node.parent.id);
    console.log(event.move_info.previous_parent.id);
}
```
and I got the same id in output, but if I use setTimeout function to delay operation I got proper result with different ids in output. How can I get proper values without setTimeout?

**Comment by mbraak** [comment]
The ``moved_node.parent.id`` is indeed the parent before the move.

You can find out the new parent by looking at the ``target_node`` and ``position`` properties:

```js
var position = event.move_info.position;
var target_node = event_move_info.target_node;

if (position == 'inside') {
  // new parent is target_node
  console.log(target_node.id);
}
else {
  // position is 'before' or 'after'
  // new parent is parent of target node
  console.log(target_node.parent.id);
}
```

**Comment by jkardynia** [comment]
This works great. Thank you for help :)
