### ISSUE TITLE
Select Node without triggering event

### ISSUE THREAD

**Issue by jxc876** [mbraak/jqTree#364]
I want to select a Node without trigger the '*tree.select*' event. In other libraries, ex: jqGrid, I can do the following:

    $grid.setSelection(rowid, onselectrow)

* **Description**: Toggles a selection of the row with id = rowid; *if onselectrow is true (the default) then the event onSelectRow is launched, otherwise it is not*.

**Comment by mbraak** [comment]
I think you can use the [addToSelection](http://mbraak.github.io/jqTree/#multiple-selection-add-to-selection) function. It does not trigger the ``tree.select`` event.

**Comment by jxc876** [comment]
Thanks @mbraak that did the trick
