### ISSUE TITLE
Select a node using its properties?

### ISSUE THREAD

**Issue by WebBizMedia** [mbraak/jqTree#365]
Hello, 
is there a way to select a node using its properties, not using id?

example:

[{"name":"home",  "visibility":"true"}]
var thisNode = $tree.tree('visibility', 'true');

**Comment by mbraak** [comment]
You can use the ``getNodesByProperty`` function.

Note that this function returns a list of nodes. And you only use a single property:

```js
        var nodes = $tree.tree('getNodesByProperty', 'visibility', true);
```
