### ISSUE TITLE
Expand all branches  of a selected node.

### ISSUE THREAD

**Issue by husseinkhatib** [mbraak/jqTree#366]
Hi Mbraak,

Is there any function to open all BRANCHES OF THE SELECTED NODE?

**Comment by mbraak** [comment]
You could do something like this:

```js
// open children of node 'Saurischia'
var node = $tree.tree('getNodeByName', 'Saurischia');

node.children.forEach(function(child) {
    if (child.isFolder()) {
        $tree.tree('openNode', child);
    }
});
```

Note that this example uses the ``Array.forEach`` function, which is not available in ie8.

**Comment by husseinkhatib** [comment]
Sorry mbraak , I executed you suggestion code the result as following:
not all branches of selected node will opened. they opened only  the parents below the selected node.

**Comment by mbraak** [comment]
You could do the following:

```js
var node = $tree.tree('getNodeByName', 'Saurischia');

node.iterate(function(child) {
    if (child.isFolder()) {
        $tree.tree('openNode', child);
    }

    return true;
});
```

**Comment by husseinkhatib** [comment]
Thank you for help :)
