### ISSUE TITLE
Is there a cashing option?

### ISSUE THREAD

**Issue by husseinkhatib** [mbraak/jqTree#370]
Is there a caching option

**Comment by mbraak** [comment]
Do you mean caching?

**Comment by husseinkhatib** [comment]
yes

**Comment by mbraak** [comment]
What exactly do you want to cache?

**Comment by husseinkhatib** [comment]
What i want is to disabled the caching

**Comment by mbraak** [comment]
I've looked in the code. When jqTree loads data from an url, it disables the cache.

Also [this line in the source code](https://github.com/mbraak/jqTree/blob/master/src/tree.jquery.coffee#L186).

**Comment by husseinkhatib** [comment]
ok
