### ISSUE TITLE
How to move whole node and children to a new tree ?

### ISSUE THREAD

**Issue by eliseubaldo** [mbraak/jqTree#371]
Hello! 

I'm trying to move a selected node:
      var seletedNode = $('#tree1').tree('getSelectedNode');

into a new tree:
                                       $('#cliptree').tree({
					data: seletedNode,
					saveState: 'my-tree3',
					autoOpen:true,
					dragAndDrop:true				
					
					});

But my seletedNode returns an object. Is there a simple way to do this?

BTW, Amazing plugin! thank you!

**Comment by mbraak** [comment]
The node object has a [getData](http://mbraak.github.io/jqTree/#node-functions-getdata) function that returns suitable data for a new tree:

```js
var selectedNode = $('#tree1').tree('getSelectedNode');

$('#cliptree').tree({
  data: selectedNode.getData()
});
```

Does this work in your situation?

**Comment by eliseubaldo** [comment]
Thank you for your answer.

It doesn't work. I get a typeError: selectedNode.getData is not a function.

In fact what I am trying to do is a way to  drag a node into another tree. Since that didn't work, I thought to create a "clipboard" to store a node then add it into the new tree.

Do you think it can be done using only drag & drop ?

**Comment by mbraak** [comment]
No, drag & drop only works in a single tree.

It's strange you get a type error. The function ``getSelectedNode`` returns null or a Node object. A Node object should have a ``getData`` function.

**Comment by eliseubaldo** [comment]
I Managed to get the data using the getData, but it only gets the "children". Is there a way to get the selected parent also ?

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
I added a ``include_parent``parent to the ``getData`` function. I added this to the *dev* branch of jqTree.

```js
var data = node.getData(true);
```
