### ISSUE TITLE
Open parent node by clicking on title not the icon

### ISSUE THREAD

**Issue by Shad0wLi0n** [mbraak/jqTree#372]
I'd like to trigger parent nodes open by clicking on the text not the arrow icon. I didn't see a built in option for this but I thought it would be a no brainer. How can I accomplish this?

**Comment by mbraak** [comment]
I think this is the same as [issue 71](https://github.com/mbraak/jqTree/issues/71).

**Comment by Shad0wLi0n** [comment]
Thanks that solves my issue.
