### ISSUE TITLE
Is there any event triggering when tree fully loaded?

### ISSUE THREAD

**Issue by SergeyBan** [mbraak/jqTree#373]
I have read documentation a few times and as I understood there is no event which can be triggered when the tree is fully loaded. It would be nice to have such event.

**Comment by mbraak** [comment]
The [tree.init](http://mbraak.github.io/jqTree/#event-tree-init) is called when the data is loaded.

Or do you mean something else with fully loaded?

**Comment by SergeyBan** [comment]
Yeah. Sorry, I just not understood from name that this event is triggered when the tree is loaded. But there is one issue. I would like to trigger similar event when the is rebuilt after drag-and-drop any node. Is it possible?

**Comment by mbraak** [comment]
The ``tree.refresh`` event is triggered when the tree is rendered. So, also after drag-and-drop. I see that this event is not documented yet.

The [tree.move](http://mbraak.github.io/jqTree/#event-tree-move) is called before the move.

Does this help?

**Comment by SergeyBan** [comment]
Yes! Thank you! You are right there is no description of event tree.refresh in documentation.

**Comment by husseinkhatib** [comment]
Could you please send me a sample how we can use the tree.refresh?

thank you in advance.

**Comment by mbraak** [comment]
You can use ``tree.refresh`` like this:

```js
$('#tree1').on('tree.refresh', function() {
  // This function is called after the tree rendered
});
```

I personally never use this event. Depending on your use case there are other options:

* [tree.init](https://mbraak.github.io/jqTree/#event-tree-init) which is called after the tree data is loaded.
* [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) to customize the rendering of the tree.

**Comment by husseinkhatib** [comment]
Why when i re draw the tree the function of the tree did not work?

**Comment by mbraak** [comment]
How exactly do you redraw the tree?

**Comment by husseinkhatib** [comment]
$('#tree1').tree({
			data: data,
			autoOpen: false,
			dragAndDrop: true,
			load_on_demand:true,
			cache: false, 
			closedIcon: '&lt;i class="fa fa-chevron-right " style="margin-left:3px" &gt;&lt;/i&gt;',
			openedIcon: '&lt;i class="fa fa-chevron-down " style="margin-left:2px" &gt;&lt;/i&gt;' 
		});

**Comment by mbraak** [comment]
And after that you connect the ``tree.refresh`` event?

In this case the ``tree.refresh`` will not be fired because the tree is rendered **before** you connect the event.
I think it will be fired when you do drag-and-drop or when you load a node on demand.
