### ISSUE TITLE
crash while moving node

### ISSUE THREAD

**Issue by kodok-buncit** [mbraak/jqTree#374]
hello, jqtree crash while i add ajax function on 'tree.move' event
```   
 $tree.bind('tree.move',function(e){
        e.preventDefault();
        e.move_info.do_move();
        $.ajax({
        	url : App.base_url+'/admin/categories/move',
        	method : "POST",
        	dataType : "json",
        	async: false,
        	data : {moved_node : e.move_info.moved_node, target_node : e.move_info.target_node}
        }).success(function(response){
        	return;
        });
    });
```

its work when i removing ajax call.

**Comment by mbraak** [comment]
Hello,

The ``e.move_info.moved_node`` property is a ``Node`` object. I think that you can't use it for the ajax data. Same for ``e.move_info.target_node``.

I think you can use the ``id`` of the nodes:

```js
data: {
  moved_node: e.move_info.moved_node.id,
  target_node : e.move_info.target_node.id
}
```

If you use this, then the nodes must have an ``id`` property.

Hope this works!

**Comment by kodok-buncit** [comment]
oooh ya my fault indeed, now its work!
thanks
