### ISSUE TITLE
conflict in magento [jquery and prototype]

### ISSUE THREAD

**Issue by henrydeguzman** [mbraak/jqTree#375]
Hi mbraak this plugin is pretty good, but when i used it in magento, there's a conflict between 2 javascript libraries like prototype that was built-in in magento core, and secondly is jquery. There is a common solution about the conflict that was a jquery noflict but it's not working, i'm little bit sure it was the core of the jqtree.js found that prototype and jquery was merge. how am i supposed to overide this conflict ? please tell me sir. tnx

**Comment by henrydeguzman** [comment]
(function ($){
        var indexRealstate = {
            init: function(){
                $(document).ready(this.exe_readyfunction);
            },
            exe_readyfunction: function(){
                var data = [
                    {
                        label: 'node1',
                        children: [
                            { label: 'child1' },
                            { label: 'child2' }
                        ]
                    },
                    {
                        label: 'node2',
                        children: [
                            { label: 'child3' }
                        ]
                    },
                    {
                        label: 'node2',
                        children: [
                            { label: 'child3' }
                        ]
                    }
                ];
                $('#tree1').tree({
                    data: data,
                    autoOpen: true,
                    closedIcon: '+',
                    dragAndDrop: true
                });
            }
        };
        indexRealstate.init();
    })($j);


in console.log
Uncaught TypeError: $.data is not a function


script call order:
prototype.js
tree.jquery.js
jquery.min.js
jquery.noconflict.js

**Comment by henrydeguzman** [comment]
and i tried reorder the js calls:
prototype.js
jquery.min.js
jquery.noconflict.js
tree.jquery.js

**Comment by mbraak** [comment]
Hello

Thanks for reporting this error. I have updated jqTree so that it uses ``jQuery`` instead of ``$``. Hopefully this will fix the prototype conflict.

The fix is in the *dev* branch of the git repository.

Greetings

**Comment by henrydeguzman** [comment]
Yeah! tnx! im looking forward to try it again tomorrow. your really cool buddy. your jqTree is very helpful
