### ISSUE TITLE
Having trouble with scrollToNode

### ISSUE THREAD

**Issue by atlantageek** [mbraak/jqTree#376]
I'm having trouble with getting scrollToNode to work.
The jqtree code is here: http://99.36.180.46
If you go to "Text search" on the right side and search for docsis Hit the link it should open the tree and then select the found node.  Afterwards a 1 second timeout will occur to scroll to the selected node.  The timeout was just me trying to make sure everything is loaded.  Does anyone have suggestions for resolving this. 
The code is in the loadSubTree function.
     function loadSubtree(value) {
         var $tree = $('#tree1');
          $.get('/uptree?oid='+value, null, function(result) {
             if (result.status == "FAIL") {
              $('#status').text(result.message);
            }
            else {
              $('#status').text("");
              data = result.data
              $tree.tree('loadData',data);
              $.get("/getId?oid=" + value).done(function(data) {
              var node = $tree.tree('getNodeById', data);
              if (node.children.length > 0) {
                 $tree.tree('openNode',node, false);
               }
               $tree.tree('selectNode',node, false);
                setTimeout(function() {
                $tree.tree('scrollToNode', node);
                 }, 3000);
  
	      });
	    }
	  });
      }

**Comment by mbraak** [comment]
I had a look at the url you mentioned. Unfortunately the site seems to be down now.

About the following code:

```js
$.get("/getId?oid=" + value).done(function(data) {
    var node = $tree.tree('getNodeById', data);
    if (node.children.length > 0) {
        $tree.tree('openNode',node, false);
    }
}
```

The ``data``result from ``/getId``, does it contain a node id?

**Comment by atlantageek** [comment]
Yeah. the 'node' variable is set.
The website is back up and should stay up now.  Could you look at it.
 99.36.180.46

On Mon, May 11, 2015 at 3:00 AM, Marco Braak <notifications@github.com>
wrote:

> I had a look at the url you mentioned. Unfortunately the site seems to be
> down now.
>
> About the following code:
>
> $.get("/getId?oid=" + value).done(function(data) {
>     var node = $tree.tree('getNodeById', data);
>     if (node.children.length > 0) {
>         $tree.tree('openNode',node, false);
>     }
> }
>
> The dataresult from /getId, does it contain a node id?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraak/jqTree/issues/376#issuecomment-100789973>.
>



-- 
http://www.atlantageek.com

**Comment by mbraak** [comment]
I noticed that the ``data`` in the ``loadSubtree`` function looks a bit strange.

Some nodes have children, yet the ``load_on_demand`` property is ``true``. I think that confuses jqTree. It would probably be better if you set ``load_on_demand`` to false in this case. This might be related to the ``scrollToNode`` error.

**Comment by atlantageek** [comment]
Thanks.  That seems to have been the issue.

On Mon, May 11, 2015 at 7:44 AM, Marco Braak <notifications@github.com>
wrote:

> I noticed that the data in the loadSubtree function looks a bit strange.
>
> Some nodes have children, yet the load_on_demand property is true. I
> think that confuses jqTree. It would probably be better if you set
> load_on_demand to false in this case. This might be related to the
> scrollToNode error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mbraak/jqTree/issues/376#issuecomment-100882123>.
>



-- 
http://www.atlantageek.com
