### ISSUE TITLE
getState does not return ID -

### ISSUE THREAD

**Issue by zapperClone** [mbraak/jqTree#380]
My tree's IDs are strings so that, when clicked, I use the strings as parameters for an Ajax call to load other pages into a content panel within the page. I outputted the result of `getState()`, and this is what I got:
           ```
           Object { open_nodes=[3],  selected_node=[1]}```

**Comment by mbraak** [comment]
That is strange, jqTree should work fine with string id's.

Note that you can also use [getSelectedNode](https://mbraak.github.io/jqTree/#functions-getselectednode) to get the selected node.
