### ISSUE TITLE
keyboard navigation and multiple trees in a dom.

### ISSUE THREAD

**Issue by ScarfaceIII** [mbraak/jqTree#382]
Hi, I am successfully using this widget, but I had to disable the keyboardSupport, here's the reason:
I had two different trees in the page, attached to different divs, with different ids.
Here's how they appear
![1](https://cloud.githubusercontent.com/assets/6950554/7747711/199dc6d2-ffb5-11e4-9f6a-d0c200e86609.png)
and here's that part of the page structure, the two divs whose ids end with "tree" are the ones I attach the tree to.
![2](https://cloud.githubusercontent.com/assets/6950554/7747717/27fc0afe-ffb5-11e4-95b4-ea94e100b418.png)

If I selected an item in the first tree and an item in the second tree and started navigating with the keyboard, I was able to act on both trees at the same time.

On a side note: I have read this in the changelog "Issue 260: Exempt ‘select’ elements from keyboard navigation", but that doesn't seem to happen. When I navigated the tree with the keyboard, each element I was going through was being selected. I tried to use the "event" object passed to the callback function for "tree.select", but it didn't contain any clues of the source of the event (eg. mouse vs keyboard).

**Comment by mbraak** [comment]
Yes. I know this problem. I added the ``keyboardSupport`` option to fix the problem with two trees. It's not the most elegant solution. I am certainly interested in a better solution.

I think that issue 260 is the following: jqTree should not handle the keyboard if an input element has the keyboard focus. So, that would be a text ``<input>``, but also a ``<select>`` input.

**Comment by ScarfaceIII** [comment]
Thanks for quick reply Marco, I'll be following updates on this and eventually let you know if I find anything about it.

Now I get what issue 260 was about, thanks for the clarification, much appreciated. On this note, if I may suggest, it would be good to separate keyboard navigation from selection, so, say I navigate with arrow keys, but select with spacebar or enter. That way if I have an event attached to node selection it won't get triggered by keyboard navigation.
