### ISSUE TITLE
Is it possible to combine "saveState" and "load_on_demand"?

### ISSUE THREAD

**Issue by ehrenfeu** [mbraak/jqTree#383]
I do have a working implementation of loading the nodes of my tree from the server, on demand. However, I'd like to combine it with the functionality to remember the state of a tree, so when a user navigates away and returns to the tree, the nodes are expanded (and re-loaded perhaps from the server) according to the previous state.

The comments in issue #334 lead me to believe this is not possible right now, but maybe I am wrong?

**Comment by mbraak** [comment]
The latest version of jqTree supports saving the state for load-on-demand trees. I believe version 1.0 supports it. Also see issue #273 and [this example](https://mbraak.github.io/jqTree/examples/05_load_on_demand.html).

I will add a note to issue #334.

**Comment by ehrenfeu** [comment]
Thanks for the superfast reply! I'll try with the latest version and let you know how it goes.

**Comment by ehrenfeu** [comment]
It works great, and it shamelessly reveals the perfomance problems of my prototoype :wink:
