### ISSUE TITLE
plugin breaks if jqtree is loaded along with scriptaculous

### ISSUE THREAD

**Issue by hbayyavarapu** [mbraak/jqTree#385]
$(node.element)
$(position_info.target);
return $(li)
$.extend
$.Event
 $(document)
return $(el)
....
several of the calls to dom breaks the plugin

**Comment by mbraak** [comment]
I think this big is related to issue #375 which fixes a problem with prototype.js.

Note that issue #375 is fixed in the **dev** branch of jqTree.

**Comment by hbayyavarapu** [comment]
I wrapped the entire code into this function and it works now.
(function($) {
   //jqtree code
}(jQuery));
