### ISSUE TITLE
Tree length

### ISSUE THREAD

**Issue by movie4** [mbraak/jqTree#387]
It's possible to get all nodes and tree length.
like: `$('#tree1').tree('getNodes')`;

Thanks

**Comment by mbraak** [comment]
You can get the tree data using the [getTree](https://mbraak.github.io/jqTree/#functions-gettree). This gives you the root node.

You can then iterate over the nodes to create a list:

```js
var tree_data = $('#tree1').tree('getTree');

var nodes = [];

tree_data.iterate(function(node) {
    nodes.push(node);

    return true;
});

console.log(nodes);
```

**Comment by movie4** [comment]
Thank!
