### ISSUE TITLE
Any Lines for the Tree?

### ISSUE THREAD

**Issue by jimiayler** [mbraak/jqTree#388]
Marco -- This is a beautifully smooth, richly featured tree widget. And while you address the unlikelihood of having dotted lines describe the hierarchical relationship between nodes, a la YUI:

https://github.com/mbraak/jqTree/issues/161

you have also left this issue open. I'm wondering if there is an ability to define  _any_ lines within jqTree to outline the parent/child structures. Although not present in some jQuery tree controls, this is currently a requirement, based on other tree widgets that do allow for these. Please advise and thanks.

j

**Comment by mbraak** [comment]
The dotted lines are implemented in [Plain-jqTree-Theme](https://github.com/artlung/Plain-jqTree-Theme).

I have seen this working in an older version of JqTree. I have not tested it in the latest version.

**Comment by jimiayler** [comment]
Ah, very cool -- you may want to close out the open issue about dotted lines accordingly. Thanks very much for the quick reply.
