### ISSUE TITLE
scrollToNode issued

### ISSUE THREAD

**Issue by daletune** [mbraak/jqTree#390]
I create jsbin to show my problem.
https://jsbin.com/hewica/8/edit?js,output

The problem occurs when tree in scrollable container. So first scrollToNode works well, but second scroll only on delta between previous and ignores previous scroll.

I guess in file tree.jquery.coffee in method scrollToNode on line 400 change could be:
top = $element.offset().top - @$el.offset().top + @$el.scrollTop();

I could create pull request if needed.

**Comment by mbraak** [comment]
Thanks for the bug report. I will look into it.

**Comment by mbraak** [comment]
I made some changes to your jsbin example, and then it seems to work: https://jsbin.com/lelenuwusi/1/edit?html,css,js,output

I set the overflow of the container to `scroll`, and I removed the overflow from the tree element.

```html
<div style="height: 400px; overflow: scroll">
  <div id="tree"></div>
</div>
```

I also removed the default `ul` margin:

```css
ul.jqtree-tree {
  margin: 0;
}
```

I hope this solution works in your situation.

**Comment by daletune** [comment]
Thank you, **mbraak**.
That works absolutely right in my situation!
Awesome widget by the way, super fast (compare to kendo e.g.)
