### ISSUE TITLE
Node's data is wrong on second dblclick

### ISSUE THREAD

**Issue by csunali** [mbraak/jqTree#392]
`event.node.load_on_demand` value unexpectedly returns false after the first double click, in case the data was loaded using the `data-url="/url/to/json"` format.

The first dblclick event works fine and returns `true` if the node's data had it as `true` but then it always returns `false` even for those that had it `true`.

I have the latest version.

**Comment by mbraak** [comment]
When jqTree loads a node on demand, it sets the property ``load_on_demand`` value of the node to ``false``.

Is it possible that this explains the behavior that you described?

**Comment by csunali** [comment]
Hey,

Indeed it explains. So what I understand is that it is not "wrong data" but "by design".

Here is my scenario, I want to add double click functionality to expand/collapse items but want to call the `toggle` method only if the item might have children nodes. So I thought, checking `load_on_demand` returned from my json endpoint was the right thing to do. What do you suggest me doing? May be adding another `boolean` property within my json for each node, one that you would not overwrite?

I have realized one more thing, whenever I want to handle the `dblclick` event, I realize the `select` event also gets triggered. However, considering my scenario, the user does not select the node but just double clicks. I also end up losing the originally selected node. Is it possible to avoid the `select` event being triggered in an event of double clicking and made it selected only on a single click?

**Comment by mbraak** [comment]
The event object for the ``tree.dblclick`` event has a ``node`` property. The node property has a ``isFolder`` function:

```js
$('#tree1').on('tree.dblclick', function(e) {
    var node = e.node;

    if (node.isFolder()) {
        $tree.tree('toggle', node);
    }
});
```

You can prevent the selection of a node by calling ``preventDefault`` in the ``tree.click`` event:

```js
$('#tree1').on('tree.click', function(e) {
    e.preventDefault();
})
```

But this works for both single and double clicks. I don't know how you can do this only for the double clicks.

**Comment by csunali** [comment]
I did not know about the `isFolder` method and it seems to solve my issue.

I know about the `preventDefault` but yes, the `click` and `dblclick` issue seems to be an OS/Browser wide issue, rather than being specific to your plugin.

Thank you for the feedback, very much appreciated.
