### ISSUE TITLE
Close previous node prior to opening new one

### ISSUE THREAD

**Issue by jmashore** [mbraak/jqTree#393]
I would like to change the behaviour of the tree a bit. If the user clicks on a new node that has children, I would like it to close all the open sibling nodes before it opens the new node. So the user is always looking at only one branch of the tree at a time. 

For instance if I have a tree that looks like
<ul>Widgets (has children)
<li><ul> Green Widgets (has children)
<li>With buckles</li>
           <li>Without Buckles</li></ul></li>
      <li><ul>Red Widgets (has children)
                   <li>With Buckles</li>
                   <li>Without buckles</li></ul>
</ul>

And I was looking at Red Widgets(expanded), but then clicked on Green Widgets, I would like the Red Widgets Branch to automatically collapse. 

Thanks !
Jim

**Comment by mbraak** [comment]
That sounds interesting. I think this is possible by catching the [tree.open](https://mbraak.github.io/jqTree/#event-tree-open) event.

I'll see if I can write a small example tomorrow.

**Comment by mbraak** [comment]
The following code closes the previous node when you open a node. It is a bit longer than expected because it handles some edge cases.

I think it's better to deactivate the slide animation, because otherwise the previous node is closed after the animation:

```js
$('#tree1').tree({
    slide: false
});
```

```js
// assume tree is in #tree1
var $tree = $('#tree1');

var previous_node = null;

$tree.on('tree.open', function(e) {
    var node = e.node;

    // Get highest parent of 'previous_node'
    // - Exclude current node and its parents
    var node_to_close = getHighestParent(
        previous_node,
        getNodeAndParents(node)
    );

    if (node_to_close) {
        $tree.tree('closeNode', node_to_close, false);
    }

    previous_node = node;
});

/* Return node and parents (except root node)
*/
function getNodeAndParents(node) {
    var nodes = [];
    var n = node;

    while (n) {
        // is not root node?
        if (n.parent) {
            nodes.push(n);
        }

        n = n.parent;
    }

    return nodes;
}

/* Return the parent of 'node' that is
    - highest in the tree (but not the root node)
    - not in 'exclude_nodes'
*/
function getHighestParent(node, exclude_nodes) {
    if (!node) {
        return null;
    }
    else {
        var highest_parent = null;
        var n = node;

        while (n) {
            if (exclude_nodes.indexOf(n) >= 0) {
                // Node is excluded
                return highest_parent;
            }
            else if (!n.parent) {
                // Root node
                return highest_parent;
            }
            else {
                highest_parent = n;
                n = n.parent;
            }
        }

        return null;
    }
}
```

**Comment by jmashore** [comment]
Thanks...that works perfectly for me. I had tried several variations but looking at your code, I can clearly see I was missing a lot of the details ! This is an excellent feature for those that want to "clean up" their list as the user moves through it.
