### ISSUE TITLE
Label displays 'null' in UI when the label key is null

### ISSUE THREAD

**Issue by inmortalnet** [mbraak/jqTree#394]
In line 1022, when the value of the label key is null, it assigns the null value to this.name, resulting in displaying 'null' in the UI.

Maybe it should validate if the value is null and apply an empty string for this.name

  Node.prototype.setData = function(o) {
    var key, value;
    if (typeof o !== 'object') {
      this.name = o;
    } else {
      for (key in o) {
        value = o[key];
        if (key === 'label') {
          this.name = value;
        } else {
          this[key] = value;
        }
      }
    }
    return null;
  };

**Comment by mbraak** [comment]
Sound like a good idea! I will have a look at it.

**Comment by mbraak** [comment]
This is now fixed in the dev branch. If a label is `null`, then the tree displays an empty string.

**Comment by inmortalnet** [comment]
Cool! Great job by the way, we have this running on one of our projects, thanks!
