### ISSUE TITLE
tree.init is too early in the save.state restore process

### ISSUE THREAD

**Issue by jmashore** [mbraak/jqTree#396]
When I am using the saveState set to true, and my user navigates back to the page, the state of the tree is correctly rendered including the last selected child. However, I need to know what that child node is. I've tried to use the tree.init function, but it appears to be firing before the tree is fully loaded.How do I catch when the tree is completely intialised<sp> and rendered from that saved state ?
I should also note here, that the selected node (child) is a result of a load on demand from the parent.

So at the time of tree.init() from a saved Tree, my tree.JSON looks like :

[{"id":"ET19","name":"Swather Belts","load_on_demand":true,"is_loading":true},{"id":"ET20","name":"Combine Belts","load_on_demand":true},{"id":"ET21","name":"Baler Belts","load_on_demand":true}]

But the screen looks like

**Comment by mbraak** [comment]
I'll try to reproduce this bug. Do you have a screenshot of this error?

**Comment by mbraak** [comment]
Thanks for reporting this bug. It is now fixed in the `dev` branch.

Could you please confirm if the issue is fixed?

**Comment by jmashore** [comment]
Marco,

I updated my code with your dev branch, but the problem persists. I 
tried to attach a screen shot last night but it github kept throwing it 
back. I'm going to try via this email and see if I can get it in.

When the tree.init fires I get this from tree.toJSON :
[{"id":"ET19","name":"Swather 
Belts","load_on_demand":true,"is_loading":true},{"id":"ET20","name":"Combine 
Belts","load_on_demand":true},{"id":"ET21","name":"Baler 
Belts","load_on_demand":true}]

But the screen looks like this :


On 8/14/2015 2:28 AM, Marco Braak wrote:
>
> Thanks for reporting this bug. It is now fixed in the |dev| branch.
>
> Could you please confirm if the issue is fixed?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mbraak/jqTree/issues/396#issuecomment-131004393>.
>

-- 
Confidentiality Warning: This message and any attachments are intended 
only for the use of the recipient(s), are confidential, and may be 
privileged. If you are not the intended recipient, you are hereby 
notified that any review, retransmission, conversion to hard copy, 
copying, circulation or other use of all or any portion of this message 
and any attachments is strictly prohibited. If you are not the intended 
recipient, please notify the sender immediately by return email and 
delete this message and any attachments from your system.

**Comment by jmashore** [comment]
What the tree really looks like 
[{"id":"ET19","name":"Swather Belts","load_on_demand":false,"is_loading":false,"is_open":true,"children":[{"id":"EC22","name":"Accessories","load_on_demand":true},{"id":"EC24","name":"Autotran","load_on_demand":true},{"id":"EC28","name":"Case","load_on_demand":true},{"id":"EC35","name":"Case-IH","load_on_demand":true},{"id":"EC76","name":"Cereal Implement","load_on_demand":true},{"id":"EC78","name":"Cockshutt","load_on_demand":true},{"id":"EC86","name":"Ford","load_on_demand":true},{"id":"EC88","name":"Hesston","load_on_demand":false,"is_loading":false,"is_open":true,"children":[{"id":"EM89","name":"<a href='#' onclick='loadProductTableFromTree(\"89\")'>Model 1200</a>"},{"id":"EM90","name":"<a href='#' onclick='loadProductTableFromTree(\"90\")'>Model 420</a>"},{"id":"EM91","name":"<a href='#' onclick='loadProductTableFromTree(\"91\")'>Model 5000</a>"},{"id":"EM92","name":"<a href='#' onclick='loadProductTableFromTree(\"92\")'>Model 520</a>"},{"id":"EM93","name":"<a href='#' onclick='loadProductTableFromTree(\"93\")'>Model 6400</a>"},{"id":"EM94","name":"<a href='#' onclick='loadProductTableFromTree(\"94\")'>Model 6450</a>"},{"id":"EM95","name":"<a href='#' onclick='loadProductTableFromTree(\"95\")'>Model 6455</a>"},{"id":"EM96","name":"<a href='#' onclick='loadProductTableFromTree(\"96\")'>Model 6555</a>"},{"id":"EM97","name":"<a href='#' onclick='loadProductTableFromTree(\"97\")'>Model 6655</a>"},{"id":"EM98","name":"<a href='#' onclick='loadProductTableFromTree(\"98\")'>Model 8050</a>"},{"id":"EM99","name":"<a href='#' onclick='loadProductTableFromTree(\"99\")'>Model 8100</a>"},{"id":"EM100","name":"<a href='#' onclick='loadProductTableFromTree(\"100\")'>Model 8200</a>"},{"id":"EM101","name":"<a href='#' onclick='loadProductTableFromTree(\"101\")'>Model Double Windrow Attachment</a>"},{"id":"EM102","name":"<a href='#' onclick='loadProductTableFromTree(\"102\")'>Model Hesston</a>"}]},{"id":"EC103","name":"I-H","load_on_demand":true},{"id":"EC110","name":"John Deere","load_on_demand":true},{"id":"EC124","name":"M&amp;M","load_on_demand":true},{"id":"EC127","name":"Mac Don","load_on_demand":true},{"id":"EC130","name":"Massey Ferguson","load_on_demand":true},{"id":"EC145","name":"Massey Harris","load_on_demand":true},{"id":"EC148","name":"Minneapolis Moline","load_on_demand":true},{"id":"EC150","name":"New Holland","load_on_demand":true},{"id":"EC162","name":"Oliver","load_on_demand":true},{"id":"EC167","name":"Owatonna","load_on_demand":true},{"id":"EC180","name":"Renn","load_on_demand":true},{"id":"EC183","name":"Versatile","load_on_demand":true},{"id":"EC196","name":"Westward","load_on_demand":true},{"id":"EC199","name":"White","load_on_demand":true},{"id":"EC203","name":"You Do It Rolls","load_on_demand":true}]},{"id":"ET20","name":"Combine Belts","load_on_demand":true},{"id":"ET21","name":"Baler Belts","load_on_demand":true}]

**Comment by jmashore** [comment]
![jqex1](https://cloud.githubusercontent.com/assets/5324951/9276728/4fd2d4ec-426b-11e5-8f64-d43d46f6e5a6.jpg)

**Comment by jmashore** [comment]
I've been doing some thinking on this. I think I might be misleading the tree a little bit. But I still think this is a bug.

Here is my tree initialization 
        menuTree.tree({
                data: data,
                dataUrl: "gettree?action=gettree",
                autoOpen: true,
                dragAndDrop: false,
                autoEscape: false,
                saveState: true,
                slide: false,
                closedIcon: $('<i class="fa fa-arrow-circle-right"></i>'),
                openedIcon: $('<i class="fa fa-arrow-circle-down"></i>'),
            }
        ); 

**data** is always populated with something. So that if there were no "saved tree"  it would show at least one node.

So what I think is happening is the init process is seeing that **data** has a value, and is populating the tree then it fires the tree.init event, but then the script continues to run and see's there is a saved tree cookie (saveState: true,) and populates the tree with that data and no tree.init is fired because it was already fired with the "default" data.

**Comment by mbraak** [comment]
Thanks for the extra info. However, I could not reproduce the error.

If I set both a `data` and a `dataUrl` parameter, then the tree does not load data from the url.

I then removed the `data` option, and tried it on a tree with load-on-demand data:

```js
$tree.tree({
    saveState: true,
    dataUrl: "/nodes/",
    autoOpen: true,
    saveState: true
});

$tree.on('tree.init', function() {
    var n = $tree.tree('getSelectedNode');
    console.log(n);
});
```
This correctly prints the selected node.

**Comment by jmashore** [comment]
Can I bother you to try the following :
http://old.balerbelt.com/store/products
Click down a parent node until you bring up a product list on the right (onclick will print the tree.json via console.log)
Then click on "View Cart" then click back to "Continue Shopping". console log will have the tree information when it fires the init function.

**Comment by mbraak** [comment]
I see that you have load-on-demand nodes in the `data` parameter. That's something that I had not thought of. But of course it should work. I will look into it.

**Comment by mbraak** [comment]
The code seems to work using the lastest `dev` branch of jqtree. The `tree.init` event is fired after all the data is loaded.

I could not find the latest jqtree code on http://old.balerbelt.com/store/products. Is it possible that you are using an older version?

**Comment by jmashore** [comment]
I thought I had updated with the dev branch a few days ago. I'll try it again and make sure.

**Comment by jmashore** [comment]
I reloaded the dev branch and all seems to be working as expected. Thank you very much for all your help and time you put into this.
