### ISSUE TITLE
Loading async data when opening items

### ISSUE THREAD

**Issue by joni2back** [mbraak/jqTree#399]
Hello, I'm looking the posibility to do the following.
Im working with https://github.com/joni2back/angular-filemanager that is a ftp folder-navigator and have a folder-tree sidebar.

This sidebar is constructed with the user requests in order to dont use a (long-time) recursive function to get all directories.

So, there are the posibility to execute a kind of callback when the user clicks a node in order to push it all chidrens?

(Demo http://zendelsolutions.com/zendel/projects/angular-filemanager)
Regards.

**Comment by mbraak** [comment]
Hi,

This looks a bit like load-on-demand, see [this example](https://mbraak.github.io/jqTree/examples/05_load_on_demand.html).

Would load-on-demand work in your situation, or is it really different?

Cheers,
Marco
