### ISSUE TITLE
open node after reload

### ISSUE THREAD

**Issue by tr0yka** [mbraak/jqTree#400]
```javascript
$tree.tree('reload');
var node = $tree.tree('getNodeById', parentId);
$tree.tree('openNode', node);
```
This code not work.

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
I think I have found the problem. The `reload` function loads the new data from the server. You can open the `parentId` node **after** it has loaded the data.

You can do the following. Note that for this you need the latest jqtree code from the `dev` branch.

```js
$tree.tree('reload', function() {
    var node = $tree.tree('getNodeById', 1);
    $tree.tree('openNode', node);
});
```

Does this code work in your situation?

Greetings

**Comment by tr0yka** [comment]
````javascript
$tree.tree('reload', function() {
    var node = $tree.tree('getNodeById', 1);
    $tree.tree('openNode', node);
});
````
not working

**Comment by mbraak** [comment]
Is the `reload` callback working?

You can see this by adding a `console.log` and then checking your console:

```js
$tree.tree('reload', function() {
    console.log('reload callback');

    var node = $tree.tree('getNodeById', 1);
    $tree.tree('openNode', node);
});
```

**Comment by tr0yka** [comment]
no. console.log() not displayed

**Comment by mbraak** [comment]
That is strange. Note that you should use the latest development version: https://raw.githubusercontent.com/mbraak/jqTree/dev/tree.jquery.js

**Comment by tr0yka** [comment]
a dev log is displayed , but node does not open(((

**Comment by mbraak** [comment]
Does the node with id 1 really exist? You can check this by adding a `console.log`:

```js
var node = $tree.tree('getNodeById', 1);
console.log(node);
```
