### ISSUE TITLE
JQTree causes Unresponsive script when it has thousands of nodes.

### ISSUE THREAD

**Issue by krishnakowshik** [mbraak/jqTree#401]
Hi,
I am loading JSON data into the JQTree and it has thousands of nodes. JQTree is causing the Unresponsive script when I try to render the tree nodes. I have the JSON data on the Client. I am not sure when the script becomes unresponsive ( During the creation of the nodes or during the rendering of the nodes ). Is there a way to fix this? I am already making one ajax call to the server to get the JSON data. I do not want to make any more ajax calls. 

Please find attached the screenshot.
![unresponsive](https://cloud.githubusercontent.com/assets/1502857/10130860/959f1fac-65e9-11e5-8c15-eaef1496f16d.PNG)

**Comment by mbraak** [comment]
Hello,

Which browser are you using?

**Comment by krishnakowshik** [comment]
I am using Chrome and Firefox. However, this problem is seen on all browsers.

**Comment by mbraak** [comment]
The best solution for this is to load the data on demand. See [this example](https://mbraak.github.io/jqTree/examples/05_load_on_demand.html).

**Comment by krishnakowshik** [comment]
Loading the data on demand is a bit expensive for me, I have got the entire JSON. Is there anyway I can speedup the operation on the Client? Maybe something like rendering on demand?

**Comment by mbraak** [comment]
In the jqtree documentation i use the [jquery-mockjax](https://github.com/jakerella/jquery-mockjax) library to simulate loading from a server. That way i can use load-on-demand without a server.

Also see this [example](https://github.com/mbraak/jqTree/blob/master/static/examples/load_on_demand.js). The example data is in [this file](https://github.com/mbraak/jqTree/blob/master/static/example_data.js).

I hope this solution works for you.
