### ISSUE TITLE
Show selected path when full list is collapsed

### ISSUE THREAD

**Issue by BattleSlug** [mbraak/jqTree#403]
Hi,
I need to full path of selected nodes when full list is collapsed.
I suppose, I can collapse it on click like in the issue 61, but after that instead of showing just head node of level one, the lable should show something like "Node 1 -> Node 1.3" (Whit picture of an arrow instead of "->")
Thanks!

**Comment by mbraak** [comment]
Hello,

If i understand you correctly: you want to show a different text for a collapsed node?

Greetings

**Comment by BattleSlug** [comment]
Yes, for example, I have a tree starting with just 1 node Node1(like a root) which can be expanded to Node 2, 3.... each of which can be expanded to 2.1, 2.2.... I click 2.1, and the whole construction collapses, and now former Node1 has a label of full path to selected node, like Node 2 -> Node 2.3.
Thank you.

**Comment by mbraak** [comment]
I'm afraid jqtree does not support that. 

Perhaps you can do something with the [tree.close](https://mbraak.github.io/jqTree/#event-tree-close) event.

**Comment by BattleSlug** [comment]
Ok, thank you, I will look this way.
