### ISSUE TITLE
Expose jqTree classes for easy extension

### ISSUE THREAD

**Issue by vickychijwani** [mbraak/jqTree#404]
Hi, I'd like to request that jqTree should expose all the various internal classes, so power users can easily extend it by overriding methods if they wish to, without requesting use-case-specific features to be built into the core by you. The code is already very modular, so any motivated user should find it easy to extend in various ways.

To give you an example of why this is useful, let me explain my use-case:

There are 2 levels in my tree, each level only has nodes of a specific type, say the types are **A** and **B**, i.e., the hierarchy is **A** > **B**. Type **B** nodes can only be dragged into other **A** nodes, they *cannot* be moved before / after other **B** nodes. So far this is all simple to do with jqTree.

Here's what's not possible right now (at least as far as I understand):

1. Since **B** nodes can never be moved in any way except into other **A** nodes, the possible set of target positions is very small. So, I would like to customize the hit areas such that when a **B** node is dragged *anywhere over the subtree* of an **A** node (i.e., including the children), it is considered to be moving "inside" the **A** node. (I hope I explained that clearly enough?). This is to make clearer to the user what interactions are possible, and to maximize the hit area for ease-of-use.

2. Related to the above, I would also like to customize the `BorderDropHint` so it highlights the entire **A** node *with its subtree* when a **B** node is hovered over it.

From looking at the code, it seems both of these are possible by overriding `HitAreasGenerator#iterate()` and some methods in `BorderDropHint`.

#### How would we do this?

The `JqTreeWidget` constructor is already accessible using `$el.data('simple_widget_tree')`. All the other classes could be exposed as properties on that function itself, i.e.,

```javascript
JqTreeWidget.HitAreasGenerator = HitAreasGenerator;
JqTreeWidget.BorderDropHint = BorderDropHint;
// and so on...
```

Looks like a win-win situation to me -- people can write their own extensions and you'll have fewer issues to resolve yourself. If you believe this is a good idea, I can send in a pull request, please let me know. Thanks!

**Comment by mbraak** [comment]
Yes, I think that is a good idea. I'll add the classes to the JqTreeWidget constructor.

This is probably a good solution for people who are unafraid to dive into the code.

Greetings

**Comment by mbraak** [comment]
I added `BorderDropHint` and `HitAreasGenerator` to the `JqTreeWidget` constructor.

Please let me know if this works.

**Comment by vickychijwani** [comment]
If it's not too much trouble, could you expose all the other classes as well? (like `GhostDropHint` etc). I anticipate having to make other changes apart from the ones I described originally (which was meant as an example rather than a comprehensive list of what I needed). Some of those changes I don't even know how to make yet, so it's tough for me to give you a comprehensive list without going through a significant portion of the code.

**Comment by mbraak** [comment]
I will have a look at it.

**Comment by mbraak** [comment]
Ok. I added almost all classes now. It's in the dev branch.

**Comment by vickychijwani** [comment]
Looks good, thanks!

**Comment by vickychijwani** [comment]
This issue can be closed now unless you want to keep it open.
