### ISSUE TITLE
JSON data returned by the Controller is shown as raw data, instead of in jqTree

### ISSUE THREAD

**Issue by faujong** [mbraak/jqTree#405]
I would like to show the JSON data in the jqTree (
http://weblogs.asp.net/jdanforth/lazy-loading-treeview-sample-with-asp-net-mvc-and-jqtree)

I am using Visual Studio 2012.
My in HomeController.cs, I have a method "ActionResult Nodes" that return a JSON string.
I associated that method with a View "Nodes.cshtml" (in Visual Studio, when I right click on this method in HomeController.cs and select "Go to View", it does go to the View "Nodes.cshtml".

This is on _Layout.cshtml:
<li>@Html.ActionLink("Node", "Nodes", "Home")</li>

No matter how I change "Nodes.cshtml", when I click on the menu "Node", the raw JSON data is printed in the browser, ie
[{"label":"SubFolder1","id":"C:/MyFolder/SubFolder1","load_on_demand":true},{"label":"batch.txt","id":"C:/MyFolder/batch.txt","load_on_demand":false},
:
What causes this, and how can I fix it ?

HomeController.cs
public ActionResult Nodes(string node)
        {
            var list = new List<Node>();
                var items = Directory.GetFileSystemEntries("C:/MyFolder/");
                foreach (var item in items)
                {
                    list.Add(new Node(Path.GetFileName(item), item, Directory.Exists(item)));
                }
            return Json(list, JsonRequestBehavior.AllowGet);
        }

View "Nodes.cshtml" using jqTree (http://weblogs.asp.net/jdanforth/lazy-loading-treeview-sample-with-asp-net-mvc-and-jqtree)
@model MVCTreeView.Models.Node

@{
    ViewBag.Title = "Nodes";
}

<h2>Nodes</h2>
<div id="tree1" data-url="/home/nodes"></div>

@section scripts {
        @Styles.Render("~/Content/treecss")
        @Scripts.Render("~/bundles/tree")
    <script type="text/javascript">
        $(function () {
            $('#tree1').tree({
                closedIcon: $('<i class="fa fa-plus"></i>'),
                openedIcon: $('<i class="fa fa-minus"></i>'),
                dragAndDrop: false,
                selectable: false
            });

            // bind 'tree.click' event
            $('#tree1').bind(
                'tree.click',
                function (event) {
                    // The clicked node is 'event.node'
                    var node = event.node;
                    console.log('clicked ' + node.name );
                }
            );
        });
    </script>
}

**Comment by mbraak** [comment]
I'm afraid I don't know much about ASP.net.

Are you sure you are opening the right url in your browser? It seems you open the url for the json data. I would also expect a url that contains html.

Greetings

**Comment by faujong** [comment]
Thank you for your quick response !
I have resolved the problem, but how can I close all the sub-trees ?
Currently the tree opens the first level, like so:
- Folder1
+SubFolder1
-Folder2
+SubFolder2
:

I would like it to show like this:
+ Folder1
+Folder2
:

This is how I set the tree:
        $(function () {
            $('#tree1').tree({
                autoOpen: 0,
                closedIcon: '+',
                openedIcon: '-',
                dragAndDrop: false,
                selectable: false
            });

Thank you.

This is how I resolved the earlier problem:
In HomeController.cs I added the following:

        public ViewResult ViewNodes()
        {
            return View();
        }
And, I associated it with View "ViewNodes.cshtml".

@model IEnumerable<MVCTreeView.Models.Node>

@{
    ViewBag.Title = "ViewNodes";
}

<div id="tree1" data-url="/home/nodes"></div>

@section scripts {
        @Styles.Render("~/Content/treecss")
        @Scripts.Render("~/bundles/tree")
    <script type="text/javascript">
        $(function () {
            $('#tree1').tree({
                autoOpen: 0,
                closedIcon: '+',
                openedIcon: '-',
                dragAndDrop: false,
                selectable: false
            });

            // bind 'tree.click' event
            $('#tree1').bind(
                'tree.click',
                function (event) {
                    // The clicked node is 'event.node'
                    var node = event.node;
                    alert('clicked ' + node.name );
                }
            );
        });
    </script>
}

**Comment by mbraak** [comment]
That is strange. I see that you set `autoOpen` to `0`. That should only open the main levels.

I will try to reproduce this.

**Comment by faujong** [comment]
Thank you for your help.
Please let me know if you want me to send you my code.

**Comment by mbraak** [comment]
I think you should use `autoOpen: false`.

**Comment by faujong** [comment]
Yes, that works. Thank you so much !!

**Comment by mbraak** [comment]
great! closing the issue
