### ISSUE TITLE
tree.move documentation clarification

### ISSUE THREAD

**Issue by phena109** [mbraak/jqTree#406]
Hi there,

My request might seem redundant or trivial, but still want to raise it in case you haven't thought of this before.

When I use the 'tree.move' event, I thought the information I retrieved from event.children is going to be the new children after the move but turn out that I have to do:

```
        event.preventDefault();
        event.move_info.do_move();
```
before I can get the information. I know I have not read the document completely before I use the function but the behavior is quite different from what I use mostly, that, the `move` event usually contains the after effect of the event, where this event contains both, depend on if you call additional functions.

So my request is to clarify in the description of the event up front about the differences of this event to other similar event in other libraries. For example, instead of:

```
Triggered when the user moves a node.
```
we can say something like:
```
Triggered when the user moves a node. Depend on usage, information before the move and after the move are available.
```

thanks very much

**Comment by mbraak** [comment]
Thanks! I will add a note.
