### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ObiWan1** [mbraak/jqTree#407]
I just started using this widget and what I have noticed is that the treeview displays as expanded when it should not.  The icon on the top level nodes shows as closed (>) but underneath it I can still see the child nodes of the closed top level nodes.  This happens even using the sample data.  Why??

**Comment by ObiWan1** [comment]
Here is a picture of the issue if I didn't describe it well enough.

![treeview issue](https://cloud.githubusercontent.com/assets/5168330/11851061/4817efa2-a3f6-11e5-888a-a39f80af8178.png)

**Comment by ObiWan1** [comment]
I would love to be able to use this but cannot if it has this issue.

**Comment by mbraak** [comment]
It seems that there is something wrong with the css. Have you included [jqtree.css](https://github.com/mbraak/jqTree/blob/master/jqtree.css)?

Also see [this example code](https://mbraak.github.io/jqTree/#Tutorial).

Does this fix the problem?

**Comment by ObiWan1** [comment]
I do have jqtree,cs in my content folder and I have a link to use it in my shared layout file.

I followed the tutorial when I implemented the TreeView as explained on the main page: http://mbraak.github.io/jqTree/#jqtree

I do want to get this resolved but I have temporarily worked around the issue by adding the following script which goes through and opens and closes all the first level nodes:

    var rootNode = $('#DocumentTypeTree').tree('getTree');
    for (var i=0; i < rootNode.children.length; i++) {
      var child = rootNode.children[i];
      $('#DocumentTypeTree').tree('openNode', child, false)
      $('#DocumentTypeTree').tree('closeNode', child, false)
    }

I should mention that I am using this in an ASP.Net MVC 4 application that uses jquery mobile.  I am using jQuery 1.11.3 and jQuery Mobile 1.4.5.

I may be doing something wrong but if I am I don't see it.  I like this treeview control and all the functionality you have added to it.

**Comment by ObiWan1** [comment]
Update:  I added the jqtree.css on the page itself (instead of in the layout page) and now it works.  Normally I add all .css links on the shared layout page and that has worked for other .css files but for some reason it does not work for jqtree but now it is working fine.

**Comment by mbraak** [comment]
Great! closing the issue
