### ISSUE TITLE
Multiselect issue

### ISSUE THREAD

**Issue by atul-bajpai** [mbraak/jqTree#409]
Hi,
I have two queries as:
1) Does jqTree support the multiple selection of nodes, if yes, then how to turn it on/off.
    Because, when I tried to use jqTree in my application, on clicking the chile node, it is selecting all of them.
**code: 
var parent_node = $tree.tree('getNodeById', "p"),
   treeNodes = [];
treeNodes.push({
				    		label : item.portName,
				    		id : "p"+item.portID,
				    		children : childNode   // this the sub child nodes
				    	});
 $tree.tree('loadData', treeNodes, parent_node);**

![untitled](https://cloud.githubusercontent.com/assets/2909552/12844595/556ac21c-cc26-11e5-80d5-fac61a782d33.png)

2) Second question: I want to select all the parents node except the root node, whenever I click any child node.

**Comment by mbraak** [comment]
Hello,

JqTree does uses single-select by default. You can add multiple selection by adding some code. Please see [this example](https://mbraak.github.io/jqTree/examples/08_multiple_select.html).

About the second question: I think it is possible to select the parent nodes. I will think about a solution.

**Comment by atul-bajpai** [comment]
Hi,
For the first question, I also want single select, but in my case it is behaving like multi select and i haven't wrote any code for the multiple selection like your example.

**Comment by mbraak** [comment]
It is possible that your data is not correct. Perhaps the child nodes do not have a unique id.

**Comment by atul-bajpai** [comment]
Yes, you right, thanks.

Please help me with the second question.

**Comment by mbraak** [comment]
The following code selects a node and its parents:

```js
$tree.bind(
    'tree.click',
    function(e) {
        // prevent default selection
        e.preventDefault();

        // deselect all nodes
        var nodes = $tree.tree('getSelectedNodes');
        nodes.forEach(function(n) {
            $tree.tree('removeFromSelection', n);
        });

        // select node and parents
        var node = e.node;

        while (node.parent) {
            $tree.tree('addToSelection', node);

            node = node.parent;
        }

    }
);
```

**Comment by atul-bajpai** [comment]
Wow, that's I want thanks alot man.

One more thing, is there any way that we can assign different css class to each LI, I mean something like this,
{
    label: 'Ports',
    id: "p",
    cssClass : 'ClassA'
},
{
    label: 'Statistics',
    id : "s",
    cssClass : 'ClassB'
 }

So that we can use these class in css to apply some specific styles.

**Comment by mbraak** [comment]
You can use the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option.

**Comment by atul-bajpai** [comment]
Thanks @mbraak, I am closing this issue now.
