### ISSUE TITLE
How to trigger event handler after selecting the node programatically

### ISSUE THREAD

**Issue by atul-bajpai** [mbraak/jqTree#410]
Hi I am selecting a node using  **$tree.tree('selectNode', node);**, which is working fine, but how to trigger event handlers attached to that node.

Second, I have to call a method once the tree is fully rendered on the page, I have tried both 

**tree.init** and **tree.refresh** but none of them are getting called.

**Comment by atul-bajpai** [comment]
Never mind. This is fixed. However, one more issue is that, how to set the custom header in the ajax request, when using dataUrl parameter. I did this
dataUrl : function(node) {
                    var obj = {
                        url : "URL",
                        method : "GET",
headers: {'Authorization': base64encodeCredentials},
                        beforeSend : false,
                        complete : false
                    }
                    return TrafficGenMakeServerCall.makeConfigObj(obj);
                },

**Comment by mbraak** [comment]
I think the extend option is a good idea.

Note that you can also use [ajaxSetup](http://api.jquery.com/jQuery.ajaxSetup/) to set ajax options.

**Comment by mbraak** [comment]
I added #412 for the `dataUrl` options

**Comment by atul-bajpai** [comment]
Thanks

**Comment by mbraak** [comment]
Issue #412 is now fixed.
