### ISSUE TITLE
Add ability to load on demand one level further down the tree.

### ISSUE THREAD

**Issue by stevebissett** [mbraak/jqTree#411]
I have recently taken a look at jqTree and it is great that on demand loading is supported.

I am more of a backend developer, but would like to see how possible it would be to modify the on demand loading to load one level down for a smoother user experience.

For example. If I have these levels:

    Alcoholic Beverages
    - Wine
    -- Red Wine
    --- Merlot
    ---- Robertson Merlot 4$

I would like to load up to two levels at initial load, and then on each click lower, load the N + 1th level and not the Nth level.

For example:
_Event -> Page Loads_
Alcoholic Beverages Loads, and it's children to one level. ie. Wine.
_Event -> User Clicks on Alcoholic Beverages_
Expands Alcoholic Beverages and Wine is Already Loaded, so is displayed immediately.
Wine's First level children are loaded from server so that if the user clicks on Wine, then the level below it will load immediately.

The aim is to more closely approximate loading all of the data points at the start, and then it's instant to look through them. I am using a large number of levels with 250000 data points so it's not a good idea to load them all in advance.

**Comment by mbraak** [comment]
You can certainly load the first 2 two levels initially. Your initial data would like this:

```json
[
    {
        "label": "Alcoholic Beverages",
        "id": 1,
        "children": [
            {
                "label": "Wine",
                "id": 2,
                "load_on_demand": true
            }
        ]
    }
]
```

I don't know if it is possible to load multiple children levels on demand. I will look into it.

**Comment by stevebissett** [comment]
Thank you. Loading two levels initially would be a good start.

**Comment by mbraak** [comment]
I checked if it is possible to load multiple levels on demand.

This is indeed possible; if your server returns multiple levels then jqTree will load the data.

**Comment by stevebissett** [comment]
I'll have a look into this and get back to you.
