### ISSUE TITLE
How to trigger tree.click event programatically

### ISSUE THREAD

**Issue by atul-bajpai** [mbraak/jqTree#413]
want to know is there a way to  trigger tree.click event through code.

**Comment by mbraak** [comment]
I don't know how you can do that. You can call the [selectNode](https://mbraak.github.io/jqTree/#functions-selectnode) function to select a node, but that would not trigger the `tree.click` event.

**Comment by atul-bajpai** [comment]
Thanks,
just curious about what if I do this,

JqTreeWidget.prototype.nodeClicked = function(event) {
    return this._click(event.click_event);
  };

and then call it like 
$tree.tree('nodeClicked', event);

will it create any bug...

**Comment by mbraak** [comment]
I think that will work. The `event` variable should of course be a proper click event.

**Comment by atul-bajpai** [comment]
Yeah, that I am handling it in my app.
Thanks alot...

**Comment by atul-bajpai** [comment]
is the jqtree is handling the memory leaks, in scenarios where tree is refreshed quite frequently..

**Comment by mbraak** [comment]
JqTree does not handle memory leaks. If you know of any memory leaks, please let me know.

**Comment by atul-bajpai** [comment]
One small query, does **updateNode ** method renders the tree again or just update the node properties.

**Comment by mbraak** [comment]
It renders the tree again. Note that the rendering is optimized, so that it will not render the whole tree.

**Comment by atul-bajpai** [comment]
thanks @mbraak 
is there a way to update the node property without reloading the tree...

**Comment by mbraak** [comment]
If you have a Node object, you can set its name property:

```
var node = $('#tree1').tree('getNodeById', 123);

node.name = 'new name';
```

**Comment by atul-bajpai** [comment]
text node used for open and close folder icon is creating memory leak, though not a very big issue but thought to inform you :)
