### ISSUE TITLE
How to enable horizontal scrolling?

### ISSUE THREAD

**Issue by dsavenko** [mbraak/jqTree#416]
Hi,

Suppose, I have the following HTML:
```html
<style>
.sidebar {
    width: 400px;
    height: 100%;
    overflow: scroll;
}
</style>
 
   <div class='sidebar'>
        <div id='tree-wrapper'>
            <div id='tree'></div>
        </div>
    </div>
```

This gives me vertical scrolling, but not horizontal. What's the best way to enable it? So far, I only found one way: set the `width` of the `tree-wrapper` div to some big value, like `10000px`. In this case, horizontal scrolling appears, but the scrollbar is really small.

**Comment by mbraak** [comment]
Hello,

I tried the following:

```css
    width: 400px;
    overflow-x: scroll;
```

It seems to work.

**Comment by dsavenko** [comment]
Yes, thanks, it worked for me, after I added `white-space: nowrap` to the tree div. 

There was another problem. If a selected node has a long name (which goes beyond the maximum width), only the visible part is highlighted. If I scroll right, the part which was hidden is not highlighted. I fixed it like this:

```css
div.jqtree-element {
    display: inline-block;
}
```

Not sure if it's a good way.

**Comment by mbraak** [comment]
I tried it too, `inline-block` seems to work. I don't understand why.
