### ISSUE TITLE
jqTree.tree("reload")

### ISSUE THREAD

**Issue by timograf** [mbraak/jqTree#417]
Hi I am using your framework and created a tree from a json into a div. This works perfectly, the tree is being displayed and all. Now im trying to make a refresh button which loads another json structure into the tree. I cant figure out how to make it work. I have tried everything.

Could you please provide me a short example of how you would load a new data into the same tree and reload it.

Thanks in advance!

**Comment by mbraak** [comment]
Hello,

In this case you can use the [loadData](https://mbraak.github.io/jqTree/#functions-loaddata) function.

This example loads new data into the existing tree `tree1`.

```js
var data = [
    { label: 'new node' },
    { label: 'another new node' }
];
$('#tree1').tree('loadData', data);
```

Please let me know if this works.

**Comment by timograf** [comment]
Yes this worked fine! Thanks for your quick help! Maybe you could describe this under the reload section in the documentation.

Or maybe it was just me and its clear to everyone else =)

**Comment by mbraak** [comment]
Thanks! I'll have a look at the documentation

**Comment by saralabafi** [comment]
Hi, 
How can I change some tree option like autoOpen in LoadData function?
I try everything, I do not want to destroy old tree and build new one , just want to load new data (in json format) with new tree option.

**Comment by mbraak** [comment]
Using `autoOpen` with `loadData` is not supported at the moment. Is not possible to use the [destroy](https://mbraak.github.io/jqTree/#functions-destroy) function?

**Comment by saralabafi** [comment]
> Using `autoOpen` with `loadData` is not supported at the moment. Is not possible to use the [destroy](https://mbraak.github.io/jqTree/#functions-destroy) function?

Yes, it is fine with destroy and then build new one, but the tree must be built again in this way.
Thanks
