### ISSUE TITLE
get Main Parent Node

### ISSUE THREAD

**Issue by urprasu** [mbraak/jqTree#418]
Hi , 

I want to find the parent node recursively.

For example node id = 10 have parents node id 7 and node id 4.

SO i want to find the main parent node.

If give node id is 10 then main parent node id 4. (I want result like this)

Can you help us above issue.

var data = [{
	"id": "1",
	"name": "Root node",
	"children": [{
		"id": "2",
		"name": "Child node 1"
	}, {
		"id": "3",
		"name": "Child node 2"
	}, {
		"id": "4",
		"name": "Child node 3",
        "children": [{
            "id": "7",
            "name": "Child child 1",
            "children": [{
                "id": "9",
                "name": "Child child child 1"
            }, {
                "id": "10",
                "name": "Child child child 2"
            }]
        }, {
            "id": "8",
            "name": "Child child 2"
        }]
	}, {
		"id": "5",
		"name": "Child node 4"
	}, {
		"id": "6",
		"name": "Child node 5"
	}]
}];

**Comment by urprasu** [comment]
i want to get all the parent nodes of a child node

**Comment by atul-bajpai** [comment]
check this issue #409

**Comment by mbraak** [comment]
Yes. Issue #409 contains a useful example for finding the parent node.

Another example:

```js
function getMainParent(node) {
    var result = node;

    while (result.parent && result.parent.parent) {
        result = result.parent;
    }

    return result;
}

var node = $('#tree1').tree('getNodeById', 10);

var main_parent = getMainParent(node);
console.log(main_parent);
```
