### ISSUE TITLE
Id Generation

### ISSUE THREAD

**Issue by zkendall** [mbraak/jqTree#421]
Is there a recommended pattern for generating and keeping track of the node IDs. Would you just keep a counter outside the tree or?

**Comment by mbraak** [comment]
Yes. A counter is probably the easiest to generate ids.

Note that in most applications the tree data comes from a database. In that case the database records already have a unique id.

**Comment by zkendall** [comment]
Thanks; I'm just learning javascript.

In a primitive test and looking at the code, it seems that ID's aren't restricted to numbers. I don't know if that would be obvious in the JS ecosystem, but that could be made clearer in documentation.

For reference, I'm using the tree to represent a file system. So if you don't see any way this could go wrong, I might use the file path as ID.

**Comment by mbraak** [comment]
Yes. That's a good point, ids can be strings.

I added this to the docs. (It's in the `dev` branch, it's not visible on the site yet).
