### ISSUE TITLE
Position "inside" instead of "before"

### ISSUE THREAD

**Issue by mbyta** [mbraak/jqTree#422]
node1
&nbsp;&nbsp;&nbsp;&nbsp;node2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;node3
&nbsp;&nbsp;&nbsp;&nbsp;node4

I want to move node4 just before node3.
So I dragged it before node3

But jqtree gives me this result

target node = node2
position = "inside"

But what I want is
target node = node3
position = "before"

Does anyone know how to fix that?

Thanks

**Comment by mbraak** [comment]
Are you talking about the [tree.move](https://mbraak.github.io/jqTree/#event-tree-move) event?

**Comment by mbyta** [comment]
Yes, I'm talking about tree.move.
What I want is to move the node to the first position inside a subtree, but instead it just append it after the last node in that subtree, because the position is "inside" instead of "before".

**Comment by mbyta** [comment]
Yes I'm talking about tree.move.

What I want is to move a node to the 1st position inside a subtree.
I'm saving that position in the backend.
So the parameters I'm expecting to receive is

target node = node3
position = "before"

but instead, I'm receiving

target node = node2
position = "inside"

and so the result is not correct when I'm refreshing the page because it just appends it after node3

**Comment by mbraak** [comment]
You can fix this by changing the `position` and `target_node` in the `tree.move` event.

Example code that changes 'inside' to 'before' first child:

```js
$tree.on('tree.move', function(e) {
    var position = e.move_info.position;
    var target_node = e.move_info.target_node;

    if (position == 'inside' && target_node.hasChildren() && target_node.children.length >= 1) {
        // change 'inside' node to 'before' first child node
        position = 'before';
        target_node = target_node.children[0];
    }

    // Use 'position' and 'target_node' in the backend
    console.log(position, target_node);
});
```

**Comment by mbyta** [comment]
Got it!

Thanks for the tip
