### ISSUE TITLE
"label" vs "name"

### ISSUE THREAD

**Issue by zkendall** [mbraak/jqTree#423]
Why are these two different terms used?

I'd expect to be able to:
```
$('#tree1').tree({ data: data });
var json = $('#tree1').tree("toJson");
$('#tree2').tree(json);
```
Shouldn't input model match output model from the library?

**Comment by mbraak** [comment]
Thank you for mentioning  this. It's indeed a bit confusing.

You can actually use `name` instead of `label` in the data. I updated the docs and the examples to use 'name'. (this is not visible on the site yet).
