### ISSUE TITLE
Add multiple node with childs

### ISSUE THREAD

**Issue by boss2509** [mbraak/jqTree#425]
Hi,
I want to add node with addNodeAfter but Node with children. The first node is ok, but cant see the childrens. However the data is the same format

**Comment by mbraak** [comment]
You can only add single nodes with the 'appendNode' function.

You can use the [loadData](https://mbraak.github.io/jqTree/#functions-loaddata) to add multiple nodes, or even a whole subtree:

```js
var new_data = [
    {
        name: 'node1',
        children: [
            { name: 'child1' },
            { name: 'child2' }
        ]
    },
    {
        name: 'node2',
        children: [
            { name: 'child3' }
        ]
    }
];

var existing_node = $('#tree1').tree('getNodeById', 100);

$('#tree1').tree('loadData', data, node);
```

**Comment by boss2509** [comment]
It doesnt work. I want to duplicate a node and his child if it have

**Comment by mbraak** [comment]
Can you show the code that does not work?

**Comment by boss2509** [comment]
"duplicate": function (node) { 

    var url = "{{url('mission/replicate_niveau_piece')}}";
    $.post(url,
    {
      id : node.id,
      is_piece : node.is_piece
    },
      function(data,status){
        $('#tree1').tree('loadData', data, node);
      });

  },

but it must not append to the node like a child, but append like a Sibling

**Comment by mbraak** [comment]
I see that you are posting something to the server. Are you also doing the duplicating on the server?

**Comment by boss2509** [comment]
Yes, then I get back the tree with new Ids from the server, that I want to append

**Comment by mbraak** [comment]
Ah, I see. If you have the whole tree on the server, you could also consider to reload the whole tree.

Appending a subtree as a sibling is not supported at this moment. There are plans to implement this, but it will take some time.

**Comment by boss2509** [comment]
yes I know. But i search to avoid doing that. Just add like a sibling

**Comment by mbraak** [comment]
You can now append a subtree using `appendNode`. Also see issue #426 .

Note that this is in the `dev` branch, noy yet in the stable branch.

**Comment by boss2509** [comment]
Thank  you
