### ISSUE TITLE
Update multiple node

### ISSUE THREAD

**Issue by boss2509** [mbraak/jqTree#427]
Can we update multiple node on one time  ?

**Comment by mbraak** [comment]
That is not supported at this moment.

**Comment by boss2509** [comment]
Will it be soon ?

**Comment by mbraak** [comment]
You mean updating the children using `updateNode`, right?

I have to think about that. It seems to be more difficult than `appendNode`.

**Comment by boss2509** [comment]
Yes with updateNode. Update information inside the node with children if it has

**Comment by boss2509** [comment]
Is it possible to openNode until the node we want ? Like children of children

**Comment by mbraak** [comment]
If you use `openNode` to open a node, then its parent nodes will also be opened. I hope this answers your question.

**Comment by boss2509** [comment]
Yes its that but it doesnt open the parent nodes thats why

**Comment by boss2509** [comment]
It's not really openNode, it's like after reload the tree, I want that its open until the node I want

**Comment by mbraak** [comment]
You want to open a specific node after reloading the tree?

**Comment by boss2509** [comment]
Yes

**Comment by boss2509** [comment]
Open the tree until a specific node

**Comment by mbraak** [comment]
That sounds like an interesting problem. I do have some questions:

* How are you reloading the tree? Are you using `loadDataFromUrl`?
* Are you reloading the whole tree, or only a part?
* Do you want to open a single or multiple nodes?
* Do you know the id of the node that you want to open?

**Comment by mbraak** [comment]
It is now possible to update children using `updateNode`:

```js
$tree.tree(
    'updateNode',
    node,
    {
        name: 'new name',
        id: 1,
        children: [
            { name: 'child1', id: 2 }
        ]
    }
);
```

Note that this removes the existing children.

**Comment by boss2509** [comment]
Thank you. 
Yes i was reloading the tree with a Url. 
Just opening at least a signe node. and yes i know the Id

**Comment by mbraak** [comment]
The [loadDataFromUrl](https://mbraak.github.io/jqTree/#functions-loaddatafromurl) function has an `on_finished` parameter.

So, if you want to reload the tree data, and then open a specific node:

```js
$tree.tree(
  'loadDataFromUrl',
  '/tree',
  null,
  function() {
    // data is loaded
    // open node 10
    var node = $tree.tree('getNodeById', 10);
    $tree.openNode(node);
  }
);
```

**Comment by boss2509** [comment]
I tried this. It doesnt work when the node doesnt have child

**Comment by mbraak** [comment]
You can open the parent in that case:

```js
$tree.tree(
  'loadDataFromUrl',
  '/tree',
  null,
  function() {
    // data is loaded
    // open node 10
    var node = $tree.tree('getNodeById', 10);
    if (node.hasChildren()) {
      // open folder
      $tree.tree('openNode', node);
    }
    else {
      // open parent of node
      $tree.tree('openNode', node.parent);
    }
  }
);
```

**Comment by boss2509** [comment]
I will try otherwise i will use the new updateNode

**Comment by mbraak** [comment]
Does this work? Closing the issue for now

**Comment by boss2509** [comment]
It works . Thanks.
