### ISSUE TITLE
tree is not consistent with opening nodes with openNode call

### ISSUE THREAD

**Issue by aherreraGH** [mbraak/jqTree#429]
I am using Backbone, and have the following code in place: 

`               $tree = _this.$('#tree');
                $tree.tree('reload', function(){
                    _this.render();
                    if (group) {
                        /******************************************
                         * Expand the tree if a group is included *
                         ******************************************/
                        $tree.on('tree.init', function() {

                            if ($tree.tree) {
                                var nodeToOpen = $tree.tree('getNodeById', group.groupId);
                                if (nodeToOpen && nodeToOpen.parent) {
                                    $tree.tree('openNode', nodeToOpen.parent);
                                }
                            }
                        });
                    }
                });
`

The tree is loaded with data from the server. It seems that the tree.init is not an indicator telling me that the tree is completely built. Any suggestions? Or can you add a boolean that can tell me when the entire thing is ready? Thanks in advance.

See image with console error...
![jqtreeissue](https://cloud.githubusercontent.com/assets/10350197/15724662/b882670e-280d-11e6-9bfc-2632e2913206.png)

**Comment by mbraak** [comment]
It seems that the tree is not intialized. You have to call `$tree.tree({})` first.

See https://mbraak.github.io/jqTree/#options-data and https://mbraak.github.io/jqTree/#options-data-url for examples.

**Comment by aherreraGH** [comment]
Thank you for the prompt response. And sorry for my delayed response on this. 
I ended up refactoring the code that uses your jqTree and got it working as expected. Your tip gave me enough to figure out what we did wrong.

**Comment by mbraak** [comment]
great! closing the issue
