### ISSUE TITLE
Is there any way to drop something external into a tree?

### ISSUE THREAD

**Issue by knipknap** [mbraak/jqTree#432]
I am trying to implement a file browser-like tree, where I need to be able to drop a file into a folder. I found no drop event in the docs. Is there any way to do this?

**Comment by mbraak** [comment]
You can move a node *inside* the tree using drag-and-drop.
But it is not possible to drag something from *outside* the tree. It is also not possible to drag-and-drop between two trees, for example.

**Comment by knipknap** [comment]
Ouch, is there any hack I can use? I have spent way too long to implement my app around jqTree to switch now. E.g., is there a way to get the node by HTML element?

**Comment by mbraak** [comment]
You can certainly do that. This is the fragment from the jqTree code that finds a tree node for an html element:

```coffeescript
_getNode: ($element) ->
    $li = $element.closest('li.jqtree_common')
    if $li.length == 0
        return null
    else
        return $li.data('node')
```

Note that this is coffeescript. Also note that `$element` is a jquery html element.

I'm planning to add a public function to jqTree that does the same thing.

**Comment by knipknap** [comment]
Ah, thanks! I had checked for data, but didn't find any due to another problem. For the record, this is what I am using now:

    td.draggable({helper: "clone", cursorAt: {'top': 3, 'left': 3}});

    $("#tree_div").droppable({
        drop: function(event, ui) {
            var center_x = ui.position.left;
            var center_y = ui.position.top;
            var elem = document.elementFromPoint(center_x, center_y);
            var li = $(elem).closest('li');
            var node = li.data('node');
            console.log(event, center_x, center_y, elem, li, node, ui);
        }
    });

Since nodes are dynamically loaded and I found no way to hook into the node add process, I could not mark all elements droppable. Hence the use of elementFromPoint()...
