### ISSUE TITLE
jqTree - is it possible to drop an object from ouside the tree

### ISSUE THREAD

**Issue by sherinjose** [mbraak/jqTree#436]
In jqTree is it possible to drop an object from ouside the tree. Means I want to drag a div that is not part of the tree and drop it an item inside the tree. 

Then should do the rest by catching which element is dropped.

Is it support that functionality ?

**Comment by mbraak** [comment]
At this moment that is not supported. The feature might be added in the future.

Please also see issue #432  In the comments someone mentions that he has implemented this using [jqueryui droppable](https://jqueryui.com/droppable/).

**Comment by sherinjose** [comment]
Okay. Thanks @mbraak . Anyway this is an awesome plugin. Much helpful for me. Will try the solution you suggested.

:+1:
