### ISSUE TITLE
XSS issue in jqTree drag and drop 

### ISSUE THREAD

**Issue by Monisha-M** [mbraak/jqTree#437]
Steps to reproduce xss:

1. Have a node label with any xss vector, say for eg., '&lt;img src=x onerror=alert()&gt;child1'
2. Drag and drop the node

Demo URL : http://fiddle.jshell.net/V5dLM/4/

**Comment by mbraak** [comment]
Thanks. I will have a look at it.

**Comment by Monisha-M** [comment]
Any update?

**Comment by mbraak** [comment]
I have a possible fix.

**Comment by Monisha-M** [comment]
Thats great..!!! May I know the fix?

**Comment by mbraak** [comment]
The fix is now in the `dev` branch, in this commit: https://github.com/mbraak/jqTree/commit/3a19f0c177c7ab9d25fff62d1b28c94f1574c3d0

**Comment by Monisha-M** [comment]
Yeah, the issue got fixed. 
Any ETA to get this work in main?

**Comment by mbraak** [comment]
I have not planned a new release yet. Perhaps you can use the `dev` branch.

**Comment by mbraak** [comment]
Closing the issue

**Comment by irinakk** [comment]
hmm... shouldn't this be related to the config `autoEscape` ? cuz now it behaves differently on .jqtree_common and .jqtree-dragging ...

**Comment by mbraak** [comment]
Yes, that's true. I will look into it.

**Comment by mbraak** [comment]
This is now fixed in the dev branch.

**Comment by irinakk** [comment]
ok, thx.
