### ISSUE TITLE
Problems with child nodes

### ISSUE THREAD

**Issue by OlegVach** [mbraak/jqTree#438]
Hello. I have one question for your.
I create my own component with you jqTree. When i adding Node from Parent its work good, but when i try add from child Node, they are creating in Child and Add to Parent Node to.

function AddChild(node){
  var parent_node = $tree.tree('getNodeById', node.id);
   if(parent_node){
    var id = $('input[id=child-id]').val();
      $tree.tree(
        'appendNode',
        {
          id: id,
          name: 'new_node'
        },
        parent_node
     );  
  }  
  $('#modal-add-child-node').modal('hide');
}

I call my function here using 'tree.click'

function(event) {
      var node = event.node;
      if ($tree.tree('isNodeSelected', node)) {
        event.preventDefault();
      }else{
        $("#remove-element-"+ node.id).on('click', function(){
          RemoveNode(node);
        });
        $('#new-child-button').on('click', function(){
           AddChild(node);
        });
      }
Thank you!

**Comment by mbraak** [comment]
Hello,

I see that you are binding the `click` event to some buttons in the `tree.click` event. I think that is a little confusing. It is also possible that this causes the click handler to be called multiple times.

Cheers

**Comment by OlegVach** [comment]
So, I must use click in function?

**Comment by mbraak** [comment]
That depends. Where are the **remove** and **add child** buttons? Do you have buttons for each node?

**Comment by OlegVach** [comment]
Yes it is. I have bootstrap dropdown menu. When i click for add child opening Modal window, and when i write Node name and ID i call Modal button #new-child-button and this call must add new Node

**Comment by OlegVach** [comment]
Its work fine with parent node, but doesn`t work with child, child Node Create me two or more Nodes, when i read log, i seen that my function get two ID, but i have one variable

**Comment by mbraak** [comment]
I don't know what's going on, but I do think that you are binding the `click` event multiple times. So, if you click on a button, multiple functions are called.

**Comment by OlegVach** [comment]
ok, i try solved this problem. Thank you.
