### ISSUE TITLE
$(...).tree is not a function

### ISSUE THREAD

**Issue by sajanojha** [mbraak/jqTree#439]
Hi,
I am facing this issue. I believe I haven't included multiple jquery versions. I followed all the steps as suggested but I am still getting this error. I can't understand why.
`script(src='bower_components/jQuery/dist/jQuery.min.js')`
`script(type='/bower_components/jqTree/lib/tree.jquery.js')`
I am implementing it on a node. Also, all the methods are wrapped inside $(function()

**Comment by mbraak** [comment]
Hello,

I see that the first includes jquery using `src` and the second line includes jqtree using `type`. Also, the url for jqtree starts with a slash, and the the url for jquery does not.
Are you sure this is correct?

**Comment by sajanojha** [comment]
Hi,
Thank you. So stupid of me. The problem is now resolved and it is working awesomely!!!
