### ISSUE TITLE
Child and parent tree can i move to root ?

### ISSUE THREAD

**Issue by joshuawatson** [mbraak/jqTree#441]
How can i move child node to parent root node of top and bottom ?

**ex:-** 
should be able to reorder the node in any hierarchy I want. Like I can make a sub-child-node to be a parent node and root of top and down and vice versa.

but doc said cannot move to root.
http://mbraak.github.io/jqTree/#options-oncanmove

Thanks,

**Comment by mbraak** [comment]
Hello Joshua,

What do you mean exactly by moving? Do you mean:
* moving using drag-and-drop, or
* moving using a function, e.g. [moveNode](http://mbraak.github.io/jqTree/#functions-movenode).

Greetings

**Comment by joshuawatson** [comment]
Hi Mbraak,

  I want to drag and drop sub-tree to root and root will be sub-tree

Thanks

**Comment by mbraak** [comment]
I see what you mean.

It cannot be done in one step. However, you can do this in two steps:
* move a node (or a sub-tree) above the root node
* then, move the root under the node

Cheers

**Comment by joshuawatson** [comment]
![move_root](https://cloud.githubusercontent.com/assets/1235449/17319321/8de7c782-58aa-11e6-9dc9-96eeacf58587.png)

Here i attached screen-short, i like to move last child task(test the app), move to parent(tester 123) and child task will be the parent task called(test the app).

Thanks

**Comment by mbraak** [comment]
You can do this in 2 steps:

* Move **test the app** above **tester 123**
   * It is now on the same level as **tester 123**
* Move **tester 123** under **test the app**

**test the app** is now the root; **test 123** is a child of **test the app**

**Comment by joshuawatson** [comment]
Is there any possibility to move child to root by one step ?

**Comment by mbraak** [comment]
I'm afraid that's not possible.

**Comment by joshuawatson** [comment]
Im not able to move **test the app** above **tester 123** , i can move below the tester 123 please verified it is not have directly move **test the app** above **tester 123**

**Comment by joshuawatson** [comment]
Hi mbraak,

Now it's working by two way.
I just added padding of my tree css.

#tree {
    border: 1px solid white;
    padding: 2em;
}


Thanks

**Comment by mbraak** [comment]
I'm glad to hear that. Closing the issue.
