### ISSUE TITLE
jqTree - tree.init is not working

### ISSUE THREAD

**Issue by sherinjose** [mbraak/jqTree#442]
I need to fire the `init` event for processing some functionalities. But the `tree.init` wont work for me. Don't know why ? Below is my code. Please help.   

> $(identifier).tree({
> 		data: data,
> 		autoOpen: true,
> 		dragAndDrop: false,
> 	}).bind(
> 		'tree.init',
> 		function() {
> 			// initializing code
> 			alert(11);
> 		}
> 	);

**Comment by mbraak** [comment]
If you initialize the tree with the `data` option, then the tree is immediately initialized. This means that you don't have to use the `tree.init` event.

You can do this:

```js
$(identifier).tree({
  data: data,
  autoOpen: true,
  dragAndDrop: false
});

// init
alert(11);
```

**Comment by sherinjose** [comment]
Okay. Is there a chance to call the `alert(11);`  immediately before the initialization completed ?

**Comment by mbraak** [comment]
No, after the `.tree` function is called the initialization is complete.

**Comment by sherinjose** [comment]
okay. thank you :)
