### ISSUE TITLE
Bug with media css hack

### ISSUE THREAD

**Issue by everio** [mbraak/jqTree#443]
Hello,

When I compile assets with gulp (the latest version), I have this error : 
`Potentially unhandled rejection [2] media definitions require block statements after any features in file /src/bower_components/jqtree/jqtree.scss line no. 192`

Apparently because of this : 
`@media \0screen\,screen\9`

I have found no solution for this problem. 

Thanks,

**Comment by mbraak** [comment]
Are you using sass or less?

Jqtree uses sass to compile the `jqree.scss` file. There is also `jqtree.css` in the source. Perhaps you can use that file.

**Comment by everio** [comment]
Yes, the bug append when I compile assets with the gulp-sass function.
So problem solved when I add jqtree.css after sass compilation.

Thanks for your answer.
