### ISSUE TITLE
Load on demand

### ISSUE THREAD

**Issue by adilakshmis** [mbraak/jqTree#444]
When am trying to construct the first level of Jqtree using below code

 browseall: function () {
        
        cordova.plugin.pDialog.init({
            theme: 'HOLO_DARK',
            progressStyle: 'SPINNER',
            cancelable: true,
            title: 'Please Wait...',
            message: 'Loading...'
        });
        console.log("browse");
        console.log("url in browse ::::" + url);
        var assetUrl = url + "browse";
        console.log("url::" + assetUrl);
        $.ajax({
            type: "GET",
            url: assetUrl,
            crossDomain: true,
            cache: false,
            success: browseDemand.browseSuccess,
            error: browseDemand.browseError
        });
    },
    browseSuccess: function (result) {
        
        console.log("result:::" + result);
        var res = JSON.stringify(result);
        console.log("res::::" + res);
        arrayList = [];
        $.each(result, function (i, field) {
            var array = [];
            console.log(field.deviceName);
            //console.log(JSON.stringify(field.listAsset));
            var asset = field.listOfModelNames;
            //console.log("asset:::"+asset);
            $.each(asset, function (i, value) {
                var children = new function () {
                    this.label = value;
                    this.id = i;
                    this.load_on_demand = true;
                };
                array.push(children);
            });
            var Folder = new function () {
                this.label = field.deviceName;
                this.id = i;
                this.children = array;
            };
            arrayList.push(Folder);
            cordova.plugin.pDialog.dismiss();
            // console.log("arrayList:::"+arrayList);
        });
  console.log("calling the tree2 -------------------------asset url is "+ url);
      
          var $tree = $('#tree2');

        $tree.tree({        
            data: arrayList,           
            dataUrl: url,
            dragAndDrop: true,
            // autoOpen: true,
            //dragAndDrop: true,
            closedIcon: $('<i class="fa fa-folder yellow"></i>'),
            openedIcon: $('<i class="fa fa-folder-open yellow"></i>')

        });

The first level of folders am successfully displying. 
but when I clicke on child element I need to call the service service url is like http://142.56.156:9080/rootcpntext/parentFoldelName/childFolderName

In above code dataUrl is = http://142.56.156:9080/rootcpntext/
But am failed to pass the clicked node name and its parent name.
Can any one help me and It is very urget.
I am poor in javascript

**Comment by mbraak** [comment]
Hello,

If I understand correctly you want to customize the url for loading nodes on demand. You can do that using the `dataUrl`. Also see [the documentation](https://mbraak.github.io/jqTree/#options-data-url).

The `dataUrl` can be a function. This function receives a node parameter, which can be null (for the whole tree) or a node (if a node must be loaded on demand).

```js
$('#tree1').tree({
   dataUrl: function(node) {
       if (!node) {
          // root node
          return { url: 'http://142.56.156:9080/rootcpntext/' };
       }
       else {
         // load a specific node

         // you can customize the url here; below is an example, the correct url is probably different
         return {
             url: 'http://142.56.156:9080/rootcpntext/' + node.name + '/'
         };
   }
});
```

I hope this answer help.

**Comment by adilakshmis** [comment]
Thank you very much @mbraak , I tried with your code it is working for me and  I read the documentation that you shared link I also added the dataFilter for customizing the response data to support next child elements to support the load-on-deamd

**Comment by mbraak** [comment]
I'm glad to hear that it works. Closing the issue.
