### ISSUE TITLE
Selectable area?

### ISSUE THREAD

**Issue by mkrsII** [mbraak/jqTree#445]
Hello, thanks for creating this great tree! couple issues I'm having:

- How do you get drag and drop scrolling to work in a page with dynamic nodes? Doesn't seem to work very well even in its own container with overflow-x-y set and height set. Doesn't detect dynamic nodes.

- Is there an option to set the selectable area class in the tree? Anywhere in the node I click it is selected, it creates some focus issues with a rich text editor I have in the tree

Other than that, where can I donate to you?

**Comment by mbraak** [comment]
Hello,

Could you tell me more about the dynamic nodes issue? Are you referring to loading on demand (like [this example](https://mbraak.github.io/jqTree/examples/05_load_on_demand/))?

You can customize the selection by handling the `tree.click` event. For example:

```js
$tree.on('tree.click', function(e) {
    if (! $(e.click_event.target).hasClass('jqtree-title')) {
        // Clicked outside title, prevent selection
        e.preventDefault();
    }
});
```

As you can see you can prevent the selection using `preventDefault`. Also see the [documentation](https://mbraak.github.io/jqTree/#event-tree-click).

I hope that this will answer your question.
```

**Comment by mkrsII** [comment]
Ok, I can call e.preventDefault to allow for that, but I still have an issue where a textarea in a node is not focusable? Any idea.

Third problem, referring to the scrolling issue. I'm adding nodes via "appendNode" with no parent. When I add a bunch of nodes and drag and drop, the page won't scroll with the mouse

**Comment by mbraak** [comment]
I'll try to reproduce these issues.

**Comment by mbraak** [comment]
You could set the focus to the textarea yourself:

```js
$tree.on('tree.click', function(e) {
    var $target = $(e.click_event.target);
    if ($target.is('textarea')) {
        $target.focus();
        e.preventDefault();
    }
});
```

**Comment by mkrsII** [comment]
I added the above logic. That fixes click selectable area problem.

Next problem is I'm not able to change where the cursor is inside the textarea with the mouse. I can start typing when focused, just mouse events are acting strange.

**Comment by mbraak** [comment]
I tried to add node using appendNode. Drag-and-drop seems to work fine in combination with autoscroll.

I did the following:

```js
$tree.tree({
  data: [],
  dragAndDrop: true
});

for (var i = 1; i < 20; i++) {
    $tree.tree('appendNode', {name: 'node ' + i, id: i});
}
```

**Comment by mbraak** [comment]
I have the same problem with the cursor inside the textarea. I will see if I can find a solution.

**Comment by mkrsII** [comment]
@mbraak Ok

**Comment by mkrsII** [comment]
@mbraak Ok

**Comment by mkrsII** [comment]
@mbraak Ok

**Comment by mkrsII** [comment]
Ok

**Comment by mkrsII** [comment]
Ok

**Comment by mbraak** [comment]
The cursor issue is now fixed in the `dev` branch.

**Comment by mkrsII** [comment]
Thanks a lot.
