### ISSUE TITLE
iterate tree remove node

### ISSUE THREAD

**Issue by mkrsII** [mbraak/jqTree#447]
Hi, I have the following: 

function removeUnusedSkills()
{
var tree = $('#skillsTree').tree('getTree');
                tree.iterate(
                    function(node, level) {
                        if (node) {
                            if (node.MonthsUsed <= 0 && !node.isParent) {
                                $('#skillsTree').tree('removeNode', node.id);
                                // will not work either $('#skillsTree').tree('removeNode', node);
                                return false;
                            }
                            return true;
                        }                        
                    }
                );
}

calling remove here will not work. Is there a better way to remove nodes?

**Comment by mbraak** [comment]
That's strange. I tried the following code, it seems to work:

```js
var tree = $tree.tree('getTree');

tree.iterate(
    function(node, level) {
        if (node) {
            if (node.name == 'Tyrannosauroids') {
                $('#tree1').tree('removeNode', node);
                return false;
            }
            return true;
        }
    }
);
```
