### ISSUE TITLE
Updating the tree

### ISSUE THREAD

**Issue by atul-bajpai** [mbraak/jqTree#449]
Does loadData and reload method first remove the tree and then recreate the tree?? If yes, then is there a method which will just update the already existing tree instead of recreating it.
Because, in my case, i have a websocket which continuously updates the values in the tree, every 500 ms, and recreating a tree in this case will be very costly/ performance issue

**Comment by mbraak** [comment]
Yes, loadData and reload do recreate the tree.

If you only want to change existing nodes then it would be better to call [updateNode](https://mbraak.github.io/jqTree/#functions-updatenode) for each changed node.

**Comment by atul-bajpai** [comment]
ok thanks
