### ISSUE TITLE
destroy event

### ISSUE THREAD

**Issue by atul-bajpai** [mbraak/jqTree#450]
Is there any destroy event, which will destroy the tree, all it event binding, basically do the cleanup to avoid any kind of memory leaks.

**Comment by mbraak** [comment]
You can destroy the tree by calling `destroy`. This will remove the event bindings and all dom elements of the tree.

```js
$('#tree1')..tree('destroy');
```

I hope this answers your question.

**Comment by atul-bajpai** [comment]
Thanks, but I didn't found in the documentation. 
Anyways, thanks.

**Comment by mbraak** [comment]
The destroy function is now added the documentation.
