### ISSUE TITLE
Enhancement related questions 

### ISSUE THREAD

**Issue by swapnilsoftdel** [mbraak/jqTree#451]
This is the excellent plugin. Thanks to implement.

I have few requirements listed below. Just want to know that, is this possible using jQTree.

If yes ill go head with my implementation.

1. CheckBox for each node and if we check that box it should select the respective node.
2. If I select Parent node then automatically child should be checked. (Means all the checkbox should be checked.)
3. I want to give option like 'Read More', once click on that link next child node should be fetched.

**Comment by mbraak** [comment]
Hello,

Jqtree does not support these functions out of the box. However, it might be possible implement them using customizations.

For example, jqtree has the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option that you can use to create the checkbox for each node.

I think it's also possible to automatically select children nodes by binding the [tree.click](https://mbraak.github.io/jqTree/#event-tree-click) event.

I don't know if it's possible to implement the 'read more' functionality.

Greetings

**Comment by mbraak** [comment]
Closing this issue for now
