### ISSUE TITLE
Feature request - checkboxes

### ISSUE THREAD

**Issue by MichalGrzegorzak** [mbraak/jqTree#454]
Hi, thank You for sharing such excellent work!
May I propose a feature, I think check-boxes feature, (with or without autoselection), would be nice addition to it.

**Comment by mbraak** [comment]
Hello,

I'm not planning to add this feature at the moment. I would like to refer you to issue #386 that contains example code that adds a checkbox.

Another example is [the multiple select example](https://mbraak.github.io/jqTree/examples/08_multiple_select/) that does something similar.

**Comment by mbraak** [comment]
Closing the issue
