### ISSUE TITLE
rename 'id' property?

### ISSUE THREAD

**Issue by victor-blagomir** [mbraak/jqTree#456]
Having reserved 'id' property for multiple selection in jqTree prevents one to use it for other needs (for example the items that I load into jqTree have it's own 'id' property that is stored in database and that would be also good to show within the jqTree with custom layout, but since the 'id' is reserved, I am forced to rename my 'id' properties to something else in order to still be able to show it on the jqTree). 

Overall, the 'id' is rather common and widely used keyword for many objects, and thus, it would be good to rename it? For example to something like 'jqTreeId' or 'jqId'.. or 'treeId'?

**Comment by mbraak** [comment]
Hello Victor,

I understand what you're saying, but I'm not going to rename the id property. I would break a lot of code, if I would change it.

But perhaps there are other solutions. If the 'id' property in your database is unique and required, then you could perhaps use it for the multiple selection. It doesn't even have to be an integer, it could also be a string.

Greetings

**Comment by victor-blagomir** [comment]
Thanks for your quick response Marko. I see your point, will think what can be done on my side.. in any case it would be a workaround, which is not a perfect solution..
