### ISSUE TITLE
Make tree.click event to be triggered immediately

### ISSUE THREAD

**Issue by vblagomir** [mbraak/jqTree#457]
It seems that current `tree.click` event is triggered only after mouse click is de-pressed (similar to 'keyup' keyboard event vs 'keydown'). I assume the purpose of that might be in drag-and-drop functionality (to prevent undesired selection of nodes while dragging). But if drag-and-drop is disabled, it might feel much faster for end user to get node selected right away after the click. Or it might be a separate option so the functionality is available in drag-and-drop as well.

**Comment by vblagomir** [comment]
I have managed to do it with custom `mousedown` event on the tree, and getting the node with `getNodeByHtmlElement`, without using the `tree.click` event at all. Overall this is just an idea, feel free to close it if you don't want to proceed with it.

**Comment by mbraak** [comment]
Thank you! I will look into this.

**Comment by mbraak** [comment]
Not supporting this; closing the issue
