### ISSUE TITLE
autoscroll example

### ISSUE THREAD

**Issue by edwardsmarkf** [mbraak/jqTree#458]
hello - the autoscroll [example referenced here](https://github.com/mbraak/jqTree/issues/402) does not appear to be available anymore.   

may i please see an example of autoscroll?

**Comment by mbraak** [comment]
This is the new url: https://mbraak.github.io/jqTree/examples/07_autoscroll/

**Comment by edwardsmarkf** [comment]
hmmm sorry not sure how i missed that one.  thank you very much.

**Comment by mbraak** [comment]
Closing the issue
