### ISSUE TITLE
minor point

### ISSUE THREAD

**Issue by edwardsmarkf** [mbraak/jqTree#459]
hello - up front, jqTree takes "cool" to a whole entirely new level.  thank you very much for this jquery plugin.  the more i look in the documentation (reading the documentation, a historic first), the more stuff i find to play with.

https://mbraak.github.io/jqTree/examples/09_custom_html/#node-2

i notice on this page you are using  **&lt;   &gt;**  in the example code.   did you mean to do this?  when i copy/pasted your example, it just includes the html code and shows it as is, rather than interpreting the html stuff.

when i removed the &lt: and replaced with "<"  everything worked fine.

**Comment by mbraak** [comment]
Thanks! This is now fixed.
