### ISSUE TITLE
special highlighting for node.name

### ISSUE THREAD

**Issue by edwardsmarkf** [mbraak/jqTree#460]
hello - is there any way to add special html highlighting for a particular node.name value ?

i have tried the following, but all i get is an empty span:

$li('.jqtree-title').before('<span style="color: red;">');
$li('.jqtree-title').before('</span>');

$li('.jqtree-element').before('<span style="color: red;">');
$li('.jqtree-element').before('</span>');

**Comment by mbraak** [comment]
Perhaps you can use the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option. Also see [this example](https://mbraak.github.io/jqTree/examples/09_custom_html/).

**Comment by edwardsmarkf** [comment]
that is what i am using.  the issue is that when i try to insert any of these:

$li('.jqtree-title').before('<span style="color: red;">');
$li('.jqtree-title').append('</span>');

$li('.jqtree-element').before('<span style="color: red;">');
$li('.jqtree-element').append('</span>');

all i get a closed tag:

**<span style="color:red;"></span>**

in other words, the span is closed right away.

it would appear that **onCreateLi** allows me to put a complete span or div BEFORE and AFTER the name, but i cannot figure out how to affect the name itself since i am unable to determine how to put an open & close tag on either side of the name.

**Comment by mbraak** [comment]
I think you can use the [wrap](http://api.jquery.com/wrap/) function from jquery:

```js
$li('.jqtree-element').wrap('<span style="color: red;"></span>');
```

If you only want to change the style, then you can also [css](http://api.jquery.com/css/):

```js
$li('.jqtree-element').css('color', 'red');
```

You can also use [addClass](http://api.jquery.com/addClass/) to add a class.

**Comment by edwardsmarkf** [comment]
pure and total **AWESOMENESS**, i tell you.

if you have a moment, it might be a good idea to have an example of this with your onCreateLi page.

**Comment by mbraak** [comment]
Closing the issue
