### ISSUE TITLE
Formatting nodes as a table

### ISSUE THREAD

**Issue by clustor** [mbraak/jqTree#461]
Hi,

Is it possible to format individual (leaf or folder) nodes, custom properties of a node as a table with length for each column adjusting automatically?

I would like to create table showing the folders and files similar to a filesystem. Each node will have "modification date", "size of the folder/file" etc. I would like the "modification date" and "length" column to auto-adjust as well the node name.

When someone selects a leaf-node, I would like to show the preview of the file right underneath it. I think I can handle this with createLi.

Thanks.

**Comment by mbraak** [comment]
Hello,

I'm afraid you can't use a table structure for the tree. The tree is formatted with `ul` and `li` elements, and it is not possible to change that. At least not without changing the source code of jqTree.

You can indeed use the `onCreateLi` option to show a preview. Note the tree is not re-rendered when a user selects a node. So, you also have add the preview in the [tree.select](https://mbraak.github.io/jqTree/#event-tree-select) event.

Your code might look something like this:

```js
$('#tree1').bind(
  'tree.select',
  function(event) {
    var node = event.node;

    if (!node) {
      // deselect a node
      var previous_node = event.previous_node;
      var $previous_li = $(previous_node.element);

      // remove preview
    }
    else {
      // select a node
      var deselected_node = event.deselected_node;
      var $previous_li = $(deselected_node.element);

      // remove preview

      var $li = $(node.element);

      // add preview
    }
  }
);
```

Greetings
