### ISSUE TITLE
Dragging new nodes into Tree

### ISSUE THREAD

**Issue by activestylus** [mbraak/jqTree#463]
Let's say I have two lists. One is a navigable tree and the other is a flat list.

I want to be able to drag items from the flat list to the tree.

Is this doable?

**Comment by mbraak** [comment]
I'm afraid that's not supported by jqTree. Dragging from an outside source or between trees is not possible at this moment.
I would like to build this feature, but at the moment I have no idea how to build it.

**Comment by activestylus** [comment]
Maybe you can find inspiration here: https://github.com/RubaXa/Sortable

I use it to drag between lists no problem. But it's definitely not an out-of-the-box tree plugin, and things get hairy with scope as soon as you start moving nodes around.

It's a tricky problem for sure!

**Comment by mbraak** [comment]
Closing the issue for now
