### ISSUE TITLE
Handle an error response in case of "open" event

### ISSUE THREAD

**Issue by agougousis** [mbraak/jqTree#464]
Hi! Is there any way to handle an error response in case of open event? 
It would be very usefull in case that opening fails due to an expired session or expired CSRF token.

**Comment by mbraak** [comment]
Hello.
You could use the [onLoadFailed](https://mbraak.github.io/jqTree/#options-onloadfailed) option. This function is called when loading by ajax fails.

**Comment by agougousis** [comment]
Damn me! You are right! Thanks a lot! 
By the way, I am using your widget to an EU-funded open source application related to biodiversity that will be uploaded to GitHub next week. There will be a reference to your widget in readme file.
