### ISSUE TITLE
data call is creating a 404 with  route /?_=timestamp

### ISSUE THREAD

**Issue by maxschons** [mbraak/jqTree#465]
Hey!

I'm trying to make a data call (https://mbraak.github.io/jqTree/examples/02_load_json_data_from_server/) but the route always has a strange get parameter:

http://localhost:8000/nodes/?_=1480702806084 Failed to load resource: the server responded with a status of 405 (Method Not Allowed)

<div id="tree1" data-url="/nodes/"></div>

 $('#tree1').tree();

Any ideas? Thx!

**Comment by mbraak** [comment]
Hello,

The '_' parameter is there to prevent caching. Also see the cache setting in [jquery ajax settings](http://api.jquery.com/jquery.ajax/#jQuery-ajax-settings).

I think this is not related to the 'method not allowed' error. If you want to make sure, you can open the url (http://localhost:8000/nodes/) in a browser, and see what it does.

Greetings

**Comment by maxschons** [comment]
-.- Jepp, wrong route... a "/" to much. Thanks for your quick reply and the awesome work 👍

**Comment by mbraak** [comment]
Closing the issue
