### ISSUE TITLE
Add an emptyIcon option?

### ISSUE THREAD

**Issue by ChadSikorra** [mbraak/jqTree#466]
I'm currently using this library like so:

    this.tree = this.$el.tree({
        dragAndDrop: false,
        dataUrl: this.dataUrl,
        dataFilter: this.dataFilter,
        closedIcon: $('<i class="fa fa-folder"></i>'),
        openedIcon: $('<i class="fa fa-folder-open"></i>'),
        onCreateLi: this.renderTreeElement
    });

Overall this works fine. I'm loading all the tree data via a REST API with the `dataUrl` option. When I do this and a node is opened and the server returns no children nodes, the folder icon is removed completely. It would be nice to have a little more control over this by adding a `emptyIcon` option, so if a node is opened that has no children I could decide how it should be displayed visually.

In my case I would like to display the same icon as the `openedIcon` option. Is this something that could be added or can you think of a better way I should be implementing this with the library?

**Comment by mbraak** [comment]
I think this is a very specific use case. It's too specific to add an option for it. If you can do this using `onCreateLi`, then I think that is the best option.

**Comment by ChadSikorra** [comment]
How do I detect if the node has been opened in `onCreateLi`? If I could somehow detect that the node's children were already fetched or the state of the node on render this could probably be done there. Looking over the functions/options I'm struggling to figure out how to make it work that way.

**Comment by mbraak** [comment]
Could you tell me more about this? For example, are you using lazy loading?

**Comment by ChadSikorra** [comment]
Yes, I'm using lazy loading. So the children for each node is fetched from the server as needed. I found that I can use the `load_on_demand` property of the node to figure out if it was fetched already. However, it doesn't seem very intuitive at all to use this property for this purpose. This is what I'm doing at the moment:

```javascript
if (node.load_on_demand === false && node.children.length === 0) {
    $li.find('.jqtree-title')
        .css('margin-left', '.5em')
        .before($('<i class="fa fa-folder-open"></i>'));
}
```

**Comment by mbraak** [comment]
Yes, that's not so intuitive. But I don't know another solution.

**Comment by ChadSikorra** [comment]
It might be nice to have another event called `tree.load` or `tree.fetch` that is called after a node has been loaded on demand that contains the `node` and `$li` in the event. That way you know the node was just loaded remotely and would not have to rely on a property that seems to be used internally and may change.

Anyway, I'll close it out since I have a work around. Thanks for the time you've taken on this library though, it has really saved me lots of time.
