### ISSUE TITLE
bootstrap support

### ISSUE THREAD

**Issue by jsmad** [mbraak/jqTree#475]
Please consider changing the generated html code, to be more friendly with bootstrap.

Ideally, I'd like jqTree to produce output similar to this:
http://jonmiles.github.io/bootstrap-treeview/

Thank you.

**Comment by mbraak** [comment]
I think it's possible to use jqTree in Bootstrap. Note that the documentation of jqTree is written using Bootstrap: https://mbraak.github.io/jqTree/.

It is a bit difficult to produce the `bootstrap-treeview` output, because the structure of the html is completely different.

**Comment by jsmad** [comment]
This is the reason I opened this ticket, to consider the possibility of changing the generated html, to be more compatible with bootstrap. For example, using nested List Groups for the tree.

Currently, the way I'm doing it, is to re-write the jqTree css all over again by copying parts of the bootstrap CSS. Not ideal and the result is not exactly similar to bootstrap but close.
