### ISSUE TITLE
Revert drag-drop after ajax fail

### ISSUE THREAD

**Issue by jsmad** [mbraak/jqTree#476]
The current implementation requires us to do_move() first, then do an ajax call to save the change to database. Unfortunately, this implementation does not help in case the database returns an error.

For example:

```javascript
'tree.move',
function(event) {

	// Make the move
	event.move_info.do_move();

	// Ajax call
	$.post("move.php", {
		id: event.move_info.moved_node.id,
		parent: event.move_info.moved_node.parent.id
	},function(e) {

		if(e==="fail") {

			// Revert move
			event.preventDefault(); //  <--  too late!
			// The preventDefault() function is useless at this point.

		}

	});

}
```

Ideally, we would like something like the following:

```javascript
'tree.move',
function(event) {

	// Ajax call
	$.post("move.php", {
		id: event.move_info.moved_node.id,
		parent: event.move_info.moved_node.parent.id  //  <--  wrong!
		// The parent still points to the previous parent at this point.
	},function(e) {

		if(e==="success") {

			// Make the move
			event.move_info.do_move();

		} else {

			// Revert move
			event.preventDefault();

		}

	});

}
```

Unfortunately, the above solution does NOT work, because the variable event.move_info_moved_node.parent.id is wrong, since it is still pointing to the id of the PREVIOUS parent. The variable changes to the new parent only after do_move() has been executed, which hasn't happened yet.

In the first case, we could potentially solve the problem by implementing a new function that forces the drag and drop to revert itself. In the second case, we would need to change how jqtree works, by defining the final parent before do_move().

I'd appreciate your thoughts, maybe someone has solved this problem differently.

Thank you.

**Comment by mbraak** [comment]
I'm planning to add the new parent to the `move_info`, but this will not be implemented soon.

However, it should be possible to do the move with the existing data. And this is also how we implemented it at the company where I work.

This works as following:

The `move_info` object contains:
* `position`: 'before', 'after' or 'inside'
* `target_node`: the original node is moved after, before or inside the target node

The idea is that you give this information to the server. Then the server will do the correct move.

I hope this method will work for your system.

**Comment by jsmad** [comment]
Thank you for the quick reply,

Unfortunately, the existing position system (before/after/inside) is of no help to me, because my databases work differently. For example:

```
[0] nodeA ->
         [0] leaf
         [1] leaf
         [2] leaf
         [3] leaf
[1] nodeB - >
         [0] leaf
         [1] leaf
```

As you can see above, my database has a position number [0], [1], etc, below each tree node. Thus, when I re-order a node (within the same parent, or to a new parent), I need to get the numeric position of the new dropped place, so the ordering is stored properly in the database.

I managed to do that by using the following **horrible** code:

```javascript
	// Make the move
	event.move_info.do_move();

	// New position
	var newpos = $(event.move_info.moved_node.element).parent("ul.jqtree_common").children().index(event.move_info.moved_node.element);

	// Submit newpos in $.post...
```

But jqtree still can't handle $.post returning a fail, because I've already used do_move().

**Comment by mbraak** [comment]
It is possible to find the new parent using some code:

```js
$tree.on('tree.move', function(e) {
    e.preventDefault();

    var position = e.move_info.position;
    var target_node = e.move_info.target_node;

    function getNewParentNode() {
        if (position == 'inside') {
            return target_node;
        }
        else {
            // before or after
            return target_node.parent;
        }
    }

    var parent_node = getNewParentNode();
    //
});
```
