### ISSUE TITLE
how can i add dblclick event to a dynamic tree

### ISSUE THREAD

**Issue by boxersir** [mbraak/jqTree#477]
first this tree is empty and load on ajax..
please help me
/*****this demo don't work****/
$('#tree1').bind(
    'tree.dblclick',
    function(event) {
        // e.node is the clicked node
        console.log(e.node);
    }
);

**Comment by mbraak** [comment]
That's strange. Binding the `tree.dblclick` should work.

How are you loading the data? Are you using the [dataUrl](https://mbraak.github.io/jqTree/#options-data-url) option?

**Comment by boxersir** [comment]
my demo has two trees , I bind click and dblclick event to them .
var $tree=$(".tree");     //both of two trees hasclass tree.
$tree.bind('click',function(event) {
  	  // The clicked node is 'event.node'
	  if($(event.target).hasClass('jqtree-toggler')){
		  createSelectNode(node);//add children
	  }
   });
$tree.bind('tree.dblclick',function(event) {
  //do somethingelse
})
the first tree  everythings works well ,but the second tree only dblclik don't work
（first of all two trees are the same , when you click search button, the second tree is update and created by ajax json.....）

**Comment by mbraak** [comment]
I'm afraid I cannot reproduce this error.I tried the following: 

```html
<div id="tree1" class="tree" data-url="/example_data/"></div>

<div id="tree2" class="tree" data-url="/example_data/"></div>
```

```js
    var $tree = $('.tree');
    $tree.tree();

    $tree.bind('tree.click', function(e) {
        console.log('click', e);
    });

    $tree.bind('tree.dblclick', function(e) {
        console.log('dblclick', e);
    });
```
