### ISSUE TITLE
i use saveState:true ,the tree is create well,but the click event don't work

### ISSUE THREAD

**Issue by boxersir** [mbraak/jqTree#479]
Tips:  this tree is opened in another viewport

**Comment by mbraak** [comment]
Could you tell me what you mean with another viewport?

Do you use the `<meta name="viewport">` tag in the header?

**Comment by boxersir** [comment]
i'm sorry,'another viewport' mean another page。

**Comment by mbraak** [comment]
That sounds interesting. Could you tell me more about that?

Are the javascript and the tree html on different pages?

**Comment by boxersir** [comment]
this is  code, when i dblclick the tree element,open a new page ,then create the same tree and save the state, but the click event don't work.

$(function(){
	
    $(window).bind("load resize", function() {
        width = (this.window.innerWidth > 0) ? this.window.innerWidth : this.screen.width;
        if (width < 768) {
            $('div.sidebar-collapse').addClass('collapse')
        } else {
            $('div.sidebar-collapse').removeClass('collapse')
        }
    });   


 
  /*******************左侧项目下拉列表****************/
  EDM.api.data.datamodel(null,function(data){
  	  globalLevelOneObj = data;
  	  _creatLeftList(data);
     var obj = $("#model_lists").val();
     selectFileId={modelId:obj,fileId:""};
     //请求左侧树状结构
     if(!localStorage.getItem("tree")){
    	 EDM.api.data.projectdata({'fpath':obj,'spath':obj},function(data){
    		 _createTree(data,null,true);
    	 });
     }
	
  });
 
  $tree.bind('click',function(event) {

  	  if($(event.target).parents("div.tree").length!=0&&$(event.target).parents("div.tree").attr("bySearch")==undefined){
  		  if($(event.target).hasClass('jqtree-toggler')){
  			  var li = $(event.target).closest('li');
  			  var node = $tree.tree('getNodeByHtmlElement',li);
  			  createSelectNode(node);
  		  }
  		}
   });
  
  $tree.on('tree.dblclick',function(event) {
  	  // The clicked node is 'event.node'
  	  var node = event.node;
  	  //node文件类型判断
  	  if(node.type==1){
  		selectFileId.fileId=node.id;
  		$tree.tree('selectNode', node);

  		 window.open('http://192.168.2.254:8080/SYSJ/resources/web/tabmodel.html?modelId='+$("#model_lists").val()+'&fileId='+selectFileId.fileId+'?t='+new Date().getTime()); 
  		 return false;
  	  }else if(node.type==3){
  		  alert("请导出后查看！");
  	  }
  	  else{	  
  		  createSelectNode(node);
  	  }
	  	  
  	  }
  );
  
 
  
  $tree.height(treeHeight);
  
 
   
    $tree2.click(function(event){
    	if($(this).attr("bysearch")!=undefined){
    		console.log(event)
    	}
    })
    
});

 
 
  /*********************构造左侧文件树******************************/
  //data待处理数据；dom 树；flag是否初始化树；node 处理单节点
  function _createTree(data,dom,flag,node){
	  debugger;
      //父目录下有几个子目录data.files.length+data.directories.length
      var datas_tree=[];
      if(data.directories){
    	  for(var i=0;i<data.directories.length;i++){
    		if(data.directories[i].type==0){
    			parent_tree[i]={};
    			parent_tree[i].name=data.directories[i].name;
    			parent_tree[i].id=data.directories[i].id;
    			parent_tree[i].children=[];
    		}
	        datas_tree.push({name:data.directories[i].name,id:data.directories[i].id,children:[{}]});   
	        //var dealFPath = data.path.substring(data.path.indexOf('/')+1);
	        //请求目录下的子文件或者子目录
	        (function(i){
	      		EDM.api.data.projectdata({'fpath':$("#model_lists").val(),'spath':data.directories[i].id},function(_data){
	      		      var child_len=_data.files.length+_data.directories.length;
	      		      debugger;
	      		      console.log(child_len);
	        		  datas_tree[i].name+=' ['+child_len+']';  
	        		  if(i==datas_tree.length-1){
	        			  for(var m=0;m<parent_tree.length;m++){
	        				  if(parent_tree[m].children.length!=0){
	        					  datas_tree[m]= parent_tree[m];
	        				  }
	        			  }
	        			  if(node){
	        		    	  debugger;
	        		    	  return datas_tree;
	        		      }
	        		      if(flag){
	        		    	  debugger;
	        		    	var treeConfigObj = {
	        		  	      data: datas_tree,
	        		  	      dragAndDrop:false,
	        		  	      autoOpen: false,
	        		  	      saveState:true,
	        		  	      useContextMenu: false,
	        		  	      onCanSelectNode: function(node) {
	        		  	          //if (node.children.length == 0){
	        		  	        	  //return false;
	        		  	          // }
	        		  	          //else {
	        		  	        	  return true;
	        		  	          //}
	        		  	      }
	        		  	    }
	        		    	debugger;
	        		    	if(dom){
	        		    		dom.tree(treeConfigObj);
	        		    	}else{
	        		    		$tree.tree(treeConfigObj);
	        		    		$tree2.tree(treeConfigObj);
	        		    	}
	        		      }else{
	        		    	  debugger;
	        		    	if(dom){
	        		    		treeConfigObj = {
	        			  	      data: datas_tree,
	        			  	      dragAndDrop:false,
	        			  	      saveState:true,
	        			  	      autoOpen: true,
	        			  	      useContextMenu: false,
	        			  	      onCanSelectNode: function(node) {
	        			  	          //if (node.children.length == 0){
	        			  	        	  //return false;
	        			  	          // }
	        			  	          //else {
	        			  	        	  return true;
	        			  	          //}
	        			  	      }
	        			  	    }
	        		    		dom.tree(treeConfigObj);
	        		    		dom.attr("bySearch","true");
	        		    	   dom.tree('loadData',datas_tree);
	        		    	}else{
	        		    	   $tree.tree('loadData',datas_tree);
	        		    	   $tree2.tree('loadData',datas_tree);
	        		    	}
	        		      }
	        		  }
	        	  });
	      	}(i));
	      }
      }
   
      debugger;
      //TODO
//      datas_tree.length=0;
      var dataFiles = data.projectFiles || data.files ||[]; 
      debugger;
	  for(var s=0;s<dataFiles.length;s++){
		var fileNamePath,fileIdPath;
		if(dataFiles[s].name){
			fileNamePath = dataFiles[s].name;
			fileIdPath = dataFiles[s].id;
		}else{
			fileNamePath = dataFiles[s].namePath.substring(dataFiles[s].namePath.lastIndexOf('/')+1);
			fileIdPath = dataFiles[s].idPath.substring(dataFiles[s].idPath.lastIndexOf('/')+1);
		} 
		if(dom && dom==$tree2){
			for(var k=0;k<parent_tree.length;k++){
			    if(fileNamePath.indexOf('.')>-1){
			    	//找到具体带有后缀的文件
			    	if(parseInt(fileIdPath)>parent_tree[k].id){
			    		//判断id的范围
			    		parent_tree[k].children.push({name:fileNamePath,id:fileIdPath,type:dataFiles[s].type});
			    	}
//			    	datas_tree.push({name:fileNamePath,id:fileIdPath,type:dataFiles[i].type});
				}
				
			}
		}else{
			datas_tree.push({name:fileNamePath,id:fileIdPath,type:dataFiles[s].type});  
		}
		
      }
	  if(node){
    	  debugger;
    	  return datas_tree;
      }
     
     

  }
  
  function _contmenu(obj,modelName){
	  /*********************文件树右键****************/
	  $.contextMenu({
	      selector: '.jqtree-element',
	      autoHide: true, 
	      callback: function(key, options) {
	    	  var element=document.querySelector('.tree .jqtree-title');
	    	  var node=$("#tree1").tree("getNodeByHtmlElement",element);
	          var m = "clicked: " + key;
	          var selectfFile=$(".jqtree-selected .jqtree-title").text();
	          var lenM=0;//模板打开文件的个数
	         
	          console.log(selectfFile);
	          console.log(options.$trigger);
	          if(key=="export"){
	             
	          };
	           if(key=="compare"){
	        	   debugger;
	        	 var element=document.querySelector('.tree .jqtree-selected');
	 	    	 var node=$("#tree1").tree("getNodeByHtmlElement",element);
	        	 var dataId=node.getData();
	             if(!compareFlag){
	            	 compare_params.left_file_id=node.id;
	            	 str_h+="<tr><td>序号</td><td>消息</td><td>"+selectfFile+"</td>";
	            	 compareFlag=true;
	             }else{
	            	 compare_params.right_file_id=node.id;
	            	 str_h+="<td>"+selectfFile+"</td></tr>";
	            	 compareFlag=false;
	             };

	             }
	             
	             
	           }
	      },
	      items: {
	      	"export": {name: "导出数据", icon: "fa-download"},
	      	"sort": {name: "排序", icon: "fa-sort-alpha-asc"},
	        "compare": {name: "选为左侧比较文件", icon: "fa-exchange"}
	      	//,
	          //"sep1": "---------",
	          // "quit": {name: "Quit", icon: function(){
	          //     return 'context-menu-icon context-menu-icon-quit';
	          // }}
	      },
	      events:{
	      	show:function(options){
	        	var node = $(this).closest('li.jqtree_common').data('node');
	        	$tree.tree('selectNode', node);
	      		return true;
	      	}
	      },
	      build:function($triggerElement,e){
	    	  var node = $triggerElement.closest('li.jqtree_common').data('node');
	    	  var parentLists=node.parent.children;
	    	  if(node.type==1 || node.type==3){
	    		  return {
	        		  callback:function(key, options){
	        			  if(key=="export"){
			                   //导出文件
				               selectFileId.fileId=node.id;
		                       window.open('http://192.168.2.254:8080/SYSJ/downloadFileForWebPage/'+selectFileId.modelId+'/'+node.id);
		                       return;
		                  };
	        		  },
	        		  items:{
                       "export": {name: "导出数据", icon: "fa-download"},
                       "exportpack": {name: "导出网络数据包", icon: "fa-download"},
                       "按模板打开":{name:"按模板打开",icon: "fa-th-list",items:obj},
                       "draw":{name:"绘制曲线",icon:"fa-picture-o"},
                       "packfx":{name:"包络分析",icon:"fa-picture-o",items:{"packfx_0":{name:"选入待分析数据"},"packfx_1":{name:"选入子样分析数据"}}},
                       "paramsfx":{name:"选入参数性能分析数据",icon:"fa-picture-o"},
	        		  }
	        	  }
	    	  }
	    	  
	      }
	  });
  }

function _createTreeByS(data,dom,flag,node){
    //父目录下有几个子目录data.files.length+data.directories.length
	debugger
    var datas_tree=[];
      var dataFiles = data.projectFiles || data.files ||[];  
	  for(var i=0;i<dataFiles.length;i++){
		var fileNamePath,fileIdPath;
		if(dataFiles[i].name){
			fileNamePath = dataFiles[i].name;
			fileIdPath = dataFiles[i].id;
		}else{
			fileNamePath = dataFiles[i].namePath.substring(dataFiles[i].namePath.lastIndexOf('/')+1);
			fileIdPath = dataFiles[i].idPath.substring(dataFiles[i].idPath.lastIndexOf('/')+1);
		} 
		if(dom && dom==$tree2){
			for(var j=0;j<parent_tree.length;j++){
			    if(fileNamePath.indexOf('.')>-1){
			    	//找到具体带有后缀的文件
			    	if(parseInt(fileIdPath)>parent_tree[j].id){
			    		//判断id的范围
			    		parent_tree[j].children.push({name:fileNamePath,id:fileIdPath,type:dataFiles[i].type});
			    	}
				}
			}
		}else{
			datas_tree.push({name:fileNamePath,id:fileIdPath,type:dataFiles[i].type});  
		}
      }
	  for(var j=0;j<parent_tree.length;j++){
		  if(parent_tree[j].children.length!=0){
			  datas_tree[j]= parent_tree[j];
		  }
	  }
     if(node){
  	  debugger;
  	  return datas_tree;
     }
     if(flag){
  	 var treeConfigObj = {
	      data: datas_tree,
	      dragAndDrop:false,
	      autoOpen: true,
	      saveState:true,
	      useContextMenu: false,
	      onCanSelectNode: function(node) {
	        return true;
	      }
	    }
  	debugger;
  	if(dom){
  		dom.tree(treeConfigObj);
  	}else{
  		$tree.tree(treeConfigObj);
  		$tree2.tree(treeConfigObj);
  	}
    }else{
	  	  debugger;
	  	if(dom){
	  		treeConfigObj = {
		  	      data: datas_tree,
		  	      dragAndDrop:false,
		  	      autoOpen: true,
		  	      useContextMenu: false,
		  	      onCanSelectNode: function(node) {
		  	        	return true;
		  	      }
		  	}
	  		dom.tree(treeConfigObj);
	  		dom.attr("bySearch","true");
	  	   dom.tree('loadData',datas_tree);
	  	}else{
	  	   $tree.tree('loadData',datas_tree);
	  	   $tree2.tree('loadData',datas_tree);
	  	}
    }
    //TODO
}



function createSelectNode(node){
	  if(node.is_open){
		 $tree.tree('updateNode',node,{name:node.name,id:node.id,children:[{}]});
		 $tree.tree('closeNode',node);
		 $tree.tree('selectNode', node);
	  }else{
		 
		 EDM.api.data.projectdata({'fpath':$("#model_lists").val(),'spath':node.id},function(data){
			 debugger;
			var childrenData = _createTree(data,null,false,node);
			var liname=[];//存放树的子节点名字;
			var sortchild=[];//排序后的子数据
		     debugger;
			if(childrenData&&childrenData[0].type!=undefined){
				for(var i=0,len=childrenData.length;i<len;i++){
	  				var obj=childrenData[i];
	  				liname.push(obj.name);
	  			}
	  			//对name排序
	  			var nliname=liname.sort(function compareFunction(param1,param2){
	  				 return param1.localeCompare(param2);
	  			 });
	  			
				for(var j=0,len=nliname.length;j<len;j++){
					sortchild[j]={};
					for(var l=0,len=childrenData.length;l<len;l++){
						if(childrenData[l].name==nliname[j]){
							sortchild[j].name=nliname[j];
							sortchild[j].id=childrenData[l].id;
							sortchild[j].type=childrenData[l].type;
						}
					}
				}
			}else{
				
				sortchild=childrenData;
			}
			 $tree.tree('updateNode',node,{name:node.name,id:node.id,children:sortchild});
	  		 $tree.tree('openNode',node);
	  		 $tree.tree('selectNode', node);
	     }); 
		 
	
	  }
}

**Comment by boxersir** [comment]
can you understand, sorry, my English is very poor, please help me,

**Comment by mbraak** [comment]
Do you think the error is in jqTree, or in your code?

**Comment by boxersir** [comment]
i think the error is in my code logic , but i can't find it

**Comment by mbraak** [comment]
I'm afraid this code is too complicated for me to understand.

**Comment by boxersir** [comment]
ok, thanks all the same
