### ISSUE TITLE
1.3.8 backwards compatibility issue with 1.3.7

### ISSUE THREAD

**Issue by luciano-deriu** [mbraak/jqTree#481]
Hi,

The 1.3.8 release has broken our Tree that worked in 1.3.7. We are still investigating this issue to see if it's something in the way we have used the library but i thought you would also like to be aware of it in case it is a bug in 1.3.8.

We get an error in the `FolderElement.prototype.open` function. Specifically the line `$button.get(0).appendChild(icon);` with the reason:

> Uncaught TypeError: Cannot read property 'appendChild' of undefined

In our bower.json we have the version pattern "~1.3.3", which means it will update to the latest PATCH version of your library but 1.3.8 doesn't seem to be a small patch change as there are some big changes like moving to TypeScript and Webpack and dropping IE8 support (i believe). Do you follow the "SemVer" approach to versioning jqTree?

Thanks

**Comment by mbraak** [comment]
Hello,

Yes, i think it would have been better to go version 1.4.0. However, version 1.3.8 should still be compatible with 1.3.7.

Greetings

**Comment by mbraak** [comment]
The error message suggests that the `button` element is missing. I don't know how that is possible.

I added a fix to the `dev` branch that handles this particular situation.

**Comment by luciano-deriu** [comment]
Thanks @mbraak.

We have also investigated further and found that we were recursively opening parent nodes in the tree but we weren't checking if we reached the root node in the tree so it kept going up the DOM.

**Comment by mbraak** [comment]
Ok thanks! Closing the issue.
