### ISSUE TITLE
After clicking textarea, clicking non-root node of the tree doesn't get focus back to the tree 

### ISSUE THREAD

**Issue by bnsblue** [mbraak/jqTree#482]
Hi,
I am trying to create an editor app with jqTree and a text area (ace editor). I am encountering a problem in if I do the following steps:

(1) I click the text area first
(2) Then I click on any of the non-root node, 

The clicked node will be selected, but the focus won't come back to the tree. That is, if I press arrow keys at this point, the keyboard navigation of the tree won't work, but the cursor in the text area will move. I have to click the root node to get the focus back on the tree again.

What I want to achieve is that, I'll be able to get the focus on the tree again no matter which node I click. Since the selectedNode is correct, I wonder if this could be a bug. 

Any suggestion is much appreciated!

Thanks for the awesome project btw.

**Comment by mbraak** [comment]
Hello,

The keyboard handling is disabled when the focus is on a textarea or an input field. So, apparently in this situation the focus is on the textarea.

Perhaps you can use the [tree.click](https://mbraak.github.io/jqTree/#event-tree-click) event to change the focus when a node is selected.

Please let know if this works.

Greetings,
Marco

**Comment by bnsblue** [comment]
I wrote a function as follows:

```
$('#tree1').bind(
    'tree.click',
    function(event) {
       $('#tree1').focus();
       var active = document.activeElement;
       console.log("ActiveElement:" + active.tagName + active.id);
    }
);
```
But it still doesn't work. Same behavior as before. Is my way of setting focus correct?

**Comment by mbraak** [comment]
Perhaps you can unfocus the textarea:

```js
$('#my_textarea').blur();
```

**Comment by bnsblue** [comment]
Thanks for the tip! That seems to approach the problem one step further. What I am trying is the following:
```
var active = document.activeElement;
active.blur();
$('#tree1').focus();
console.log("ActiveElement:" + active.tagName + "(" + active.id + ")");
```
But I found that the focus is on body instead of on the tree. Here's what in console:
```
ActiveElement:BODY()
```
Functionality-wise it achieves what I currently want, but I think that's because jqTree accepts keyboard input as long as the focus is not on textarea or input. If we put two jqTrees in the same app, then I would assume that this will cause problem again.

Any suggestions?

**Comment by mbraak** [comment]
I added a `tabindex="-1"` attribute to my tree `div`, and now I can set the focus to it. This works in Chrome.

```html
<div id="tree1" tabindex="-1"></div>
```

```js
$('#tree1').focus();
```

**Comment by mbraak** [comment]
I changed the following: if you select a node, it gets the focus. This means that you don't have to focus the tree.
The change is in the `dev` branch.

**Comment by mbraak** [comment]
I'm also considering the following change:

Keyboard support only works if the tree (or a node) has the focus.

**Comment by bnsblue** [comment]
Thank you for the new commit! I'll try it out soon!

I think that design (i.e., keyboard only works if the tree has the focus) definitely makes sense to me. Do you have any concern regarding to that change?

**Comment by bnsblue** [comment]
The version in the dev branch works for me! Not sure why the activeElement is still showing "BODY", though.

**Comment by mbraak** [comment]
I added the following change:

Keyboard support only works if the tree (or a node) has the focus.
