### ISSUE TITLE
Small error in documentation for Example 10

### ISSUE THREAD

**Issue by msholly** [mbraak/jqTree#483]
Thanks for your work on this library. I caught a small error in your example 10 documentation I believe. 
http://mbraak.github.io/jqTree/examples/10_icon_buttons/

~~~~
closedIcon: $('&lt;i class="fa fa-arrow-circle-right"&gt;&lt;/i&gt;'),
openedIcon: $('&lt;i class="fa fa-arrow-circle-down"&gt;&lt;/i&gt;')
~~~~

Should be actual '<' and '>', since it looks properly escaped. This works fine in my Angular App.

~~~~
closedIcon: $('<i class="fa fa-chevron-right"></i>'),
openedIcon: $('<i class="fa fa-chevron-down"></i>'),
~~~~

**Comment by mbraak** [comment]
Thanks! This is now fixed.
