### ISSUE TITLE
KeyHandler moves in all trees

### ISSUE THREAD

**Issue by straubr** [mbraak/jqTree#484]
Hey mbraak,

first of all: kudos and thanks for this lib, it looks and works great!

I'm currently using jqTree to populate two dropdown. When a children in tree1 is selected, tree2 is dynamically loaded with data.

However, when trying to navigate in either tree via keyboard, BOTH trees move a node up or down. Am I missing a setting or is this not working as intended?

Best regards and many thanks,
Rolf

**Comment by mbraak** [comment]
Hello Rolf,

This is a known issue and it's fixed in the `dev` branch. In the new version, a tree will only handle the keyboard if it is has the focus.

Greetings,
Marco

**Comment by straubr** [comment]
Great, thanks for the quick feedback :)
