### ISSUE TITLE
Getting index of drop

### ISSUE THREAD

**Issue by thk-risma** [mbraak/jqTree#485]
First of all, great plugin!

Is their anyway to obtain the position (index) of the dropped element. Right now I get the position of the element when the move is done, but it need the index before the move. I use $(element).index().  Before the move, it will count itself within the index.

**Comment by mbraak** [comment]
You can do something like this:

```js
$('#tree1').on(
  'tree.move',
  function(event) {
    // This is the node before the move is done
    var node = event.moved_node;
    var parent = node.parent;

    if (parent) {
      var child_index = parent.getChildIndex(node);

      console.log('index', child_index);
    )
  }
);
```

I haven't tried it yet, but I think it should work. Please let me know if it works.

**Comment by thk-risma** [comment]
Thank you for your reply.

I ended up using this method to get the new index. 
var index = 0;`
if (position == 'inside') {
        var parent = target_node;
    }
    else {
        var parent = target_node.parent;
        index = $(event.move_info.target_node.element).index() + 1;
    }`
