### ISSUE TITLE
is there any way to check if the tree is already initialised or not ?

### ISSUE THREAD

**Issue by razakcbe** [mbraak/jqTree#486]
I am facing duplicate event request due to multiple initialisation issue.

Thanks for this great plugin.

**Comment by mbraak** [comment]
There is no function to check if the tree is initialized.

Perhaps, you can use the [tree.init](https://mbraak.github.io/jqTree/#event-tree-init) event?

```js
var is_initialized = false;

// connect the tree.init event before initializing the tree
$('#tree1').bind(
    'tree.init',
    function() {
        is_initialized = true;
    }
);

$('#tree1').tree();
```

**Comment by abdulrazak-mumms** [comment]
I have used this `($tree[0].children.length != 0)` to check tree whether tree is initialised or not.

Thank You. It almost served my purpose

**Comment by razakcbe** [comment]
I have used this ($tree[0].children.length != 0) to check tree whether tree is initialised or not.

Thank You. It almost served my purpose

**Comment by razakcbe** [comment]
I have used this ($tree[0].children.length != 0) to check tree whether tree is initialised or not.

Thank You. It almost served my purpose

**Comment by razakcbe** [comment]
$tree.tree('loadData', sampledata); 

When I load tree 5 times for every user call lead to tree initialisation for 5 times and every click event happening 5 times.

**Comment by razakcbe** [comment]
is there a way to intialize the tree and we can use the handle to load data for successive request ?

```
function constructTree(data, container, isFirstCall){
var $tree = $('#'+container);

if(isFirstCall){
$tree.tree({
			data: pathArray,
			onCreateLi: function(node, $li) {
				// my logic to customize each node
				}
			}
		});
}else {
$tree.tree('loadData', pathArray);
}

$tree.bind(
			'tree.select',
			function(event) {
				if (event.node) {
					var node = event.node;

				}
			}
	);
	
	$tree.on(
			'click', '.fav-icon',
			function(e) {
				var node_id = $(e.target).data('node-id');
				var node = $tree.tree('getNodeById', node_id);
				if (node) {

				}
			}
	);
}
```

constructTree(data, 'gwt-container', true);
constructTree(data, 'gwt-container', false);
constructTree(data, 'gwt-container', false); 
constructTree(data, 'gwt-container', false);

Here initialisation of my tree is equal to number of times of calling constructTree function.

**Comment by mbraak** [comment]
It is possible to deinitialize the tree. See https://mbraak.github.io/jqTree/#functions-destroy

**Comment by razakcbe** [comment]
Thank You. Is there any idea why tree is initialising every time when I call loadData function ?

**Comment by mbraak** [comment]
That is indeed strange. I'll try to reproduce that.

**Comment by mbraak** [comment]
I could not reproduce the error.

I called loadData multiple times. I got only 1 'tree.init' event.

```js
$tree.tree({ data: data });  // this triggers tree.init

$tree.tree('loadData', data);
$tree.tree('loadData', data);
```

**Comment by razakcbe** [comment]
Did you try it out with event bind ?.

Try it out with tree.select or click event. You might get event call same number of times. I didn't find any strange issue in UI. Though UI looks good, I got his multiple request in debug mode

**Comment by mbraak** [comment]
Hello,

I see that you are binding the `tree.select` and `click` events there. It looks like you are doing this for every call of constructTree. I think you should only bind when `isFirstCall` is true,

I could be wrong, but perhaps this is related to the error.

Greetings

**Comment by abdulrazak-mumms** [comment]
Yes  You are right. Thank You. I am binding event multiple times.
