### ISSUE TITLE
How to set the selection of exact nodes?

### ISSUE THREAD

**Issue by terryoy** [mbraak/jqTree#487]
Hi,

I would like to set the exact selection of nodes in the tree. I have read the document and thought the "setState" method would work. 
https://mbraak.github.io/jqTree/#functions-setstate

If I set "selected_node=[]", I expected that the tree will clear the selection of nodes, but found out it won't.

The source codes seems only to add the nodes supplied by "selected_node", but will not remove those already selected but not in the list.
https://github.com/mbraak/jqTree/blob/master/src/save_state_handler.ts#L145

**Comment by mbraak** [comment]
Hello,

It's probably better to use the functions for [multiple selection](https://mbraak.github.io/jqTree/#multiple-selection).

Something like this:

```js
// remove selection
const selected_nodes = $tree.tree("getSelectedNodes");

selected_nodes.forEach(
    function(node) {
        $tree.tree("removeFromSelection", node);
    }
);

// selected nodes
const node_ids_to_be_selected = [19, 28, 31];

node_ids_to_be_selected.forEach(
    function(node_id) {
        const node = $tree.tree("getNodeById", node_id);

        if (node) {
            $tree.tree("addToSelection", node);
        }
    }
);
```

**Comment by mbraak** [comment]
I will have a look at the setState function. Like you mentioned, it should clear the selection.

**Comment by mbraak** [comment]
The setState bug is now fixed in the dev branch. If you call setState, it will clear the existing selection.

**Comment by terryoy** [comment]
thanks for quick reply! It is working now.

**Comment by mbraak** [comment]
Ok. Closing the issue.
