### ISSUE TITLE
Cannot insert SVG xlink as openedIcon/closedIcon

### ISSUE THREAD

**Issue by terryoy** [mbraak/jqTree#489]
Hi,

I'm trying to use svg icon as openedIcon/closedIcon and failed. 

My settings is like:

```javascript
{
  // ...
  openedIcon: '<svg class="icon icon-tree-arrow-down " viewBox="0 0 32 32"><use xlink:href="#icon_tree_arrow_down" /></svg>',
  closedIcon: '<svg class="icon icon-tree-arrow-right " viewBox="0 0 32 32"><use xlink:href="#icon_tree_arrow_right" /></svg>'
}
```

But the output html removed the <use> element leaving only:

```html
<svg class="icon icon-tree-arrow-down " viewBox="0 0 32 32"></svg>
<svg class="icon icon-tree-arrow-right " viewBox="0 0 32 32"></svg>
```

It's probably caused by this shallow clone instead of deep clone when appending the icon node.
https://github.com/mbraak/jqTree/blob/master/src/elements_renderer.ts#L138

**Comment by mbraak** [comment]
I'll have a look at it.

**Comment by mbraak** [comment]
It seems to work with a deep clone. I have pushed a new version to the `dev` branch.

**Comment by terryoy** [comment]
Yes. I tested it in local.

**Comment by mbraak** [comment]
Great! Closing the issue.
