### ISSUE TITLE
All Nodes in expanded state when loading from JSON

### ISSUE THREAD

**Issue by gligorov** [mbraak/jqTree#490]
I am loading the tree with JSON data form the server, and creating the tree with the default option of only getting data option.  The tree is created, but all the nodes are expanded.

Tried setting up the options, still not working.
  $('#tree1').tree({
                            data: JSONContent,
                            autoEscape: false,
                            autoOpen: false
                        });
Using version 1.4.0, under IE and on Chrome same result.

**Comment by mbraak** [comment]
That's strange. I will try to reproduce this.

**Comment by gligorov** [comment]
Here is a screenshot 
![untitled](https://user-images.githubusercontent.com/1810069/27352764-71f0a3bc-55c7-11e7-9e51-a154791b247d.png)
with some JS exceptions I get

**Comment by mbraak** [comment]
It is possible that the ``jqtree.css`` file is not loaded correctly. In that case all nodes are expanded. Could you please check this?

**Comment by gligorov** [comment]
The problem seems to happen only in IE 11.   It does not happen in Edge, or Chrome browsers.

Is there a specific JQuery version that is best to use so that it works under IE 11?

**Comment by mbraak** [comment]
Jquery 3.x should work fine for IE 11. I will check if I can reproduce this error.

**Comment by mbraak** [comment]
I could not reproduce the error on IE 11.

I see that you are using `autoEscape: false` option. Could the error be related to that?

**Comment by gligorov** [comment]
Had to do a work-around, using this recursive function and now it looks as it should  after loading...

function ColapseNode(treeControl, root) {

                //Ensure first to collapse the very last children before the node
                for (var i = 0; i < root.children.length; i++) {

                    var curNode = root.children[i];

                    //check if there are children and ensure to collapse first them 
                    if (curNode.children.length > 0) 
                        ColapseNode(treeControl, curNode);

                    //now collapse the current node by calling open/close
                    treeControl.tree('openNode', curNode);
                    treeControl.tree('closeNode', curNode);
                }


                //One final workaround for ROOT node
                if (root.parent != null) {
                    treeControl.tree('openNode', root);
                    treeControl.tree('closeNode', root);
                }
            }

**Comment by mbraak** [comment]
I'm glad that it works.
