### ISSUE TITLE
Define open/closed icons via CSS

### ISSUE THREAD

**Issue by aimeos** [mbraak/jqTree#491]
It would be easier to change the icons dynamically if open/closed icons are defined via CSS, e.g.
```
ul.jqtree .jqtree-folder .jqtree-toggler.jqtree-closed:before {
  content: "►";
}
ul.jqtree .jqtree-folder .jqtree-toggler:before {
  content: "▼";
}
```

**Comment by mbraak** [comment]
Yes, perhaps it would. But I don't want to change the existing [openedIcon](https://mbraak.github.io/jqTree/#options-openedicon) construction, because it would break existing code.

**Comment by aimeos** [comment]
Developers should still be able use the opendIcon/closedIcon option in the constructor so existing code still works. If the options are set, the JS code can overwrite the icon using inline styles. If you like, you can make that two options deprecated in the docs but that's not essential.

**Comment by mbraak** [comment]
Is there a direct use case where using css for the icons is better?

**Comment by aimeos** [comment]
For example, open/close all nodes is much easier and faster if you can only change the CSS classes instead of traversing the whole tree and call the openNode/closeNode function on each node. But this also requires CSS based icons.

**Comment by mbraak** [comment]
I am not going to change this in the jqtree code. But I think there is an alternative:

If you set `openedIcon` and `closedIcon` to " " (a single space), then the buttons will be empty. This will allow you to set the icons in css.

```js
$tree.tree({
  openedIcon: " ",
  closedIcon: " "
});
``` 

```css
ul.jqtree-tree .jqtree-folder .jqtree-toggler.jqtree-closed:before {
  content: "►";
}
ul.jqtree-tree .jqtree-folder .jqtree-toggler:before {
  content: "▼";
}
```

**Comment by aimeos** [comment]
Thanks for your hint. This way it works pretty well.

Here's the JS code for expanding/collapsing all nodes for completeness:
```
$("body").on("click", ".collapse-all", function(ev) {
	$(".jqtree-folder .jqtree-toggler", ev.delegateTarget).addClass("jqtree-closed");
	$(".jqtree-folder", ev.delegateTarget).addClass("jqtree-closed");
	$('ul.jqtree_common[role="group"]', ev.delegateTarget).css("display", "none");
});

$("body").on("click", ".expand-all", function(ev) {
	$(".jqtree-folder .jqtree-toggler.jqtree-closed", ev.delegateTarget).removeClass("jqtree-closed");
	$(".jqtree-folder.jqtree-closed", ev.delegateTarget).removeClass("jqtree-closed");
	$('ul.jqtree_common[role="group"]', ev.delegateTarget).css("display", "block");
});
```

**Comment by mbraak** [comment]
I'm glad to hear that it works. Closing the issue.
