### ISSUE TITLE
Tab index for root node

### ISSUE THREAD

**Issue by aimeos** [mbraak/jqTree#493]
How can I assign a different tabindex attribute value to the span tag of the root node? For all other nodes, passing a function for "onCreateLi" works but the root node always has a tabindex value of "0".

Is there a way to prevent selecting (focusing) the root node by default?

**Comment by mbraak** [comment]
That's a little strange. A node should only get a tabindex 0 if it's selected.

**Comment by aimeos** [comment]
That's exactly the problem. `NodeElement.prototype.select/deselect()` change the tabindex attribute and disturb the tab order: https://github.com/mbraak/jqTree/blob/d6601312bfb8fcc3097a0812c475e17314052667/lib/node_element.js#L39

I want to select the current node automatically but don't want to change the tabindex so tabbing through all elements (not only the nodes) works like expected. How can I overwrite these two methods? Adding this before instantiating the tree doesn't seem to work:
```
NodeElement.prototype.select = function () {
    // ...
}
```

**Comment by mbraak** [comment]
At this moment it's not possible to set the tabindex.

I could add the option `tabIndex`. Would that be a solution for you?

**Comment by aimeos** [comment]
Not really. I have to overwrite the two NodeElement methods somehow because I have to remove these two lines:
```
        $span.attr("tabindex", 0);
        $span.focus();
```
Otherwise, the tab order is too chaotic and the focus is on the tree, not on the toolbar.

BTW: What does the option "keyboardSupport" exactly do?

**Comment by mbraak** [comment]
Jqtree has keyboard support. So, if the tree has the focus, then you can navigate using up/down/left/right.

You can turn this feature on or off using the option `keyboardSupport` (true/false). By default the option is true.

**Comment by aimeos** [comment]
The keyboard support is a cool feature! :+1: 

I think, setting the tabindex attribute to "0" or "-1" depending on a node is selected or deselected is a mis-feature. What was the intend behind this code?

In my opinion, the tabindex attribute should not be changed to prevent chaos in the tab order. Then, a new "tabindex" configuration value when creating the tree makes more sense.

**Comment by mbraak** [comment]
If you have multiple trees, then you want one tree to handle the keyboard. This is the tree that has the keyboard focus.
This also applies if you have other components with keyboard support.

**Comment by aimeos** [comment]
Sure, but "focus" and "tabindex" are two different things. With multiple trees you want to control the tree that has the focus by using the arrow keys. But the tab index value is for the tabulator key. Thus, you can control the current tree with the arrow keys (by calling the methods of the tree to set the focus to the new node) without changing the tabindex values.

I removed the code for setting the "tabindex" attribute in our application and keyboard support still works. Therefore, I would say setting the tab index in select()/deselect() is a bug, not a feature.

**Comment by mbraak** [comment]
Another thing is that it should be possible to select the tree using tab, just like other controls. For that it needs a tabindex of 0 or a positive value. See [mdn tabindex](https://developer.mozilla.org/nl/docs/Web/HTML/Global_attributes/tabindex).

**Comment by aimeos** [comment]
Yes, that's true. That's the reason why a new "tabindex" option for each tree is necessary like you've suggested. Then, we can set the tab index for the tree nodes depending on the other elements in the page.

**Comment by mbraak** [comment]
Ok. I will add the `tabIndex` option.

**Comment by mbraak** [comment]
I added the `tabIndex` option.

```js
$('#tree1').tree({
    tabIndex: 5
});
```

**Comment by aimeos** [comment]
Great! But you also have to remove setting the tabindex to "-1" in `NodeElement.prototype.deselect()`. This creates a chaotic tab order: https://github.com/mbraak/jqTree/blob/dev/src/node_element.ts#L51

**Comment by mbraak** [comment]
In which situation does this create a chaotic tab order?

**Comment by aimeos** [comment]
After using the keyboard to navigate in the tree, each node that lost the focus gets a tabindex of -1. When you select an element outside of (and before) the tree with the mouse and tab again through the elements, the tab order gets screwed up.

**Comment by mbraak** [comment]
I will try to reproduce this.

**Comment by mbraak** [comment]
Changed: if you deselect a node, then the tabindex is removed. Also see #494.

**Comment by aimeos** [comment]
Sorry, but removing the `tabindex` attribute isn't better than before if everything else has a tab index greater than zero. You need to leave the `tabindex` attribute untouched in select()/deselect().

**Comment by mbraak** [comment]
I could not reproduce this error. But perhaps there is an alternative. I can add the following:

If you set the option `tabIndex` to null, then jqtree will not set the tabindex.

**Comment by aimeos** [comment]
But I need to set the `tabindex` attribute value to 1 like the other elements
