### ISSUE TITLE
tree.init does not seem to work for me

### ISSUE THREAD

**Issue by edwardsmarkf** [mbraak/jqTree#496]
hello - 

i am trying to determine a way to fire an event AFTER the tree completely loads.  binding "tree.init" does not seem to work for me.

is there any way to fire an event after the tree loads?  

note:  jqTree is totally awesome - i love it.

**Comment by mbraak** [comment]
Hello,

Are you loading the data directly using the [data](https://mbraak.github.io/jqTree/#options-data) option? Or are you loading the data from a url using [dataUrl](https://mbraak.github.io/jqTree/#options-data-url)?

Greetings

**Comment by edwardsmarkf** [comment]
data option, from a HUGE object, like a quarter million "children" over four levels.

my issue is how long it takes to display the tree.  so i am thinking just do the first level or two and the most current stuff, then fire off a "setTimeout" set at 500 milliseconds to[ fill in the rest.](https://mbraak.github.io/jqTree/#functions-updatenode)  that way, the users can start using it right away, and the less-relevant stuff can[ fill in asynchronously.
](https://stackoverflow.com/questions/9516900/how-can-i-create-an-asynchronous-function-in-javascript)

**Comment by mbraak** [comment]
If you use the `data` option to load the data, then you don't need the `tree.init` event. The tree is initialized after you call `.tree`:

```js
$('#tree1').tree({ data: my_data );

// the tree is now initialized
```

Note that if you have so much data, then you could also use load-on-demand: see [this example](https://mbraak.github.io/jqTree/examples/05_load_on_demand/). If you want to use this, you must load the data from a url.

**Comment by lichnow** [comment]
I have the same problem,when i initialized the tree i need to bind some function and css class for every `li` element,but init event not work if i use data option

**Comment by mbraak** [comment]
What you can do is: bind the init event first, then initialize the tree:

```js
$('#tree1').bind('tree.init', function() { console.log('init'); });

$('#tree1').tree({ data: my_data );
```

Now the handler for the tree.init event will be called.
