### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by mdurovni** [mbraak/jqTree#497]
Hi Marco,

Many thanks for your work, It realy helped me.

I am working with a file tree and jqtree reads the directorys and files correctly and I set it to show the file path so I can open the files. I wonder if there is any way to customize jqtree to do the following:

1) Does not show path for directorys 
2) For files omit the name and show files paths.

My tree looks like this (I don't know if you will be able to see it:

![image](https://user-images.githubusercontent.com/11097483/28594122-29451e4a-7165-11e7-94ff-8d0b816fad99.png)

**Comment by mbraak** [comment]
Hello,

I see that you have already customized the html rendering. Are you using [onCreateLi](https://mbraak.github.io/jqTree/index.html#options-oncreateli) for that?

Greetings

**Comment by mdurovni** [comment]
Hi Marco,

Yes I have, but I solved this with autoEscape set to false and sending an anchor tag. Now the problem is that the files don't open. Do I need some extra code to open an file?

My new tree is like that, the files are in blue, directorys (folders) in black with an icon.

![image](https://user-images.githubusercontent.com/11097483/28618425-bc4984cc-71da-11e7-8740-79d14aa22df9.png)

**Comment by mbraak** [comment]
I see, you used autoEscape. That is indeed a simple solution.

You say that the file nodes do not open. Do the file nodes have child nodes, then?

**Comment by mdurovni** [comment]
Hi Marco,

Many thanks. It was not opening because de url was wrong. I fixed and it is beautiful. 
Many thanks again.

**Comment by mbraak** [comment]
I'm glad that it works. Closing the issue.
