### ISSUE TITLE
How to get data json from constructed tree

### ISSUE THREAD

**Issue by swapniladsure** [mbraak/jqTree#498]
Hello,
I would like to get tree json and i want to store it into database for future use.
How can i get JSON from currently constructed tree?
Thank you

**Comment by mbraak** [comment]
Hello,

You can get the tree using the [getTree](https://mbraak.github.io/jqTree/#functions-gettree) function.

```js
var tree_data = $('#tree1').tree('getTree');
```

The result is a javascript data structure.
