### ISSUE TITLE
DragAndDrop issue

### ISSUE THREAD

**Issue by tomato4** [mbraak/jqTree#499]
Hello,
I have one problem. When I add DragAndDrop.js 
(containing this: `var $tree = $('#tree1');
$tree.tree({
  dragAndDrop: true,
  autoOpen: 0
});`)
it completely stops working. (on website I can see, that the tree isn't generated)
![vystrizek23](https://user-images.githubusercontent.com/26723812/28944459-e96a4f9e-78a2-11e7-957f-8c0e7bc62e21.PNG)
Do you know what is wrong?

**Comment by tomato4** [comment]
Ou I solved it 😄 ... I have changed default settings
![vystrizek24](https://user-images.githubusercontent.com/26723812/28944749-fa2d7bfc-78a3-11e7-88b5-a2d5bfca0ab4.PNG)
But why it doesn't work with normal way?

**Comment by mbraak** [comment]
That's strange. It does work in the [drag and drop example](https://mbraak.github.io/jqTree/examples/03_drag_and_drop/).

**Comment by tomato4** [comment]
Yes it does... Have you tried to download script from website, create html, data etc. and create draganddrop script? (If it works then mistake is on my side if not then in JavaScript...)

**Comment by tomato4** [comment]
So I have tried it again... It works and I don't know why. :)
