### ISSUE TITLE
Problems with function

### ISSUE THREAD

**Issue by tomato4** [mbraak/jqTree#500]
Hi again,

so there are problems not only with DragAndDrop (as I said in last Issue). When I use for example AddNodeAfter or removeNode it doesn't work. 
![vystrizek25](https://user-images.githubusercontent.com/26723812/29032912-84880a64-7b93-11e7-8014-4246a0391605.PNG)

**Comment by mbraak** [comment]
Hello,

You get this error if the second parameter of addNodeAfter is null:

```js
// WRONG: existing_node is null
$tree.tree('addNodeAfter', node, null);

// WRONG: existing_node is null
$tree.tree('addNodeAfter', node);

// WRONG: existing_node is undefined;
var existing_node;
$tree.tree('addNodeAfter', existing_node);
```

**Comment by tomato4** [comment]
Ou I think that I know where I have mistake... I will try it.
But for removeNode - it doesn't drop error, but it only refresh tree. To parameter I gave `$(this).parent().parent().parent()` which refers to this `<li class="jqtree_common jqtree-folder jqtree-closed" role="presentation">` is it alright or it should be something diferent (e.g. Div)?

**Comment by mbraak** [comment]
That doesn't work because `$(this).parent().parent().parent()` returns a jquery element, and `removeNode` only accepts tree nodes.

One way to get a tree node is by using [getNodeById](https://mbraak.github.io/jqTree/#functions-getnodebyid):

```js
var node = $tree.tree('getNodeById', 10);

$tree.tree('removeNode', node);
```

**Comment by tomato4** [comment]
So, thanks - creating node works (I haven't define node1).
But deleting still won't work. Here is a code: 
`var $tree = $('#tree1');
var node = $tree.tree('getNodeById', 3);
$tree.tree('removeNode', node);`
Is it alright?
And I have one another question - In data.js I have IDs (`name: 'node1', id: 1,`...). Is there a way to write these IDs into html element (into div's attribute)?

**Comment by mbraak** [comment]
Can you see what the node variable contains?

```js
var node = $tree.tree('getNodeById', 3);
console.log(node);
$tree.tree('removeNode', node);
```

**Comment by mbraak** [comment]
You can use [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) to add an id property.

For example, this code sets the `data-node-id` property:

```js
$tree.tree({
  data: my_data,
  onCreateLi: function(node, $li) {
    $li.find('div.jqtree-element').attr('data-node-id', node.id);
  }
});
```

Also see [this example](https://mbraak.github.io/jqTree/examples/09_custom_html/).

**Comment by tomato4** [comment]
![vystrizek26](https://user-images.githubusercontent.com/26723812/29085564-f84db4e4-7c6f-11e7-81d1-6fbc2dd40de7.PNG)

**Comment by tomato4** [comment]
So I explored code by debbuger and here is some info: it calls function removeNode -> node.remove() removes node, but then function `_refreshElements(node.parent)` add node back. why?

**Comment by mbraak** [comment]
Where do you get the node from that you want to remove? Are you using `getNodeById`?

**Comment by tomato4** [comment]
Yes. I used getNodeById and I am using. Before it doesn't work and now it works... So again I don't know where was mistake. But thanks for help.
