### ISSUE TITLE
re: #118 "selectable" option available

### ISSUE THREAD

**Issue by arminlinder** [mbraak/jqTree#502]
First of all let me thank you for you excellent library, it helped me a lot.

Quick question: in #118 you implemented a node selection toggle, if a node is selected an clicked, it is unselected, and vice versa.

Is there a quick way for me to change this, so the node does not toggle, instead it keeps the "selected" state and colour? I need a tree where one node is always selected.

(guess this is how the tree behaved before the #118 change)

Thanks very much,
'
Armin.

**Comment by mbraak** [comment]
I think that's possible. I will have a look at it.

**Comment by mbraak** [comment]
You can fix this using the following code:

```js
var $tree = $('#my-tree');

$tree.on('tree.click', function(e) {
    e.preventDefault();

    $tree.tree('selectNode', e.node);
});
```

Please let me know if it works.

**Comment by arminlinder** [comment]
Hi,

I built the code into my tree, and it seems to work like intended. Thanks very much, Armin.

**Comment by mbraak** [comment]
I'm glad to hear that it works.
