### ISSUE TITLE
Idea to improve - speed of animation

### ISSUE THREAD

**Issue by tomato4** [mbraak/jqTree#503]
Hi,

you have there only option to turn on/off slide animation, but I need to change speed of animation. Can you implement it to you library (code)?

**Comment by mbraak** [comment]
I'll put it on the todo list.

**Comment by tomato4** [comment]
thanks

**Comment by mbraak** [comment]
I added the `animationSpeed` option.

E.g.: 500 ms

```js
$tree.tree(
  dataUrl: '/example_data.json',
  animationSpeed: 500
);
```

**Comment by tomato4** [comment]
Have you post new .js file on site? because it won't works...

**Comment by mbraak** [comment]
The change is in the `dev` branch. The changed tree.jquery.js file is on [this link](https://github.com/mbraak/jqTree/blob/dev/tree.jquery.js).

**Comment by tomato4** [comment]
thanks!
