### ISSUE TITLE
Configure node ID parameter name for dynamic loading

### ISSUE THREAD

**Issue by aimeos** [mbraak/jqTree#504]
When using existing REST APIs, the parameter can't always be named "node". Thus, it would be great if this could be configurable like this:
```
        var data_name = this.element.data("name") || this.options.dataName || 'node';
        var data_url = this.element.data("url") || this.options.dataUrl;
        var getUrlFromString = function () {
            var url_info = { url: data_url };
            if (node && node.id) {
                var data = {};
                // Load on demand of a subtree; add node ID parameter
                data[data_name] = node.id;
                // tslint:disable-next-line: no-string-literal
                url_info["data"] = data;
            }
```
The `data_name` can be configured from a data attribute or a "dataName" configuration option in this example code (or stay as "node" as default).

Please note that also the `data-url` and `dataUrl` parts are reversed (dynamic before static configuration to be able to overwrite static config if necessary).

I would open a PR but I don't have enough experience with your build system.

**Comment by mbraak** [comment]
I think you can achieve the same using the [dataUrl](https://mbraak.github.io/jqTree/#options-data-url) option as a function. This is a bit more work, but it should achieve the same thing.

For example, this code changes the parameter to `my_node`:

```js
$tree.tree({
    dataUrl: function(node) {
        var result = {
            'url': '/my_url/',
            'method': 'post'
        }

        if (node) {
            // -> load on demand
            result['data'] = {
                'my_node': node.id
            };
        }

        return result;
    }
});
```

Also see issue #80.

**Comment by aimeos** [comment]
OK, works as well
