### ISSUE TITLE
Tree to Tree Drag/Drop

### ISSUE THREAD

**Issue by samcov** [mbraak/jqTree#505]
Is it possible to drag and drop from one tree to another?

**Comment by arminlinder** [comment]
Good question! I'm really interested too, and was upon asking this question myself.

**Comment by cybercandyman** [comment]
Yes, Good question ! I am interested too

**Comment by mbraak** [comment]
Unfortunately this is not supported. Would be a nice feature, but it would be really difficult to implement.

**Comment by mbraak** [comment]
Closing this issue. Not building this feature.
