### ISSUE TITLE
[BUG] jQuery on other alias

### ISSUE THREAD

**Issue by fauzie** [mbraak/jqTree#506]
Hello,

Im using prototype.js as main js framework, so i have global ```jQuery``` with no conflict on ```$j``` because default ```$``` owned by prototype. Unfortunately this plugin is not support for it, which is not good for the future.

Looking forward for your update.
Regards,

**Comment by mbraak** [comment]
I will look into it.

**Comment by mbraak** [comment]
The latest code uses the `jQuery` global variable instead of `$`. Please use the `dev` branch if you want to try this.

**Comment by fauzie** [comment]
Looks good now, thank you for your update 👍

**Comment by mbraak** [comment]
Fixed in version 1.4.4
