### ISSUE TITLE
Setting a max level of nodes

### ISSUE THREAD

**Issue by irvize** [mbraak/jqTree#507]
Hi, is there a tree option that can be used to set a max node limit, E.g., I only want to allow my tree to have a maximum of 3 levels?  Might have been asked before but can't find it in your documentation or previous closed issues. 

If no tree option exists, what's the best way to do this?

Your help is very much appreciated.

Cheers,
Iain

**Comment by tomato4** [comment]
Hello, try something with "getLevel" function. You will create new node (or move node) and then use getLevel and if the level is higher that you want to, return changes (so for move you should somehow save location and if the level will be higher you make script to move it back). You can invent something better with "getLevel". This is my idea how I would solve it.

**Comment by irvize** [comment]
Many thanks for this, I combined the tree.move event with the getLevel function like this (where bookmarkTree is my tree):

		$('#bookmarkTree').bind(
				'tree.move',
				function(event) {				    
					var level = event.move_info.target_node.getLevel();		
					if (level >= 4){
						alert('Unable to add further folder levels');
					}
				}	
		);

Currently trying to find out how to stop the move happening if we reach level 4.

Thanks again for your suggestion, very much appreciated.

**Comment by tomato4** [comment]
Happy to hear that.
this maybe you can solve by function "moveNode". Try to write this function into your "if" for level and into target_node write "event.move_info.previous_parent"... I don't know how it will react, but it might work.

**Comment by irvize** [comment]
Solved my issue by using onCanMoveTo:

				onCanMoveTo: function(moved_node, target_node, position) {
					// don't allow more than 3 folders deep on the tree.
					if (target_node.getLevel() == 4) {
						return false;
					}
					else {
						return true;
					}

Seems to work but would be nice to have a maxLevel (or similar) tree option that can be set.

Thanks again for your help. very much appreciated.
