### ISSUE TITLE
Horizontal autoscroll

### ISSUE THREAD

**Issue by thk-risma** [mbraak/jqTree#508]
I have some custom CSS on the nodes which makes them wider and in some cases adds an horizontal overflow. My problem is, that I can only see autoscoll on the vertical axis and nothing happens when I drag to the end of horizontal axis. 

Thank you for a great plugin :-)

**Comment by mbraak** [comment]
I would like to reproduce this. Could you share some of the css that you use?

**Comment by thk-risma** [comment]
A simple test could be like this: 
Set you ul.jqtree-tree ul.jqtree_common {margin-left:300px} in your Example 7 - autoscroll

When you drag on the horizontal axis, it does not autoscroll.

**Comment by thk-risma** [comment]
Here a preview of my tree with custom CSS. 
![jqtree-custom-css](https://user-images.githubusercontent.com/17592567/33169038-5995259e-d043-11e7-9c1f-8da7cafbd019.jpg)

**Comment by mbraak** [comment]
I can reproduce the error. I will look into it.

**Comment by mbraak** [comment]
I added support for horizontal scrolling to the `dev` branch.

I tested it with the autoscroll example. Please let me know if it works in your situation.

**Comment by mbraak** [comment]
Fixed in version 1.4.4
