### ISSUE TITLE
Search tree from textbox value

### ISSUE THREAD

**Issue by shahsumit** [mbraak/jqTree#509]
Hi, 

Have implemented the search functionality on keyup of an text box as below:

```
$('#txtSearchField')
        .keyup(function() {
            var searchterm = $(this).val();
            var $tree = $('#tree1');
            var tree = $tree.tree('getTree');
            tree.iterate(
                function(node) {
                    if (node.name.indexOf(searchterm) == -1) {
                        return true;
                    } else {
                        $tree.tree('selectNode', node, true);
                        return false;
                    }
                }
            );
        });
```

Am facing two issues with the above implementation:
1) The movement am typing a word in the search box the focus is lost. so if I need to type multiple words, I need to every time select the search box and type letters
2) Upon search the tree should only contain nodes and child nodes related to the search words, so basically the tree should always dynamically bind based on the search keywords.

Posting the answer with relevant examples would be very helpful.

**Comment by mbraak** [comment]
Have you seen issue #230? It contains some examples for searching.

**Comment by shahsumit** [comment]
Thank you for the hint. I was able to figure out how to rebind the tree based on the search. below is the code snippet:

$('#txtSearchField').keyup(function () {
        clearTimeout(thread);
        var searchVal = $(this).val();
        if (searchVal.trim().length) {
            var tempData = [];
            var _outputData = jQuery.extend(true, {}, outputData);

            _.each(_outputData,
                function(parent) {
                    var match = _.filter(parent.children,
                        function(child) {
                            return (child.name.toLowerCase().indexOf(searchVal.toLowerCase()) > -1);
                        });
                    var parentObj = parent;
                    parentObj.children = match;
                    if (match.length)
                        tempData.push(parentObj);
                });
            thread = setTimeout(function() {
                    $('#FieldTree').tree('loadData', tempData);
                },
                1000);
        } else {
            $('#FieldTree').tree('loadData', outputData);
        }
    });

You can close this issue. Thank you for your quick response.

**Comment by mbraak** [comment]
Thanks. Closing the issue.
