### ISSUE TITLE
Make the `tree()` function return a promise

### ISSUE THREAD

**Issue by lenormf** [mbraak/jqTree#512]
Hi,

It'd be convenient to have the `tree()` function return a promise similar to the one provided by [the jQuery.ajax() function](http://api.jquery.com/jQuery.ajax/#jqXHR), with a `done()`, `fail()` and `always()` callback, instead of hooking specific events.

Thanks.

**Comment by mbraak** [comment]
Hello,

I don't want to change it, because that will break existing code. At this moment the `tree` functions returns the jQuery object, and code might depend on that.

Greetings,

**Comment by lenormf** [comment]
Could the `tree()` function take a promise object as optional parameter then, and execute whatever callbacks are set in it? It could be ugly, but it certainly would be convenient.

**Comment by mbraak** [comment]
I think it would be better to write some function that initializes a tree and returns a promise. But this should not be part of  jqTree in my opinion.

Calling the function could be something like this:

```js
initTree(
  $('#my-tree'),
  { dataUrl: '/example_data' }
).then(
  $tree => {
    // the data is now loaded
  }
).catch(
  () => {
    // could not load the data
  }
);
```

**Comment by lenormf** [comment]
The problem with that example is that I need to implement a function that wraps a tree function and hooks events - all manually. It would be easier if `tree()` triggered a callback itself once the function has been executed.

**Comment by mbraak** [comment]
I'm closing this issue. There are no plans to support this.
