### ISSUE TITLE
Prevent mouseover event from running while tree.move is running.

### ISSUE THREAD

**Issue by irvize** [mbraak/jqTree#514]
Hi all,

I have an issue where I have a mouseover event that displays a tooltip. When moving an item on the tree fast enough, I can get the mouseover event to run for another item while I still have the tooltip displaying for the item I'm moving.

I now have two tooltips. If I let go of the mouse click when the second tooltip is open, it will not go away. I have to log out of my application to get rid of it.

So, I'd like to prevent the mouseover even from running if I am in the middle of moving an item on the tree.

Is there a way to do this? Or a better way to display tooltips that would prevent this? 

Thanks in advance for your help.

**Comment by mbraak** [comment]
Hello,

There is an `isDragging` function that returns  `true` when a node is being moved. Perhaps you can use this function in your tooltip code.

 ```js
const is_moving = $('#tree1').tree('isDragging');
 ```

Note that this function is not documented at this moment. I will add it to the documentation.

**Comment by irvize** [comment]
Thank you, will give this a try.

**Comment by mbraak** [comment]
Closing the issue
