### ISSUE TITLE
label changes to name

### ISSUE THREAD

**Issue by Phrantiques** [mbraak/jqTree#519]
Server object has "label" field, when i pass data to the tree, on "onCreateLi" callback im receiving changed node, instead of "label" it has a "name" field.

**Comment by mbraak** [comment]
Yes, sorry about that. This is a feature to support legacy code. It's better to use `name` for new code.

**Comment by Phrantiques** [comment]
Okay, thanks for reply.

**Comment by Phrantiques** [comment]
PS U made a very nice tool, it helped me a lot, ty
![AI Editor](https://user-images.githubusercontent.com/12500524/36466477-82d1ea48-16eb-11e8-8268-086e45a91222.png)

**Comment by mbraak** [comment]
closing the issue
