### ISSUE TITLE
Close all opened nodes

### ISSUE THREAD

**Issue by Costegillio** [mbraak/jqTree#521]
Greetings!

How to close all opened nodes?

Plugin is awesome, thanks!

**Comment by mbraak** [comment]
I think this is possible. I will see if I can make a code example.

**Comment by mbraak** [comment]
I think this is the easiest way to close all nodes:

```
var $tree = $("#tree1");

var root = $tree.tree("getTree");

root.iterate(function(node) {
    $tree.tree("closeNode", node);
    return true;
});
```

Please let me know if this works.

**Comment by Costegillio** [comment]
Works like a charm, though.

Thanks a lot!
