### ISSUE TITLE
Handling empty results from AJAX call

### ISSUE THREAD

**Issue by rhys-stubbs** [mbraak/jqTree#522]
Reading through the documentation I cannot seem to find a way to handle empty results from an AJAX call, my request is returning a 204 as it was valid, however, no data was found to return. Any reasonable suggestions?

**Comment by mbraak** [comment]
I will have a look at this. How should a 204 status be handled? Should it ignore the request?

**Comment by rhys-stubbs** [comment]
I don't think the request should be ignored, it should definitely be handled, it's not very helpful for it to fall over when there's nothing to return. If there was an event that was fired if data is null/empty that'd probably solve it, or if the response was exposed so we could handle it in whatever way we see fit. The first is probably my preferred! I has half expecting there to already be this functionality and I had missed it in the docs, but since it doesn't exist, I will have a look into the source and if I come up with a nice fix; I will submit a pull request for it.

**Comment by mbraak** [comment]
The tree fires the `tree.load_data` callback when the data is loaded. The feature is undocumented at this moment.

```js
$('#tree').on('tree.load_data', function(e) {
  // e.tree_data contains the data 
});
```

**Comment by rhys-stubbs** [comment]
Ok that could work as a temporary fix, I'd rather not have to perform logic on the data myself though.

I was literally just looking through the source and I was thinking, within the `handleSuccess` function; test if the response is an empty object. If that returns as true then return a new event "tree.empty"? 

Picking up the empty response here would stop any further parsing etc on the data which clearly doesn't exist?

`const handleSuccess = (response: any) => {

            if(jQuery.isEmptyObject(response) || isNull(response)) {
                removeLoadingClass();
                return this._triggerEvent("tree.empty");
            }

            const data = filterData(getDataFromResponse(response));

            handeLoadData(data);
        };`

**Comment by mbraak** [comment]
I think an event for an empty tree is too specific. It works in this case; but who else is going to use this feature.

**Comment by rhys-stubbs** [comment]
Yeah that's probably a fair comment, I will stick with your suggestion.

**Comment by mbraak** [comment]
ok thanks
