### ISSUE TITLE
'setOption' not work

### ISSUE THREAD

**Issue by ab18282099** [mbraak/jqTree#523]
Hi, I try to use function 'setOption' after create a tree, but it seems not work?
Thank you very much!

**Comment by mbraak** [comment]
Hello; which option are you trying to set?

**Comment by ab18282099** [comment]
I tried set 'autoOpen: true' after initial a tree with 'autoOpen: false', but not work
thanks

**Comment by mbraak** [comment]
Ah yes. Auto-open only works when the tree is initially loaded; so setting it later doen't work.

If you want to open all nodes, you could do this:

```js
var $tree = $("#tree1");
var root = $tree.tree("getTree");

root.iterate(function(node) {
    $tree.tree("openNode", node);
    return true;
});
```

**Comment by ab18282099** [comment]
great! thx!

**Comment by mbraak** [comment]
closing the issue
