### ISSUE TITLE
IS drag and drop works in hybrid mobile apps in cordova

### ISSUE THREAD

**Issue by rameshsharmaaspire** [mbraak/jqTree#524]
Hi all,

I am able to populate json as list of items but there is no drag and drop working. Can anyone update me on this. 

Implemented in cordova app with angularjs  and bootstrap.

Thanks,
Ramesh Sharma

**Comment by mbraak** [comment]
Have you set the `dragAndDrop` option to true? Also see this example: https://mbraak.github.io/jqTree/#options-draganddrop

**Comment by rameshsharmaaspire** [comment]
Yes I have set dragAndDrop option to true and using debugger also I have tested that its value is passing to plugin also...

In my controller it is defined something like this 

`$scope.treeOptions =  {
                data: $scope.treeData,
                dragAndDrop: true,
                onCreateLi: function() { },
                onCanMoveTo: function() { }
}`

Can you assure me that your plugin works well in mobile application in android or iOS in Hybrid application build with cordova or ionic.

**Comment by mbraak** [comment]
I cannot assure that to you.

**Comment by mbraak** [comment]
closing the issue
