### ISSUE TITLE
set dataUrl as object not worked

### ISSUE THREAD

**Issue by yurayko** [mbraak/jqTree#526]
$('#tree').tree({
        // (1) worked
        dataUrl: node => {
            let r = {
                'url': "/my_url/",
                'method': 'get'
            };
            if (node) {
                r['data'] = { 'node' : node.id };
            }
            return r;
        },
        // (2) worked
        dataUrl: "/my_url/",
        // (3) not worked
        dataUrl: {
            url: "/my_url/"
        },
    });
(3) generate request always for root tree, without  "node" request parameter
2018-04-26T10:04:31+03:00 127.0.0.1 method=GET, uri=/my_url/?_=1524726271220, status=200
It is OK?

**Comment by mbraak** [comment]
Fixed. This is now included in the `dev` branch.

**Comment by yurayko** [comment]
Thanks
