### ISSUE TITLE
All nodes are open at start with autoOpen: false

### ISSUE THREAD

**Issue by vesperon51** [mbraak/jqTree#527]
All the nodes appear open but with the symbol of being closed.

I have tried to set autoOpen: false and expand_selected_onload: false but the result is the same.

Here my JSON: `[
    {
        "name": "CACO2",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "test5",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "799",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "ay",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "test3",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "test34",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "dadadawda",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "test2",
        "children": [
            {
                "name": "dev"
            }
        ]
    },
    {
        "name": "DIPL2",
        "children": [
            {
                "name": "dev"
            }
        ]
    }
]`

And here my init tree function
`function loadjqTree() {
    $.getJSON(
        '/dir',
        function (data) {
            $('#tree').tree({
                data: data,
                expand_selected_onload: false,
                autoOpen: false
            });
            console.log(JSON.stringify(data));
        }
    );

}`
Image: https://ibb.co/jL3oVd
Thanks

**Comment by mbraak** [comment]
It looks like the `jqtree.css` file is not correctly loaded.

The css file is here: https://mbraak.github.io/jqTree/jqtree.css Also see the tutorial: https://mbraak.github.io/jqTree/#Tutorial

**Comment by mbraak** [comment]
I hope this works now. Closing the issue.
