### ISSUE TITLE
what's the mean of $tree

### ISSUE THREAD

**Issue by johnhan1** [mbraak/jqTree#528]
When i copy your code like this:
var parent_node = $tree.tree('getNodeById', 123);
$tree.tree(
    'appendNode',
    {
        name: 'new_node',
        id: 456
    },
    parent_node
);
I got a error:$tree is not defined
So i want to konw what's the mean of $tree or where does this variable come from?

**Comment by mbraak** [comment]
I hope this works now. Closing the issue.
