### ISSUE TITLE
Make the "title span" toggle-able when "selectable" is off

### ISSUE THREAD

**Issue by 4wk-** [mbraak/jqTree#529]
Hello. Sorry if it's a dumb question: I'm looking for a way to make a the **title span** toggle-able.
For instance, when I click on the title span of the node, I want to toggle children, just like the button link.

I've put the **selectable** option to off, because I don't need it. 
It seems that if I add the ` jqtree-toggler` css class to the `<span>`, it work just like that. 

- Is there a native way / an option to do that behaviour? 

Or should I just stay with adding the `jqtree-toggler` class with JQuery after the tree is build like that;
`$('.jqtree-folder .jqtree-title-folder').addClass('jqtree-toggler');`

Thanks for your work.

**Comment by mbraak** [comment]
I think you can do the same with the following code:

```js
var $tree = $('#example-tree');

$tree.on('tree.click', function(e) {
  $tree.tree('toggle', e.node);
});
```

**Comment by 4wk-** [comment]
Indeed, that work too. I don't know what is the best, but I tend to prefer my one line / global solution without having to specify the tree. But it's good to know!

Any chance one day you guys can create a **Tree Option** for this? (a)

**Comment by mbraak** [comment]
Closing the issue
