### ISSUE TITLE
Prevent default tree.click event and call it later

### ISSUE THREAD

**Issue by Costegillio** [mbraak/jqTree#530]
Greetings!

How to prevent default tree.click event inside it and call it later?

I have code like this:

```
tree.on('tree.click', function(e){
	if () {
		//call default event
	} else {
		//do some stuff
	}
});

```

Many thanks!

**Comment by mbraak** [comment]
Hello,

You can prevent the default behaviour using `e.preventDefault()`. The default event is to the select the node; you can do that using `selectNode`.

```js
tree.on('tree.click', function(e) {
  e.preventDefault();

  if () {
    tree.selectNode(e.node);
  }
});
```

By the way, there is no other way to call the default event. But `selectNode` is exactly the same as the default event.

**Comment by Costegillio** [comment]
@mbraak, thanks you!

After calling `selectNode` it doesn't toggle back (deselect) so the way is: check if this node selected and call `selectNode` with empty brackets to deselect node. Am i right?

**Comment by mbraak** [comment]
That should work. You can also use the [toggle](https://mbraak.github.io/jqTree/#functions-toggle) function

**Comment by Costegillio** [comment]
@mbraak, thanks again and good luck!
