### ISSUE TITLE
updateNode does not trigger tree refresh

### ISSUE THREAD

**Issue by TivoSoho** [mbraak/jqTree#531]
The updateNode method works as intended - it updates the node info. However it does not trigger a refresh event for the tree.

**Comment by mbraak** [comment]
This is now fixed. The fix is in the `dev` branch

**Comment by TivoSoho** [comment]
Thank you but we are using it via composer, so github branches are unfortunately not applicable. Is there a way to trigger it manually ourselves? It would be great otherwise as well to have this feature - manual refresh triggering. Or possibly the only workaround is to append a dummy element and remove it immediately after?

**Comment by mbraak** [comment]
Yes, I think the only workaround at this moment is to append and remote a dummy element.

I will see if I can release a new version soon.

**Comment by mbraak** [comment]
I have released new npm and bower versions (1.4.7). I have no control over composer packages.

**Comment by mbraak** [comment]
Closing the issue
