### ISSUE TITLE
API for applying css to tree nodes

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#534]
Hi,

Are there APIs for applying custom CSS style for nodes that we'd like to differentiate based on application criteria? 

Example, group of patients' vitals are put into the tree and we'd like to highlight a few nodes based on criteria (like, invalid values, high or too low values etc.)

**Comment by mbraak** [comment]
Hello,

You could use the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option to add a css class to the node:

```js
$tree.tree({
  data: tree_data,
  onCreateLi: function(node, $li) {
    $li.addClass('test-value');
  }
});
```

Note that the `node` refers to a node to your own tree_data; so you can also check for values in your data:

```js
$tree.tree({
  data: tree_data,
  onCreateLi: function(node, $li) {
    if (node.patient_vitals) {
      $li.addClass('test-value');
    }
  }
});
```

Also see [this example](https://mbraak.github.io/jqTree/examples/09_custom_html/)

I hope this answers your question.

**Comment by 767267** [comment]
Thanks, that will help.
