### ISSUE TITLE
Deferred loading on certain tree nodes where the data is huge

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#535]
Looking for internal mechanism that I can use to have a deferred loading and also pagination on the tree node's children when the data is huge

1. Indication of the children count can be provided upfront (example 2000) and the page size (example 50) so the node knows that it has to load only 50 at the start 
2. Extra nodes are loaded on demand (example on click of some "..more" label extra which would be displayed at the end of per page 

UI mockup

+ Root
     + child 1
     + child 2
     + child 3
     + child 4
      ...more

On click of that "...more" t loads next 4 and so on

**Comment by mbraak** [comment]
JqTree does not support pagination. The closest thing is the load-on-demand feature; but that's not the same thing as pagination. Please see [this example](https://mbraak.github.io/jqTree/examples/05_load_on_demand/)

**Comment by 767267** [comment]
OK, thanks. Any plan on adding "..more" (twitter type pagination). If would really help.

**Comment by Schnierle** [comment]
I don't think this feature should be integrated directly into jqtree. For me, this is clearly an application-specific extension to the use of the library. We should focus more on jqtree providing the interfaces (like @mbraak explained) to solve such problems. For me, jqtree won in a technology selection because it has clear interfaces and is not overloaded with such features like other libs.

**Comment by mbraak** [comment]
I agree with the previous comment. I prefer to put as little as possible in jqtree itself. So, I'm not planning to add this feature to jqtree.

On the other hand, it's probably difficult to add this function in your application code.

**Comment by 767267** [comment]
OK, I see what you are trying to say here and thanks. I feel it's a very generic problem for any data bound control.

Now, I'll try to see if I can do it myself because the data we load is at time just too much.
