### ISSUE TITLE
Auto multiple selection and alternate selection

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#536]
Hi,

Just working with the latest version. I found an issue where the click event seems to behave differently. i.e. on click on tree nodes, the selection css appears on alternate click and the last selection does not get removed. Hence it feels like multiple nodes are selected. Although multiple selection is not enabled in the code.

here is the initialization code:

this.tree = this.$dom.tree();		
this.tree.ParentView = this; //  here 'this' the wrapper function
this.tree.bind( 'tree.click', this.treeNodeClick.bind(this));
this.tree.bind( 'tree.dblclick', this.treeNodeDblClick.bind(this));

//click event handler
treeNodeClick : function(event) {
	Log.info('TreeView:click ' + event.node.name);
// this below routine is to invoke my code on node click
	var eventOnLinkClickHandler = this.getEventObj("ontreenodeclick");
		if(eventOnLinkClickHandler) {
			this.messageMap.set("TreeNodeName", event.node.name);
			this.messageMap.set("TreeNodeId", event.node.id);
			eventOnLinkClickHandler.run();
		}
},

Please check the image for understanding, I had clicked on nodes > OxfordHip > LabOrders > KOOSPS > ICHOM_LPC > ICHOM ...

You can see that all alternate items are not showing the selection style + the old selection on nodes are still visible.

![treeview](https://user-images.githubusercontent.com/13524673/41775570-f5572686-7641-11e8-9468-65ac31598542.PNG)

**Comment by mbraak** [comment]
Hello,

That's strange. I cannot reproduce this error.

If you remove the code for binding the `tree.click` event, does it behave differently?

This could also happen if your have duplicate node ids.

**Comment by 767267** [comment]
Hi,

Altered code:
this.tree = this.$dom.tree();		
		this.tree.ParentView = this;
		//this.tree.bind( 'tree.click', this.treeNodeClick.bind(this));
		this.tree.bind( 'tree.dblclick', this.treeNodeDblClick.bind(this));

The result is the same, first 4 child nodes were clicked in an order of top to bottom

![treeview2](https://user-images.githubusercontent.com/13524673/41788308-dc55224c-7668-11e8-8ef8-d4b3ea726be0.PNG)

**Comment by 767267** [comment]
I guess the other point you mentioned is correct, my "id" value was going in as NaN which was causing that issue. 

So, I was able to fix the issue. Thanks.
