### ISSUE TITLE
SVG xlink as openedIcon/closedIcon disappear after click

### ISSUE THREAD

**Issue by terryoy** [mbraak/jqTree#537]
Hi, sorry to bring up an old issue. 

https://github.com/mbraak/jqTree/issues/489

I didn't test fully because I had a workaround for this issue and  was moving on another task.

Now I came back to the component and reviewing this solution again, and find out that we ignored two lines to fix.

https://github.com/mbraak/jqTree/blob/1.4.2/src/node_element.ts#L88
https://github.com/mbraak/jqTree/blob/1.4.2/src/node_element.ts#L131

When the folder toggler is clicked and trigger the open/close method, they both did the shallow clone again and thus I lost the icon's "xlink" content.

Should have change to `true` again.

**Comment by mbraak** [comment]
This is now fixed in the `dev` branch.

**Comment by terryoy** [comment]
Confirm problem solved. Thanks!

**Comment by mbraak** [comment]
I'm glad to hear that it works. Closing the issue.
