### ISSUE TITLE
Looking for an event like OnNodeAdded

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#540]
Hi,

I have to load data recursively in the tree (but in a very on-demand and safe way) and hence I am looking for an event to hookup for OnNodeAdded, so that when I call "appendNode" or "addXXX" methods I'd like get an indication (via event) so that I can get better control on the loading of other child nodes.

If there is any possible way currently to get that indication of new node being added to the tree, please do let me know. Thanks.

**Comment by mbraak** [comment]
Hello,

There is no `OnNodeAdded` event.

Have you seen the load-on-demand feature? Example is here: https://mbraak.github.io/jqTree/examples/05_load_on_demand/

Perhaps that could work in your situation?

Greetings

**Comment by mbraak** [comment]
Hello

I think you can use the [dataUrl](https://mbraak.github.io/jqTree/#options-data-url) option for that. It allows you to change the request when dat is loaded.

Also see https://github.com/mbraak/jqTree/issues/237.

Greetings

**Comment by 767267** [comment]
Thanks, the dataUrl does not work for me as I don't have json url based data binding, we have a custom framework where data fetch actions are already in place giving out xml structures. 

For now I have implemented custom code after the appendNode() api call, so that my recursive code and be triggered within it.
