### ISSUE TITLE
Looking for openNode + autoOpen on child nodes

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#541]
Hi,

Looking for a way to achieve openNode(node, openAllChild: true), so that I can tell the api to autoOpen all the child node. Also this should be possible for the whole tree (if I pass the root node).

Similarly, it should be able to closeNode(node, closeAllChild: true).

Please do let me know how I can achieve that, I was expecting there is an API for it, but the openNode just expands the currently selected node 1 level deep, not beyond it.

**Comment by mbraak** [comment]
Hello,

You can do something like this:

```js
function closeNodeAnChildren(node) {
    $tree.tree("closeNode", node);

    node.iterate(function(node) {
        $tree.tree("closeNode", node);
        return true;
    });
}

const node = $tree.tree("getNodeById", 3);

closeNodeAnChildren(node);
```

I will see if I can add a parameter for this.

Greetings

**Comment by 767267** [comment]
Thanks, that works as expected.
