### ISSUE TITLE
Customizing Node selection color and text properties

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#542]
Hi,

I'd like to theme the tree to the application's color scheme, hence I am looking for properties that I can set to theme it, so that I can change the node selection color and the node text properties like font, size, etc.

**Comment by mbraak** [comment]
Hello,

You could perhaps use the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option and do the rest with css. Also see [this example](https://mbraak.github.io/jqTree/examples/09_custom_html/).

**Comment by mbraak** [comment]
Note that `onCreateLi` is called when you update a node:

```js
var node = $tree.tree('getNodeById', 123);

$tree.tree('updateNode', node, { id: 123, name: 'node1', exampleProperty: 'abc' );
```

Then you could use `onCreateLi` to add a class:

```js
onCreateLi: function(node, $li, is_selected) {
  if (node.exampleProperty === 'abc') {
    $li.addClass('my-css-class');
 }
```

**Comment by 767267** [comment]
Thanks. I'll see if this works.
