### ISSUE TITLE
Can 'getNodeByCallback' be used to search the tree nodes?

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#543]
Hi, 

It is not very clear to me as to what the event 'getNodeByCallback' can be used for, though, I am in need to write some logic to search within the tree nodes (search on caption) and then scroll to that tree node if found. 

Can 'getNodeByCallback' be helpful in achieving the task above? If not, please do guide on how to search and scroll to the found node.

I think I see that I can use 'scrollToNode' to get to the intended node, but want to make sure how to search.

**Comment by mbraak** [comment]
Hello,

The `getNodeByCallback` is for finding a single node using a callback. The example code for `getNodeByCallback` shows how to search for a node by name.

The other useful function would be [scrollToNode](https://mbraak.github.io/jqTree/#functions-scrolltonode).

Greetings

**Comment by 767267** [comment]
Thanks that helps.
