### ISSUE TITLE
scrollToNode does not work as expected 

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#546]
Hi,

I have tried to use "getNodeByCallback" function to perform a search.  Here is the code snippet 

SearchTreeNode.prototype.invoke = function SearchTreeNode_prototype_invoke(readyHandler) {
	if(this.searchText)
	{	
	console.log('SearchTreeNode:' + this.searchText);	
	var node = this.tree.tree('getNodeByCallback', function(node) {
		  if (node.name == this.searchText) {
		  console.log('SearchTreeNode comparing "' + this.searchText + '" with node.name[' + node.name + ']');
		  // Node is found; return true
		  return true;
		  }
		  else {
		  // Node not found; continue searching
		  return false;
		  }   } );
		if(node) {
			console.log('SearchTreeNode: node found' + node.id);
			this.tree.tree('scrollToNode', node);
		}
    }	
    readyHandler();
}

you can ignore the bits which are not relevant, but please check the part from "var node... " because that is how the documentation says to use the api. I added console logs to show how the execution goes

![image](https://user-images.githubusercontent.com/13524673/43519960-ee3b3360-95ae-11e8-9117-d61fa6456768.png)

Here is the tree that I am searching on:

![image](https://user-images.githubusercontent.com/13524673/43519994-07b2d6ae-95af-11e8-9fe5-ec476be27d38.png)

Looking at the console logs I feel the API is not even getting invoked. Please let me know if the call is made incorrectly. Thanks.

**Comment by 767267** [comment]
Sorry, my bad, it was variable scope issue. I have fixed that part, the search works fine. Although the scrollToNode API does not seems to be working. 

![image](https://user-images.githubusercontent.com/13524673/43536091-595066a0-95d9-11e8-80e9-7d6aac16b56f.png)

Even after hitting scrollto api with the node with id 16 the tree remains in the same state. It does not expand and goto node with id 16
![image](https://user-images.githubusercontent.com/13524673/43536153-8223225c-95d9-11e8-9e4f-f1b7b57c9bae.png)

**Comment by mbraak** [comment]
Hello,

If scroll doesn't work, it could be a css problem. The tree should be in a scrollable container.

Also see the [autoscroll example](https://mbraak.github.io/jqTree/examples/07_autoscroll/). It doesn't use the `scrollToNode` function, but does have css for a scrollable container.

I will check the `scrollToNode` function and post some example code.

**Comment by 767267** [comment]
Hi,

Yes, the tree container div is made scrollable as documented. 

![image](https://user-images.githubusercontent.com/13524673/43564497-a81bec58-9644-11e8-84ec-b0c2d28b94ff.png)

**Comment by mbraak** [comment]
Hello,

I noticed that `scrollToNode` only works if a node is opened. It worked when I first called this code:

```js
$tree.tree("openNode", node.parent);
```

**Comment by 767267** [comment]
Hi, 

I tried openNode on parent as well as same node, it still did not scroll to that found node.

**Comment by mbraak** [comment]
Hmm, that's unfortunate.

There is perhaps one other solution: using `selectNode`. Because that will set the focus to the selected node; and that will cause the browser to scroll to that node.

```
$tree.tree('selectNode', node);
```

**Comment by 767267** [comment]
Yes, that helps. Thanks.

**Comment by 767267** [comment]
Sorry, the selectNode gave an impression as it worked, but it did not, when the tree has a scrollbar and if I find a node towards the bottom, it does not scroll to it.

**Comment by mbraak** [comment]
I tried `selectNode` with the `autoscroll` example. That seems to work.

**Comment by 767267** [comment]
Hi there,

Please see the attached video to understand what I experience.


[Video 8-3-2018 12-16-35.zip](https://github.com/mbraak/jqTree/files/2256310/Video.8-3-2018.12-16-35.zip)

Code:
function ScrollToNode(tree, node) {
	if(tree) {
		if(node) {
			console.log('Scroll to id: ' + node.id);
			tree.tree('selectNode', node);
			//tree.tree('scrollToNode', node); //tried even with un-commenting this line still same
		} else {
			console.log('Error: TreeView.ScrollToNode node was null');
		}
	} else {
		console.log('Error: TreeView.ScrollToNode tree was null');
	}
}

I experience that it does select the node but does not scroll to it, I have tried this with scollToNode api in combination with selectNode too.

**Comment by mbraak** [comment]
I have seen the video. I don't understand why the scrolling doesn't work in this situation.

**Comment by mbraak** [comment]
I see that you have a search field that has the focus. Perhaps that is the reason why the scrolling doesn't work. The browser scrolls automatically to an input that has the focus.

**Comment by 767267** [comment]
Any suggestion or advice, what conditions are necessary on the node and tree so that the scroll works.

**Comment by mbraak** [comment]
You could debug the `scroll handler` code. It's in https://github.com/mbraak/jqTree/blob/master/src/scroll_handler.ts.

An interesting function is the `initScrollParent` function. It should find the correct `$scroll_parent` element.

An alternative is to add some logging code.

**Comment by 767267** [comment]
Hi, 

To continue on this topic, I did add some logs (in scroll_handler.ts and .js) in the method initScrollParent, strangely the log statement is never seen on the console (i.e. the function seems not called)

Any idea why it would not get called?

**Comment by mbraak** [comment]
Hello,

That's strange. I expect the following:

* `jqtree.scrollToNode` calls `scroll_handler.scrollToY`
* `scroll_handler.scrollToY` calls `scroll_handler.ensureInit`
* `scroll_handler.ensureInit` calls `scroll_handler.initScrollParent` (only the first time)

**Comment by 767267** [comment]
Hi,

Just to let you know we added openNode for each parent node recursively and then the scrolling works. It see that the position calculated by scrollToNode api is not the is incorrect if the tree is not expanded.

openParent(tree, node); // we do this in the start
tree.tree('selectNode', node); //then do a select node
tree.tree('scrollToNode', node); // then the scroll to

function openParent(tree, currentNode) {
	var parent_node = currentNode.parent;
	if(parent_node) {	
					tree.tree('openNode', currentNode);	
					openParent(tree, parent_node);
	}
}

I really expect this part should be autohandled by the scrollToNode API. Let me know your view.

**Comment by 767267** [comment]
hi,

The variable `node` is the test example was a child mostly 2,3 levels deep. So, what I found was that the scroll height calculated (without the expanded tree) was incorrect (or less than the actually height needed to scroll to when the node is visible in an expanded tree).  So, what I do is, first expand the tree in a way that the searched node is visible and then I use scrollToNode api.

**Comment by mbraak** [comment]
This code should do the same thing as the `openParent` function (in theory):

```
tree.tree('openNode', node.parent);
```
