### ISSUE TITLE
Documentation on css

### ISSUE THREAD

**Issue by 767267** [mbraak/jqTree#548]
Hi,

Is there any documentation on the packaged jstree.css, so that it can be helpful to develop some themes based on it?

**Comment by mbraak** [comment]
Hello,

I'm afraid there is no documentation for `jqtree.css`. The css is quiet straightforward, so it should not be too difficult to customize it. Also see this customization example: https://mbraak.github.io/jqTree/examples/12_button_on_right/

**Comment by mbraak** [comment]
You can use `onCreateLi` for customizing colors.

You could add a custom class:

* This would require some extra css. In this case for `shoe-category`.
* This code assumes the data contains `category` attributes. The name `category` is just an example.

```
onCreateLi: function(node, $li, isSelected) {
  if (node.category == 'shoes') {
    $li.addClass('shoe-category');
  }
}
```

If your colors are only known at runtime:

```
onCreateLi: function(node, $li, isSelected) {
  var color = '#eee';
  $li.css('background-color: ' + color); 
}
```
