### ISSUE TITLE
Inserting buttons inside

### ISSUE THREAD

**Issue by cangoktas** [mbraak/jqTree#551]
I'm trying to insert 2 buttons inside each node (delete and edit), see the screenshow below. Is there a not-ugly way to do it?
![group 15](https://user-images.githubusercontent.com/4026342/48307174-748bc580-e558-11e8-93bb-69a224775e53.jpg)

**Comment by mbraak** [comment]
You can use the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option. The function is called after rendering each node.

```js
function customCreateLi(node, $li) {
  // Insert edit link after the title
  const $title = $li.find(".jqtree-title");
  const nodeId = node.id;

  $title.after(
    `<a class="edit-node" href="/edit/${nodeId}">edit</a>`
  );
}

$('#tree1').tree({
    data: data,
    onCreateLi: customCreateLi
});
```
 
This example uses a url ('/edit/[node-id]'), but you can also handle the button in js:

```js
$('#tree1').on('click', '.edit-node', function(e) {
  // handle click
});
```

**Comment by cangoktas** [comment]
Great, thanks ✌️
