### ISSUE TITLE
Making nodes only y-axis draggable

### ISSUE THREAD

**Issue by cangoktas** [mbraak/jqTree#552]
Is there a way to make nodes draggable on y-axis so they'd be dragged only up/down? Not by functionally but also visually while dragging. Each node and the hollow node while dragging would be %100 width and the dragging node wouldn't be allowed to dragged outside the container.

**Comment by mbraak** [comment]
I'm afraid that is not supported. I think it's possible, but not without changing the source code of jqtree.
