### ISSUE TITLE
"toJson" removes empty children

### ISSUE THREAD

**Issue by dlkulp** [mbraak/jqTree#553]
Calling `.tree("toJson")` removes empty children, leaving them undefined.  So:

    $("#ex").tree({data: [
      {id:1, name:"one", children:[]},
      {id:2, name:"two", children:[
        {id:3, name:"three", children:[]}
      ]}
    ]});
    $("#ex").tree("toJson");
Would return:

    [
      {id:1, name:"one"},
      {id:2, name:"two", children:[
        {id:3, name:"three"}
      ]}
    ]
Not only is this unexpected behavior, but it causes other tree traversal code I have to have to check if children exist every time I want to do anything.  Would be less of an issue if javascript would hurry up and support null propagation.  

The biggest issue here is interfacing with other systems that are strongly typed.  Having properties randomly removed throws a bunch of errors!  The expected behavior would be to have the data retrieved show empty children `children: []` just like the data was entered or as things were moved around.

**Comment by mbraak** [comment]
I see the problem, but I can't change this behaviour without breaking external systems. 

An alternative solution is perhaps a custom `toJson` function. The original `toJson` function does something like this: 

```js
const treeData = $("#ex").tree('getTree');
return JSON.stringify(treeData);
```

You could recursively visit all the nodes in `treeData` and add an empty `children` property where needed.

**Comment by mbraak** [comment]
Cleaning op old issues. Closing.
