### ISSUE TITLE
Long item names wrap incorrectly

### ISSUE THREAD

**Issue by dlkulp** [mbraak/jqTree#554]
When the name of a node is fairly long, the text wraps in a very confusing way: 
![image](https://user-images.githubusercontent.com/1719356/50529067-1767b700-0aa7-11e9-9664-9c4489dfbf29.png)
I've tried to mark which items belong to which levels, but it's definitely not intuitive the way that text wraps.  Would be nice if everything would stay in line.

**Comment by mbraak** [comment]
I will have a look at it.

**Comment by mbraak** [comment]
I think you can fix this by adding the following css: 

```css
ul.jqtree-tree .jqtree-element {
  display: flex;
}
```

I'm testing this myself in different browsers. If it works, I will add it to the next release.

Please let me know if the `display: flex` solution works for you.

**Comment by dlkulp** [comment]
That seems to do it!  Thanks @mbraak
