### ISSUE TITLE
When tree is loaded.

### ISSUE THREAD

**Issue by ijerry** [mbraak/jqTree#556]
Hi I am using Selenium to test an App which heavily uses jqtree.

Is there an inline small piece of javascript or other that i could use to determine if the tree has presented all the items in the dropdown ?

some think like 

$('.jstree-loading').length == 0

Thanks

**Comment by mbraak** [comment]
Hello,

It adds a `jqtree-loading` class to the tree while loading.

The tree also emits a `tree.init` event when loading is finished: also see https://mbraak.github.io/jqTree/#event-tree-init . I'm not sure if you can use that in selenium.

Greetings
