### ISSUE TITLE
can i use the id to set the Highlight(css) to the node

### ISSUE THREAD

**Issue by lifebeatiful** [mbraak/jqTree#559]
now i use the id to open the node .
if the one no children node ,that is ok.

now i want when open the node,and give the node add a css to make the Highlight effect.

open node is js action, not click .

how can i should do ?

thank you~

**Comment by lifebeatiful** [comment]
i guess the code like:

`
var node = $(".nav-tree").tree('getNodeById', openId);
$(".nav-tree").tree('addClass', class);

`

is there some method to get the effect?

**Comment by lifebeatiful** [comment]
i try ,and this code is ok,but maybe not good
` $($(GlobalNode.element).children("div").get(0)).css("background-color","inherit")`

**Comment by mbraak** [comment]
You could select the node using [selectNode ](https://mbraak.github.io/jqTree/#functions-selectnode]).

```js
$(".nav-tree").tree('selectNode', node);
```

This adds a `jqtree-selected` class.

At this moment there is no `addClass` function. The problem with such a function: the tree is repainted in some situations; that would cause the `class` to disappear.

Note that custom rendering is done using the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option.

**Comment by lifebeatiful** [comment]
thank you!
