### ISSUE TITLE
Determine node moved as child or sibling

### ISSUE THREAD

**Issue by mihirpatel83** [mbraak/jqTree#560]
When I move nodes, I can get information of the moved node, target node and previous parent. Based on this I make an ajax call and change the ordering in MYSQL table.

Beds
--1
--2
TestNode

I can move "TestNode" as a child of "1"or as a sibling between "1" & "2".
Doing this it gives me Target Node in both scenario as below
Array (
            [name] => 1
            [id] => 16
            [order] => 1
            [parent_id] => 6
            [children] => []
        )

How can I determine this?

**Comment by mbraak** [comment]
The `tree.move` event contains a `position` attribute. It can be `before`, `after` or `inside`.

For example: if you move 'testnode' inside node '1', then the `position` is `inside`.

NB: the position `before` is only used if a node is moved above the root.

**Comment by mihirpatel83** [comment]
> The `tree.move` event contains a `position` attribute. It can be `before`, `after` or `inside`.
> 
> For example: if you move 'testnode' inside node '1', then the `position` is `inside`.
> 
> NB: the position `before` is only used if a node is moved above the root.

Awesome. How could I miss that? It's clearly in documentation. Thank you for reverting.

**Comment by mbraak** [comment]
Closing the issue.
