### ISSUE TITLE
Can this work on Android and other mobile devices

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#561]
Hi! This looks like amazing software. I've been testing it out a bit. Impressed.

Will it work on Mobile and Android devices?

The arrows(open/close) and the drag dropping work great on my web page. But don't seem to respond on my Android tablet or Kindle Fire(android tablet)

Thanks for any insight. Possibly something I haven't added or done wrong? Much thanks!

Or is it something I can add?

**Comment by WriterStat** [comment]
Ok I did some testing and it has to be something I/We are doing or something that our Bootstrap installation is doing. As I've gotten the demo working all by itself on both my Android tablet and Kindle Fire(android tablet). And the tree works fine on the web inside our software for us.

Which is super cool!

Since it works great on the web page for us, I'm thinking there might be something going on with either the Bootstrap CSS or JS files in our software that we are using, possible collision on Android. Knowing that though, I can track it down.

Apologize for the note. Totally on us. If you know of any collisions, we are using an older version of Bootstrap drop us a note.

Otherwise you can close this as a non-issue.

With that said, it's wonderful software! To all it works great on Android. Thanks to all.

**Comment by WriterStat** [comment]
I did some testing, turns out it's a bootstrap thing where the bootstrap modal hides behind the backdrop and doesn't have anything to do with jqTree.

jqTree works great on Android.

Which is super cool!

Apologize for the note. Totally on us. You can close this as a non-issue.

With that said, this is wonderful software! To all it works great on Android. Thanks to all.

**Comment by mbraak** [comment]
Ok thanks!
