### ISSUE TITLE
Drag Handle for items

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#562]

**Comment by WriterStat** [comment]
Hi, great software! Wondering if there is a way to create a drag handle for the items in the tree?

We'd like to make the items contenteditable on click to be able to change the item's title/text on the fly.

Also if we change the title text for an item this way will it save that state to localstorage?

We are also hoping to add a desc/note to each element/item in the tree.

Is there a better place to ask questions, if so please let us know? Apologize ahead. This isn't really an issue, but more like a feature/information request.

Thanks!

**Comment by mbraak** [comment]
Hello WriterStat,

**Desc/note**: use the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option for that. Also see [this example](https://mbraak.github.io/jqTree/examples/09_custom_html/)

**contenteditable**: use the [tree.click](https://mbraak.github.io/jqTree/index.html#event-tree-click) event for that. Note that the dom element is available via `event.node.element`. You can use that to change the dom. 

You can change a node using [updateNode](https://mbraak.github.io/jqTree/index.html#functions-updatenode). This will not save the tree to localstorage.

There is currently no public function to save the state to localstorage. The following code does the same thing: 

```js
const state = JSON.stringify($tree.tree("getState"));

localStorage.setItem("tree", state);
```

Greetings, Marco

**Comment by WriterStat** [comment]
Hi Marco thanks for the great note and software!

Lot's of cool things to try out. Thanks!

We'd like the drag handle to be just after the tree open/close icon.

We used the onCreateLi option to add new styled checkboxes to jqTree, using:

$li.find('.jqtree-title').before(newCheckBox);

Still working out the spacing/layout to get them to line up/settle in spacing next to the title text, it does perfect when there is an open/close icon to the left of a tree item, but not when there isn't. Still working on it. =)

We may need to add the open/close icon spacing to all items, but hide the open/close icon except on hover.

We'd like to place all the icons/drag handle on the left side of the tree items where the open close icon is or just to the right of the open close icon when displayed and this seems to cause a few layout things for us to address.

We quick used:

$("#tree1").on("click", function(){
        $(".jqtree-title").attr("contenteditable","true");
    });

So we'll change it to: tree.click event looks like it provides better. thx!

Looks like we can use the updateNode function for a bunch of things.

Thanks again for everything!

**Comment by WriterStat** [comment]
Hi Marco, I've created a drag and drop handle.

I needed to turn off: dragAndDrop: false to limit it to the drag and drop handle.

For the drag handle - how/what to call to start drag & drop inside jqTree on click of drag-drop handle?

It's probably in the docs somewhere, but I can't currently see it. =)

Or is there a better way? Thanks for any pointers.

Again cool software. I'll try a few things here.

**Comment by mbraak** [comment]
You can use the [onIsMoveHandle](https://mbraak.github.io/jqTree/#options-onismovehandle) option to use a custom drag-and-drop handle. The `dragAndDrop` must then be set to `true`.

**Comment by WriterStat** [comment]
Hi Marco, Thanks! Tremendous!

Apparently I either need sleep or more caffeine. =)) Drag handle is working great!

Thank You!

**Comment by WriterStat** [comment]
closing...
