### ISSUE TITLE
Open/Collapse all tree nodes programmatically after tree is open

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#564]
Hi Marco,

Open/Collapse all tree nodes programmatically.

Function? Thx.

**Comment by mbraak** [comment]
Hello,

You can do this:

```js
$tree.tree("getTree").iterate(function(node) {
    if (node.isFolder()) {
        $tree.tree("openNode", node);
        // for closing: $tree.tree("closeNode", node);
    }
    return true;
});
```

Greetings

**Comment by WriterStat** [comment]
Hi!

Cool! Thank You!

Follow up:

Is there a quick jquery/javascript way to get just a node that's clicked on?

Ex. Let's say we want to add an attribute to that node, programmatically to it. Or let's say we want to affect the title text of that node by bolding the title text on node click. For example.

Is there a quick jquery/javascript way to affect all the titles under a node that's clicked on?

Ex. Let's say we want to add an attribute, programmatically to the tree node clicked on and all the tree nodes found under it. Or let's say we want to affect the title text by bolding the title text on node click for that node and for all the node titles under it. For example.

Thanks again,

**Comment by WriterStat** [comment]
Apparently I keep trying to manipulate the tree outside of the tree code using. jQuery for some reason. =)

So understanding the above will help a lot in translation for me. Much thx!

**Comment by WriterStat** [comment]
Works great! Thx!
