### ISSUE TITLE
onDragStop not working.

### ISSUE THREAD

**Issue by techybirds** [mbraak/jqTree#565]
var $tree = $('#tree1').tree({
						singleBranchExpand: false,
                                                data: data,
                                                dragAndDrop: true,
                                                autoOpen: false,
                                                onDragStop : function(node, $li){
                                                	alert(" asdasd asd ");
                                                }
                                          });

Not alerting asdasd asd after drag stopped.

**Comment by mbraak** [comment]
I will look into it

**Comment by mbraak** [comment]
I could not reproduce this error. I tested it on Chrome.

NB: `onDragStop` is called when you release the mouse button; so when a node is actually moved

**Comment by mbraak** [comment]
No progress here. Closing.
