### ISSUE TITLE
.jqtree-title how to remove auto focus 

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#566]
If you dynamically add a contenteditable=true div after the .jqtree-title <li>. Then make the .jqtree-title <li> also contenteditable=true.

$li.find('.jqtree-title').after('<div class="test" contenteditable=true>test</div>');
$li.find('.jqtree-title').attr("contenteditable","true");

When you initially click on the contenteditable=true div the cursor jumps into the .jqtree-title <li>.

How to remove the auto set focus on the .jqtree-title <li> jqTree title, so that the cursor initially stays in the dynamically added contenteditable=true div?

I could force set the focus to the e.target on tree click, but is there a better way?

Huge Thx! Great software! Thanks for the help,

**Comment by WriterStat** [comment]
The github forum isn't allowing me to edit or to insert code correctly, seems wonky/broken so the above text may be a bit unformatted. apologies in advance. Hope it makes enough sense.

**Comment by mbraak** [comment]
You can do the following: 

```js
$tree.on("tree.click", function(e) {
    e.preventDefault();

    $tree.tree("selectNode", e.node, { mustSetFocus: false });
});
```

Note that you need the latest `dev` branch to do this. It doesn't work on the npm package at this moment.

**Comment by WriterStat** [comment]
Hi Marco, Cool! Thanks!

I grabbed the dev build.

I'm going to try and use markdown here on github in the github box to fix it's broken formatting. =)

I currently use the code below to allow clicking and re-clicking on both the contenteditable=true div and the .jqtree-title span, to prevent deselecting the selected node on re-click of the two areas in the node.

```
 if ($tree.tree('isNodeSelected', e.node)) {
 e.preventDefault();
 }
```
How to stop the autofocus and do the above to allow re-clicking the two areas in the node without deselection. Possible? Thx!

I tried a few things, like just using the autofocus code and other variations using both, but unable to get both to work together.

Without the code above, it focuses correctly using the new code, but then deselects the node when clicking on both areas.

example: click the .jqtree-title span then click the added contenteditable div, it deselects the node.
example: click the added contenteditable div then click the  .jqtree-title span, it deselects the node.

**Comment by mbraak** [comment]
Hello,

The event in `tree.click` has a `click_event` property for the original click event. You could use this to check which html element was clicked on.

For example:

```js
$tree.on("tree.click", function(e) {
    e.preventDefault();

    const target = e.click_event.target;

    if (!$(target.hasClass("my-edit-div"))) {
        $tree.tree("selectNode", e.node, { mustSetFocus: false });
    }
});
```

Greetings

**Comment by WriterStat** [comment]
Hi Marco, Thanks!

Ok so this code stops the cursor from jumping out of the clicked on element in the node.

```
const $target = $(e.click_event.target);
if ($target.hasClass("my-edit-div")) {
e.preventDefault();
$tree.tree("selectNode", e.node, { mustSetFocus: false });    	
}
```
Possible to turn off mustSetFocus globally as an option? Are there possible ramifications to doing it?
How do we stop the current node from being de-selected when the elements inside it are clicked twice, while keeping it selectable?

Thanks again!

In testing I can stop the cursor jump or I can stop the current node from deselecting on second element click inside it, but I can't seem to do both.

I'll keep trying. Possibly just something I'm missing.

**Comment by mbraak** [comment]
* *Possible to turn off mustSetFocus globally as an option?* At this moment there is no option for that.

* *How do we stop the current node from being de-selected?*

```js
$tree.on("tree.click", function(e) {
    e.preventDefault();

    if (!$tree.tree("isNodeSelected", e.node)) {
        $tree.tree("selectNode", e.node, { mustSetFocus: false });
    }
});
```

**Comment by WriterStat** [comment]
Cool! Thank you! Closing...

**Comment by WriterStat** [comment]
Hi Marco, I noticed that sometimes a clicked on tree node area gets selected but doesn't get focus. Thanks for the help.

example to recreate:

I create 4 nodes/tree items in the tree.

Under/inside each of those I create 2 content editable divs.

When I click on and between the content editable divs under/contained in the nodes/tree items. The jqtree tree items/nodes area containing them should get focus. And the clicked on div should get selected/get the cursor.

For a while they do, then after a while if you continue to click between the content editable divs under/contained in the nodes/tree items the divs get selected with the cursor in them but the node area they are under stops getting focus/selected. The focus stays in the previous tree node and doesn't focus on the newly clicked on tree node area. But the div does get the cursor.

Hope there is a fix, thanks!

Our goal is to click on a div under a tree node and for the tree node to get selected, bu the cursor and focus to be in the selected div under it.

Thanks again for any help

**Comment by mbraak** [comment]
I will try to reproduce this. Do you have example code that I can use for that?

**Comment by mbraak** [comment]
I could not reproduce the error using the example below.

```js
const $tree = $("#tree1");

$tree.tree({
    data: ExampleData.exampleData,
    autoOpen: 1,
    onCreateLi: function(node, $li) {
        $li.find('.jqtree-title').after('<div contenteditable="true" class="edit">test</div>');
    }
});

$tree.on("tree.click", function(e) {
    e.preventDefault();

    $tree.tree("selectNode", e.node, { mustSetFocus: false });
});
```

**Comment by WriterStat** [comment]
Hi Marco, much thanks,  I'll try and send you some code. In the next day or so, Traveling..

I'll also download and make sure I have the current version.  In case it's here.

I made a couple of contenteditable divs under each node. So as to make it quicker to find when you click between them.

I also have this code in my code from the thread above:

```
$tree.on(
    'tree.click', function(e) {
		e.preventDefault();
		if (!$tree.tree("isNodeSelected", e.node)) {
    	    $tree.tree("selectNode", e.node, { mustSetFocus: false });
    	}
});
```

**Comment by WriterStat** [comment]
Top of my head, I had: 

```
onCreateLi: function(node, $li) {
        $li.find('.jqtree-title').after('<div id="1" contenteditable="true" class="edit1"  data-gramm_editor="false" tabindex="0">test</div>');
        $li.find('.jqtree-title').after('<div  id="2" contenteditable="true" class="edit2"  data-gramm_editor="false" tabindex="0">test</div>');
    }

$tree.on(
    'tree.click', function(e) {
		e.preventDefault();
		if (!$tree.tree("isNodeSelected", e.node)) {
    	    $tree.tree("selectNode", e.node, { mustSetFocus: false });
    	}
});
```

But will send some much better test code after I check the newest version in a day or so, from travel.

**Comment by WriterStat** [comment]
I also have this code from the thread above.

```
$li.find('.jqtree-title').attr("contenteditable","true");
```
The node is content editable, with 2 contenteditable divs under it. And then the isNodeSelected code from the above thread as well, to keep the cursor in the div clicked on. Will send better thanks.

**Comment by WriterStat** [comment]
Hi Marco, I re-uploaded the tree jquery file.

We haven't made any source changes to the tree code. So it should rule out a bad file.

Still seeing this, I'll try to trace down the exact sequence to get this to happen. And trace the code to either rule out our code here and provide test code. Our code here is all outside the tree code.

It appears it is multi-selecting in some fashion. With the first selected node's contenteditable area staying selected after clicking a new one and the newly clicked on contenteditable area also being selected but the node for that, that contains it, is not highlighted/selected in the tree. Pretty weird.

**Comment by WriterStat** [comment]
I'm going to set up a test are here. May take me a bit.

**Comment by WriterStat** [comment]
I did a really quick test using the autoscroll demo as a base. Am including an image...hopefully as the github box here doesn't seem to like my editing it. It shows how the node select and the cursor are in different places...sort of unhitched. I'll try and clean up a better test, but maybe seeing it can help identify it.

**Comment by WriterStat** [comment]
Ok in testing there seems to be a collision with the jqtree code when the focusout event happens.

To replicate create 6 nodes.
Then populate each of those nodes by using the code below when you create the tree:
```
onCreateLi: function(node, $li, is_selected) {
	var t_title = $li.find('.jqtree-title');
	t_title.attr("contenteditable","true");
	t_title.after('<div class="div1" contenteditable="true">Stuff goes here</div>');
	t_title.after('<div class="div2" contenteditable="true">Stuff goes here</div>');
	},
```
And then also this code is needed as well so that the divs can be directly selected when under the nodes :
```
$tree.on(
    'tree.click',
    function(e) {
	e.preventDefault();
	if (!$tree.tree("isNodeSelected", e.node)) {
    	     $tree.tree("selectNode", e.node, { mustSetFocus: false });
    	}
});
```
This will give you 6 contenteditable nodes each with two contenteditable divs under them.

You'll need to use this small CSS on the page with them to cause the error:
```
<style>
.div1:focus {
   height: 130px;
   border: 1px solid #dddddd !important;
   -webkit-border-radius: 5px !important;
   -moz-border-radius: 5px !important;
   border-radius: 5px !important;
}
.div2:focus {
   height: 230px;
   border: 1px solid #dddddd !important;
   -webkit-border-radius: 5px !important;
   -moz-border-radius: 5px !important;
   border-radius: 5px !important;
}
</style>
```
I gave them borders to make them easier to see. But it's only the change in height of the div under the node during the focusout/blur event that triggers the tree collision.

To trigger the collision:
Click on div1 under the first node 1, then click on div1 under node 2, then click on div1 under node 3.
Next click on the node title for node 5.

The cursor moves to node 5, but the highlight and node selection for the tree do not. To get things/the tree to sync up again, you have to click node 5 twice. Or click another node in the tree.

This causes problems when trying to add or remove a node because the current node is actually the previous one. (It looks like) And the current clicked on node doesn't appear selected.

You can also trigger the error using Jquery instead of CSS by using this code:
```
$tree.on('focusin', '.div1', function(e) {
	$(this).css("height","130px");
	var node = $tree.tree('getNodeByHtmlElement', this);
	$tree.tree('scrollToNode', node);
    });
$tree.on('focusout', '.div1', function(e) {
	$(this).css('height', 'auto');
});
$tree.on('focusin', '.div2', function(e) {
	$(this).css("height","230px");
	var node = $tree.tree('getNodeByHtmlElement', this);
	$tree.tree('scrollToNode', node);
});
$tree.on('blur', '.div2', function(e) {
   $(this).css('height', 'auto');
});
```  
You can also trigger the error using the 'blur' event if not using 'focusout'.

I want to change the height of the div to be larger on focus and then return to the original one line height size on blur or focusout. Which way is best?

Thanks for the great software, I'm hoping you can let me know why it does this and a possible work around.

**Comment by mbraak** [comment]
Thanks for the example code. I can now reproduce the bug.

When I click the title of node 5, I get a `click` event with the target `ul`. That is one of the parents of the node.

I think the browser is somehow confused in this situation. Maybe it's because of the css on focus.

I tried the following css, and that seems to work:

```css
.jqtree-selected > .jqtree_common > .div1 {
    height: 130px;
    border: 1px solid #dddddd !important;
    -webkit-border-radius: 5px !important;
    -moz-border-radius: 5px !important;
    border-radius: 5px !important;
}

.jqtree-selected > .jqtree_common > .div2 {
    height: 230px;
    border: 1px solid #dddddd !important;
    -webkit-border-radius: 5px !important;
    -moz-border-radius: 5px !important;
    border-radius: 5px !important;
}
```

**Comment by WriterStat** [comment]
Super! Thank you! You are correct.

Your support here for this is tremendous!

Will give it a try.

My css wasn't scoped correctly/specifically enough, even if working. And left too much up to the browser.

Thanks!

**Comment by WriterStat** [comment]
First off your support for this project is really tremendous! Thank you! Huge thanks!

Gave it a quick test.

There's a few gotchas in testing.

Doing the above and going around focusout and blur means that both divs, div1 and div2 are always opened at max size before/prior to being clicked/having focus.

In changing all the div1 css to be more specific here some of the css doesn't get applied in the tree for some reason, but works as .div1.

I also tried:
``` 
.jqtree-selected > .jqtree_common > .div1:focus
```
Was hoping it would work.

But the jqtree stops selecting nodes/divs, and then needs the next node or div under a node to be clicked on after that to start again.

The Tree doesn't seem to like CSS focus, the focusout and blur events in some cases/collision when there's an element resize.

Our goal is to have a description div or note div under the node to be opened up/resized on click/focus and for the node it's in to be selected and then to resize back to regular when another node or div is selected. As an in-place edit. We are sooo close. jqTree is almost there.

Everything works great with .div1: focus except every once in a while the jqtree stops finding/selecting tree nodes/divs under nodes during/after a div/element resize on focusout or blur. Possibly something happening in the tree resize or scroll, focusout or blur events or things associated to resize or blur?

Could we always force the tree node selection/old node de-selection in javascript in our code when a node or div under it gets focus? focus:within? 

That way, even if the node gets lost or isn't selected we select it?
 
Wish my javascript/css was better. =) Thanks again!

**Comment by mbraak** [comment]
I think using `:focus` in css makes things more complicated in this situation. The browser seems to react in unpredictable ways.

Perhaps there is an alternative solution?

**Comment by WriterStat** [comment]
Hi Marco, want to make sure we try everything. We've got a bit invested in jqtree. Appreciate the thoughts and help.

**Comment by WriterStat** [comment]
We won't take this too much farther, but want to take it far enough to see if this works.

If you use the test set up I gave. And give each div a different unique id...id+1.

Then in testing it appears for this bug that the tree selects/thinks you are clicking on the same node again even though the browser propagates and moves the cursor into the new node element, node 5.

And so does no new selection.

So if you use the same test that produces the bug and give each different div an id
Then use this code to monitor.
```
$(document).on("click","#tree1", function (event) {
    console.log(event.target.id);
});
```
Then click on the div1 under the 1st node. Then click on the node 5. In our testing, the console log will give the div1 id you first clicked on twice. Like the tree click default was prevented and it was prevented .preventDefault() from running the node selection code.

Propagation wasn't prevented so the browser moved the cursor into the new node/new element, leaving the selection in the old node. So the old node is selected, and the new node gets the cursor in it.

I'm believing this code below possibly prevents it from moving on/selecting to the new node/element? Because it stops the default and believes it's still on the current div1 on tree click and that's already selected. Possible?
```
$tree.on(
    'tree.click',
    function(e) {
	e.preventDefault();
	if (!$tree.tree("isNodeSelected", e.node)) {
    	     $tree.tree("selectNode", e.node, { mustSetFocus: false });
    	}
});
```
And so doesn't run the selection code. But does allow the browser propagation to bubble up the event chain for the cursor to move to new element?

Possibly might explain the target parent ul of the node, not sure though. Possible?

So possibly not the :focus, which is just a symptom, does seem to work. Just prevented from getting/selecting the new node? Thoughts? Apologize if I'm behind.

We've noticed the node selection bug happening intermittently also on the divs under the nodes prior to us using the :focus. Could the bug be found in the underneath tree click code used to grab the node, because it's getting it using the div inside and not the node? Hoping. =) Thoughts?

**Comment by WriterStat** [comment]
Much thanks for the help, I think solving this could help jqtree.

Ok, I have a theory after doing a bit of more testing. But only a theory for now.

Once we put our own contenteditable divs/spans under the tree using the onCreateLi code and forced the cursor to stay in them on click with the provided code, we noticed jqtree appeared to lose it's tree selection ability, in some cases when going from div/span under a node to a new node and when going from a node to a div/span under a different node.

This was prior to using the :focus.

My theory is the browser/jqtree is prevented from running the necessary code somewhere to select the tree node or that the node doesn't change for some reason. Because of an event/code where there is a e.preventDefault(); set but where e.stopPropagation(); is not set. Or something similar to this. Thoughts? Possible?

Something prevents the node selection. But allows the browser to propagate and place the cursor.

Because the browser isn't getting lost, it's just being prevented from running the selection code, but the browser still propagates to the clicked on area placing the cursor there. Tree selection is left in one place, the browser cursor is moved to another. Thoughts? Possible?

 So in test the cursor is moved to be in node 5, but the selection never moves from the prior selection.

In some of the testing of jqtree, when we click on node 5 from a div under a node, no tree.click is registering here in tree.click.

So I'd like to open a new issue based just on the loss of selection/non-selection.

**Comment by WriterStat** [comment]
And then close this one. So we can keep it node selection bug specific. Possibly walk through the possibles. has to be one of them. =)

**Comment by WriterStat** [comment]
In testing, I think I possibly found a clue as to why the tree sometimes doesn't select:

If you set up the test script from the top provided above that provides/shows the selection bug.

And then instrument the tree.click event code with:
```
$tree.on(
    'tree.click',
    function(e) {
	e.preventDefault();
	console.log('tree.click:'+e.node);
	if (!$tree.tree("isNodeSelected", e.node)) {
	     console.log('...!selected');
    	    $tree.tree("selectNode", e.node, { mustSetFocus: false });
	}
});
```
And then run the test, by clicking on div1 under node 1 and then on node 5.

Clicking div1 fires the tree.click event.

But clicking node 5 does not fire the tree.click event. So no node is selected.

But the browser does work correctly and places the cursor in the clicked node.

Just no tree.click event selection code is called.

Hope helps track down the bug. Thanks! 
Wondering if you see this too? If so, with no tree.click event fired then no node is selected right?

Maybe you've already seen this.

**Comment by WriterStat** [comment]
Hi Marco, 

After finally catching up to where you were above with the parent ul being returned as the e.target for the tree node click. And getting familiar with the jqtree code finally.

Thanks for being patient. =) Took me a bit. =)

To stop the tree click from resetting the click target to the very top of the tree.

I made this code change in the jqtree base tree code:
```
   //this.element.click(this._handleClick);
   this.element.mousedown(this._handleClick);
```
I don't know if there will be ramifications, other than the keyboard shortcuts. Which we'll change.

But in testing everything now selects correctly between divs/nodes, contenteditable areas etc... and it allows us to use click/blur, focusin/focusout, resize and all other events without affecting the tree target selection or making any large changes. It bypasses whatever collision was going on in those events for the tree.

Let me know if there are any other downsides to using the mousedown event for this.

We'll continue to test and adjust back to the click event later.

Changing the css selectors didn't make a difference, we tried a dozen different ways and intermittently the e.target for the tree node was still changed to the top of the tree in some clicks. For us a dynamic change in the height of the div under the node and then a change back to the original size of the div on blur/focuout caused the target reset bug to happen in the tree.

**Comment by WriterStat** [comment]
I'm trying this out in the jqtree base tree code:
```
   //this.element.click(this._handleClick);
   this.element.mousedown(this._handleClick);
```
Let me know if you can see any downsides. But seems to work, allow all the focus/click/focusin, blur/focusout events and :focus to work. Still testing it though. Huge Thanks!

**Comment by mbraak** [comment]
I'm hesitating to put this into jqtree. The behaviour of `mousedown` is different from `click`. See for example https://stackoverflow.com/questions/19109754/difference-between-mousedown-and-click-in-jquery/19109840

**Comment by WriterStat** [comment]
I definitely understand that.

The selection bug above only happens when you add divs under the nodes in the folder. And we're not sure yet why. Then the click target may sometimes provide the top of the tree instead of the clicked node/div or it may provide the clicked on target. When it provides the top of the tree, of course the tree selection of the node/div fails.

So it may not affect everyone. 

For us, we needed the divs, and the events on them. And this seemed the cleanest way for now.

**Comment by WriterStat** [comment]
I definitely understand that.

The selection bug above only happens when you add divs under the nodes in the folder. And we're not sure yet why.

Then the click target may sometimes provide the top of the tree instead of the clicked node/div or it may provide the clicked on target. When it provides the top of the tree, of course the tree selection of the node/div fails.

So it may not affect everyone.

For us, we needed the divs, and the events on them. And this seemed the cleanest way for now.

**Comment by WriterStat** [comment]
Closing this.

Mousedown seems to work, for our use to the tree code, allowing regular divs and contenteditable divs to work with the tree selection and with node selection.

Using it also appears to reduce the browser/tree selection lag time, things seem to now select much faster.

Note: The mousedown event does allow all three mouse buttons, left, right and middle scroll button click to select tree elements, but this seemed to be ok/appropriate in use.

Thanks to Marco, for the great software.
