### ISSUE TITLE
ability to add a list to state

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#567]
Hi Marco! Wonderful software! Thanks!

Possible to add/access a new state list?

State in the Local Storage is:
```
{ open_nodes: [12, 23, 45], selected_node: [88] }
```

I have a chkd state I am currently storing in the json Data. And would like to store/access a checked_nodes as a State option above to keep state and data separate. I also have a few other state options I'd like to store/access in the state object to keep them separate from the data.

So possibly a way to add a new state list. And the ability to add a state function chained to handle it/them.

The chkd state in the Data works fine, but wondering about the above. I'm going to save the State JSON in the database along with the Data. 

Thoughts? Thanks!

**Comment by mbraak** [comment]
Hello WriterStat,

I think it's not practical to use the existing state for storing the nodes. The reason is that the state is an internal mechanism for the tree.

Maybe an alternative is to write some code that stores the checked nodes somewhere else in the local storage.

Greetings

**Comment by WriterStat** [comment]
Hi Marco, thanks for the quick response, totally understand. I can definitely do that.

I can store a state_checked_nodes list in local storage.

{ checked_nodes: [12, 23, 45] } 

Huge Thanks again,
