### ISSUE TITLE
Grabbing/displaying a portion of the tree.

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#569]
Thanks for the great software!

I noticed in the json for the tree that there's ids for each node to keep track of things. Is it possible to grab a portion and display a portion of the menu after the tree/dom has already been loaded?

Like let's say I'd like to display only one node and it's sub nodes of the current tree to the user.

Thanks!

**Comment by mbraak** [comment]
Hello WriterStat,

The tree does not have a built-in function for displaying a subtree of the current tree. But there are functions that you can use to achieve that, combined with some custom javascript code.

The following functions can be useful, depending on your use case:

* The function [getData](https://mbraak.github.io/jqTree/#node-functions-getdata) gets the current data of the tree.
* The function [loadData](https://mbraak.github.io/jqTree/#functions-loaddata) loads new data into an existing tree.
* The [tree.init](https://mbraak.github.io/jqTree/#event-tree-init) is emitted when the data is loaded. This function is useful if you load the data from the server.

Could you tell me more about your use case? What kind of data are you displaying, and when do you want to show the sub nodes?

Greetings,
Marco

**Comment by WriterStat** [comment]
Hi Marco,

Thanks for the quick note back.

I was thinking to make this more mobile friendly we could when the tree gets a bit long either vertically or horizontally. Maybe in cases where it's on a limited view/smaller device like mobile, tablet or phone, that I could allow when clicking on a node to just display the clicked on node. Maybe a <> on top.

Hope this makes sense, on small screens/mobile then the tree would still work wonderfully. With everything moving to mobile first dev, it makes sense to have a fall back/alternative.

**Comment by WriterStat** [comment]
So it looks like I could grab the current selected node data using node.getData().

But if I use loadData won't it change the underlying initially loaded tree data to be the newly loaded one?

I want to display only the current selected node in tree1 div, but I don't want to lose the underlying full set of tree data that the node is a part of. I suppose I could locally save the full tree as a shadow tree and then make changes to it when changes occur in the loaded node. But this risks sync problems. Possibly the best way to implement this would be to have a display/loadData option that doesn't change the initially loaded underlying tree data object.

Then you could iterate back and forth in the currently loaded tree nodes while keeping the underlying tree data in sync.

Giving this some thought.

**Comment by WriterStat** [comment]
My other thought is to use a filter of the current tree1 display somehow so it only shows the selected one and it's children/sub nodes of the current tree.

**Comment by WriterStat** [comment]
Will close and look for solution, the ability to drill down would definitely be great for current smaller screens/mobile first. Will send code once I have it figured out.
