### ISSUE TITLE
Setting the open state of the tree

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#574]
Hi Marco,
I'd like to set the open state of the tree to have only the first node opened and selected.

How do I do it?

After I loaded the tree from the server I tried:
```
$tree.on('tree.init', function() {
		var nstate = {"open_nodes":[1],"selected_node":[1]};
		var _json = JSON.stringify(nstate);
		console.log(_json);
  		$tree.tree('setState', nstate);
		ttree = $tree.tree('getState');
		console.log(JSON.stringify(ttree));
	});
```

What other tree settings should I set? Could you give me an example of setting the open state of the tree? Thanks! The above didn't work for me.

I checked the docs, but couldn't find an example/info.

My goal is to store the open state of the tree in mySQL and then set the open state of the tree based on the stored open state of the tree from mySQL. Is there a quick example?

What if I wanted to set the tree to:
```
{"open_nodes":[1, 2, 7, 16],"selected_node":[1]};
```
Much thanks.

**Comment by mbraak** [comment]
I think it's beter to you use the `selectNode` function. Something like this:

```js
$tree.on("tree.init", function() {
    var root = $tree.tree("getTree");

    if (root.hasChildren()) {
        $tree.tree("selectNode", root.children[0]);
    }
});
```

**Comment by WriterStat** [comment]
For others...How do I set the open nodes along with the selected node?
Could you give me an example of setting the open state of the tree using setState and the code below? Thanks! 
```
var nstate = {"open_nodes":[1, 2, 7, 16],"selected_node":[1]};
$tree.tree('setState', nstate);
```
The above doesn't seem to work for me and it's the code from here in the forum. I'll be storing the state in the database/mySQL. Each tree will be different with different nodes open and selected. So will need to set the state of opened and selected.

Mych thanks! Thanks again,

**Comment by WriterStat** [comment]
For others...How do I set the open nodes along with the selected node?
Could you give me an example of setting the open state of the tree using setState and the code below? Thanks!

var nstate = {"open_nodes":[1, 2, 7, 16],"selected_node":[1]};
$tree.tree('setState', nstate);

The above doesn't seem to work for me and it's the code from here in the forum. I'll be storing the state in the database/mySQL. Each tree will be different with different nodes open and selected. So will need to set the state of opened and selected.

Much thanks! Thanks again,

**Comment by mbraak** [comment]
You could use the `onGetStateFromStorage` option. The option is not documented yet.

If you want to set the initial state of the tree, then this is maybe a good option.

```js
$tree.tree({
    data: ExampleData.exampleData,
    saveState: true,
    onGetStateFromStorage: function() {
        return JSON.stringify({ open_nodes: [1], selected_node: [2] });
    }
});
```

* It is only called when the tree is initialized. After the data is loaded.
* It should return the `open_nodes` and `selected_node` as a json string.
* `selected_node` is an array; you can include multiples nodes
* The default implementation of this function is to get the data from localstorage.

There is also a `onSetStateFromStorage` option which is called when the tree saves the current state.

**Comment by mbraak** [comment]
I tried `setState`. This example code seems to work:

```js
const $tree = $("#tree1");

$tree.on("tree.init", function() {
    $tree.tree("setState", { open_nodes: [1], selected_node: [2] });
});

$tree.tree({
    data: ExampleData.exampleData
});
```

**Comment by WriterStat** [comment]
onGetStateFromStorage looks to be pretty great! I'll give it a try. And use the other info provided as well. Thanks!

Thanks again.

**Comment by WriterStat** [comment]
For:
```
$tree.tree({
	dataUrl: serverURl,
        saveState: true,
        onGetStateFromStorage: function() {
           return serverTreeState;
    }
```
With the above. Using it from the server takes two server calls.
One for the DataUrl and one ahead of time on the same data row for the serverTreeState.
 
Feature request: Combine dataUrl and onGetStateFromStorage for one data call into:
```
dataUrlStor: serverURl,
```
serverUrl passes back treeJson and treeState json to jqTree.

I think this is something we could add if not in the base.
