### ISSUE TITLE
Have icon for empty folders

### ISSUE THREAD

**Issue by andrew-hinde** [mbraak/jqTree#579]
This is basically a clone of issue 516.

Currently when a node has no children it's assumed that it is not a folder (based on the isFolder function in node.js).  I was wondering how I can override this function to use a data property on the node.  I'm setting this to distinguish between 'folders' and the items within it, but if the folder is empty, there's no icon - only if it's populated.

Can I overload the isFolder function, or is there a different way I can achieve adding the openedIcon to a node that has no children?

Thank you.

**Comment by mbraak** [comment]
Currently there is no support for that. I could change the code so it considers a node a folder if it has an empty `children` property.

So, it could work like this:

```
{ name: 'abc', id: 1, children: [] }  // folder
{ name: 'abc', id: 1 }  // not a folder
```

Would this solution work for you?

**Comment by andrew-hinde** [comment]
I could definitely work with that.  Thanks!

**Comment by mbraak** [comment]
I have added a pull-request with this new feature: #580. Please see the example there.

Note that it adds a new option `showEmptyNode`.

**Comment by mbraak** [comment]
The pr is merged in `dev`; it's not yet in an npm release
