### ISSUE TITLE
Reload node with new data

### ISSUE THREAD

**Issue by rat43** [mbraak/jqTree#58]
Is there any functionality to reload the data node?

For example, after submitting the form I need to update the node with new data (label and icon).

Today I am doing the following:
-> addNodeAfter ("new data", oldNode);
-> removeNode (oldNode);
-> Loop to find the new node because I don't have an unique id;
-> selectNode ("new node") to maintain the state of oldNode;

**Comment by vikasrana-netsmartz** [comment]
I am unable to add children in updateNode/appendNode, is it possible to update/append a node with child items

**Comment by mbraak** [comment]
You can't use ``updateNode`` or ``appendNode`` for that. Perhaps you can use [loadData](http://mbraak.github.io/jqTree/#functions-loaddata).

This will add a subtree to the node. Note that existing children will be replaced.

```js
var node = $tree.tree('getNodeById', 123);

var subtree = [
    {
      label: 'new1',
      id: 200,
      children: [
        { label: 'child1': id: 201 }
      ]
    },
    { label: 'new2' , id: 202}
];

$tree.tree('loadData', subtree, node);
```

**Comment by vikasrana-netsmartz** [comment]
Thanks for the immediate reply. Hope it would help me.
