### ISSUE TITLE
Alternative labels for tree nodes

### ISSUE THREAD

**Issue by mgillnorthgateps** [mbraak/jqTree#581]
Hi,

Tree nodes can be defined with "name" or "label". Is it possible to have an alternate display name so I can display one value (label) and return another when node is selected ?

**Comment by mbraak** [comment]
Hello,

Yes, you can using the [onCreateLi](https://mbraak.github.io/jqTree/#options-oncreateli) option.

Something like this:

```js
$('#tree1').tree({
    data: data,
    onCreateLi: function(node, $li, isSelected) {
        var text;

        if (isSelected) {
          text =node.name + ' (selected)';
        } else {
          text =node.name;
        }

         $li.find('.jqtree-title').text(text);
    }
});
```

Also see [this example](https://mbraak.github.io/jqTree/examples/09_custom_html/)

Depending on your needs you can also add custom properties to your data.

```js
// custom property 'selectedName'
var data = [
  {
     id: 1,
     name: 'abc',
     selectedName: 'abc - selected'
  }
];

$('#tree1').tree({
    data: data,
    onCreateLi: function(node, $li, isSelected) {
        var text;

        if (isSelected) {
          text =node.selectedName;
        } else {
          text =node.name;
        }

         $li.find('.jqtree-title').text(text);
    }
});
```

I hope this answers your question.

Greetings
