### ISSUE TITLE
isNodeSelected does not work with multiple selection

### ISSUE THREAD

**Issue by jonathantwright** [mbraak/jqTree#589]
I am unable to reproduce the example provided at https://mbraak.github.io/jqTree/examples/08_multiple_select/.

e.preventDefault(); is set so that single click is disabled.

But the on click event always seems to trigger the opposite of what you would expect.

Example:

        `$rootNode.on('tree.click', function (e) {

            e.preventDefault();
            var selected_node = e.node;

            if (typeof selected_node.id == "undefined") {
                console.warn('jqTree: The multiple selection functions require that nodes have an id');
            }                    

            // toggle node selection
           if ($rootNode.tree('isNodeSelected', selected_node)) {
                console.log("node selected!");       
                $rootNode.tree('removeFromSelection', selected_node);
           } else {
                console.log("node de-selected!");                    
                $rootNode.tree('addToSelection', selected_node);
           }
        });`

In my example, highlighting a node will write to the console **node de-selected!**
In my example, deselecting a node will write to the console **node selected!**

I wrapped the if statement in a timeout function, just to see if the 'tree.click' handler needed a few extra ticks to set the state of the node, but this has no effect

**Comment by mbraak** [comment]
I tried this (on `devserver/devserver.js` in the source code) and it seems to be working.

It prints  'node de-selected' when the node was not selected, and is now selected. The multi-select also work.

Strange that your example doesn't work. What types are you using for the ids, just numbers or something else?

**Comment by jonathantwright** [comment]
Unless I misunderstand the intention of the method name.

1. 'isNodeSelected' refers to the state of the node for the click event the user just fired.
2. Or, 'isNodeSelected' refers to the previous state of the node BEFORE the click event fired?

The name implies to me that the intention is #1.

I have a sample that I posted on codepen.io that I will post shortly.

**Comment by mbraak** [comment]
It's option 2. Note that the click event did not change the selection because `preventDefault` was called.
I can understand that this is confusing.
