### ISSUE TITLE
Use jqTree in TypeScript

### ISSUE THREAD

**Issue by myth984** [mbraak/jqTree#592]
Hi Marco, Thanks again!

I use jqTree in TypeScript
```
$('#tree1').on(
                        'tree.dblclick',
                        function (event) {
                            console.log(event.node)
                        
                        }
                    );
```
event doesn't has node.

**Comment by mbraak** [comment]
I'll try to reproduce this error.

**Comment by mbraak** [comment]
I used this workaround myself: 

```ts
$tree.on("tree.dblclick", function(event) {
   console.log((event as any).node);
});
```

Does this solve the problem?

I will see if I can add the type information to the event.

**Comment by mbraak** [comment]
I haven't found a way to define a custom event. The typescript definition for Jquery does define types for existing types (like `ClickEvent`), but I couldn't find a way to add a custom event. So the workaround with `any` seems the be the only solution at this moment.

**Comment by mbraak** [comment]
Closing the issue without a solution.
