### ISSUE TITLE
multiple values in "selected_nodes" possible - why?

### ISSUE THREAD

**Issue by rowild** [mbraak/jqTree#601]
Via the implementation in a CMS's ecommerce system I discovered that it is theoretically (and practically) possible to save more then one value in the localStorage's tree object under `selected_nodes` (which is an array). I wonder, why this is possible, since I would assume that one and only one item is a tree could be the selected one?

What I am misunderstanding here?

The issue of said CMS can be found here (there is even a video that showcases the problem):
https://github.com/aimeos/ai-admin-jqadm/issues/119

Thank you!

**Comment by mbraak** [comment]
The default behaviour is to select a single node. In that case `selected_nodes` contains 0 or 1 ids.

But it is possible to select multiple nodes using api calls: https://mbraak.github.io/jqTree/#multiple-selection.

**Comment by rowild** [comment]
Thank you for your quick response! Good to know that this is intentional and also thank you for pointing me to the example! I admit I missed that one!
Is there any way to prevent multiple selection?

**Comment by mbraak** [comment]
By default a single node is selected. The only way to select multiple nodes is to call the `addToSelection` method.

One detail: it is important to give nodes a unique id.

**Comment by rowild** [comment]
OK. We do not use `addToSelection`, nevertheless localStorage's `selected_nodes` is filling up with ids (yes, our ids are unique...) 
No idea, why this happens, probably because the second level of the tree is lazy-loaded...

Thank you very much for your fast feedback! Much appreciated! :-)
