### ISSUE TITLE
createTitleSpan performance

### ISSUE THREAD

**Issue by bgeree** [mbraak/jqTree#603]
I just finished profiling a huge tree and I noticed a performance bottleneck in the createTitleSpan() method. Since HTML is not allowed here I think the innerHTML can be replaced with textContent.

Can you please confirm this?

Thanks!

**Comment by mbraak** [comment]
I'll have a look

**Comment by mbraak** [comment]
Using `textContent` seems to work fine. And yes, html is not allowed for the title.

I made a pr: https://github.com/mbraak/jqTree/pull/604 (not merged yet)

**Comment by mbraak** [comment]
The pr is merged. Closing the issue.

**Comment by jorgecasas** [comment]
Is any reason to not allow HTML in createTitleSpan()? In version 1.4.2 it was allowed (labels, links, images...) thanks to innerHTML:

![jqTree-before-1 4 2](https://user-images.githubusercontent.com/968843/93789175-cf50d680-fc31-11ea-89d5-5e96038b46c2.jpg)

In version 1.5.0, with textContent, it is not backwards compatible:

![jqTree-after-1 5 0](https://user-images.githubusercontent.com/968843/93789268-ec85a500-fc31-11ea-9634-5abd7b54c546.jpg)

Any way (maybe adding a new parameter) to indicate that HTML is preferred? Eg. something like if config param X then innerHTML else by default textContent for maximum performance?

Thanks for your magnificient work!

**Comment by mbraak** [comment]
I will have a look at it.

**Comment by mbraak** [comment]
The error above is being fixed in #618. Note that you have to set `autoEscape` to `false`.

**Comment by jorgecasas** [comment]
Thanks! It works perfectly!
