### ISSUE TITLE
"touch" is still on "todo"

### ISSUE THREAD

**Issue by rowild** [mbraak/jqTree#606]
In my case, "touch" is not working, when opening Chrome Dev Tools and selecting a mobile device.

I saw that around line 2795ff the touch event should be handled, but there is still a "todo".

```
    // todo
    // const touch = touchEvent.changedTouches[0];
    // return this.handleMouseDown(this.getPositionInfo(touch));
```

When I remove the comments from the following 2 lines, the touch event is recognised and the tree works, but errors appear in the console:

```
Uncaught TypeError: this.getPositionInfo is not a function
    at HTMLDivElement.MouseWidget._this.touchStart (VM3763 index.php:2947)
    at HTMLDivElement.dispatch (VM3770 jquery.min.js:2)
    at HTMLDivElement.v.handle (VM3770 jquery.min.js:2)
```

When I add underscores to this function (as is done with other functions)

```
return _this.handleMouseDown(_this.getPositionInfo(touch));
```

the errors disappear, but the tree does not react anymore (no folders open, not page reloads...)

The same is true for "touchMove" and "touchEnd", where all the move-related functions work better, when uncommented and "this" corrected to "_this", even though it is not optimal, because the device does not seem to distinguish, whether I want to move a Node or scroll the page (and therefore predominantly scrolls...)

Do you have any idea, if this is something I messed up or you can fix?

Thank you very much!

EDIT:

Question: is there a particular reason, why you assign the event to an extra variable, which IMO does not serve any purpose?

```js
_this.mouseDown = function (e) {
		var mouseDownEvent = e; // <-- Why? everything that follows could very well be just handled with "e"
		// Is left mouse button?
                if (mouseDownEvent.which !== 1) {
                    return;
                }
		var result = _this.handleMouseDown(_this.getPositionInfo(mouseDownEvent)); // <= "_this.getPositionInfo(e)"
                if (result) {
                    mouseDownEvent.preventDefault(); // <=  "e.preventDefault();"
                }
                return result;
            };
            _this.mouseMove = function (e) {
                var mouseMoveEvent = e; // <= no need
                return _this.handleMouseMove(e, _this.getPositionInfo(mouseMoveEvent));
            };
            _this.mouseUp = function (e) {
                var mouseUpEvent = e; // <= no need
                _this.handleMouseUp(_this.getPositionInfo(mouseUpEvent));
            };
```

**Comment by mbraak** [comment]
I will look into the touch events.

The code is written in typescript: https://github.com/mbraak/jqTree/blob/dev/src/mouse.widget.ts. You're looking at the compiled javascript code.

The extra `mouseDownEvent` variable is there for type reasons. The same applies to `mouseMove` and `mouseUp`. 

Below is the typescript code. The extra cast is necessary because typescript expects the parameter to have the type `JQuery.Event`.

```ts
private touchStart = (e: JQuery.Event): boolean => {
        const touchEvent = (e as JQuery.TouchStartEvent).originalEvent;
```

**Comment by mbraak** [comment]
Thanks for finding this issue. It seems that the touch events were broken.
I'm adding the touch events. Pr is #607.

**Comment by rowild** [comment]
@mbraak I really, really highly appreciate your fast and helpful response! Thank you very much!!!

**Comment by mbraak** [comment]
I'll merge #607 shortly.

Note that this error occurs in the `dev` branch. It doesn't occur in the latest release (1.4.12).

**Comment by rowild** [comment]
Thank you! Looking forward to the merge!

**Comment by mbraak** [comment]
The pr is merged.

**Comment by rowild** [comment]
Thank you! I just tried it, and touch move seems to work fine. But the regular touchstart does not open/close and folder in the tree nor load any data.

I must try with the debug version, since we do not have a webpack/TypeScript setup in our CMS.

**Comment by mbraak** [comment]
I'll have a look at it. The version is not yet updated. The version of the next release will be 1.4.13.

**Comment by mbraak** [comment]
Thanks for testing this. Apparently I don't test enough on mobile.

Pr is under way: #608

**Comment by rowild** [comment]
> Thanks for testing this. Apparently I don't test enough on mobile.

That's why there is team work, right? :-)
Thank you again for your quick response! I just tested you latest changes and they seem to work just great! Awesome!

Here is a little animated gif:

![test](https://user-images.githubusercontent.com/213803/86329795-fe653680-bc46-11ea-900d-33a3eb39dfcf.gif)

As a note (which I believe is not jqTree related: 

Moving categories up (probably also down) a tree, when the page itself can scroll or the category tree itself is within a scrollable div with a specific height, is not easy, since the page / div scrolls along with the touch.

Doing so causes this warning: "[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>" [an no, there is really no URL...])

But I assume this is not something that jqtree is responsible for - or would it be able to tackle that? (If so and you want me to open a separate issue, let me know.)

Thank you very much again!!! Have a good day!
