### ISSUE TITLE
Potential XSS vulnerability

### ISSUE THREAD

**Issue by aimeos** [mbraak/jqTree#615]
There's potential stored-XSS attack possible here:
https://github.com/mbraak/jqTree/blob/d6b8d11c4ebd7aa4a60498786bc94724b6f6ffda/lib/dragAndDropHandler.js#L474-L476

If `node_name` contains e.g. `<img src=x onerror="alert('oh')">`, the JS code will be automatically executed:
```
this.$element = jQuery("<span class=\"jqtree-title jqtree-dragging\">" + node_name + "</span>");
```

It can be solved changing the line to:
```
this.$element = jQuery("<span>").addClass("jqtree-title jqtree-dragging").text(node_name);
```

**Comment by mbraak** [comment]
Thanks. I will fix it.

**Comment by mbraak** [comment]
This is now fixed in the dev branch.
