### ISSUE TITLE
Examples have stopped working

### ISSUE THREAD

**Issue by evaneykelen** [mbraak/jqTree#631]
Example: https://mbraak.github.io/jqTree/examples/02_load_json_data_from_server/ (tree is not displayed)

Reason: the `https://mbraak.github.io/jqTree/build/tree.jquery.js` path is invalid

**Comment by mbraak** [comment]
I will have a look.

**Comment by mbraak** [comment]
Thanks for reporting this! It's fixed now.

**Comment by evaneykelen** [comment]
Thanks @mbraak!
