### ISSUE TITLE
I have a follow up question ..... is there anyway to add the dnd features to an existing unordered list?

### ISSUE THREAD

**Issue by duaneelkins** [mbraak/jqTree#639]
I have a follow up question ..... is there anyway to add the dnd features to an existing unordered list?

Let's say I have:

<ul>
   <li>1</li>
   <li>2</li>
</ul>

already loaded in the dom .... can I somehow apply jqTree to it to make it draggable/droppable?

_Originally posted by @duaneelkins in https://github.com/mbraak/jqTree/issues/638#issuecomment-753032230_

**Comment by mbraak** [comment]
No, that's not possible using jqtree.

There are other libraries that supports this: https://sortablejs.github.io/Sortable/ and https://bevacqua.github.io/dragula/ Those libraries have excellent dnd features but are less oriented at tree structures.
