### ISSUE TITLE
Add option to delay drag an drop

### ISSUE THREAD

**Issue by evaneykelen** [mbraak/jqTree#640]
Although there is a setting to delay the opening of folders using `openFolderDelay` there is no option to delay the actual start of the drag & drop action. The delay [seems to be set to 300 ms](https://github.com/mbraak/jqTree/issues/78). It would be nice to make this configurable (based on feedback from my users: some accidentally trigger a drag and drop action).

**Comment by mbraak** [comment]
I will add the option. The name will be something like `startDndDelay`.

By the way, there is an undocumented function that sets the delay: `setMouseDelay`. The function is used in the unit tests.

```js
$tree.tree("setMouseDelay", 100);
```

**Comment by mbraak** [comment]
The `startDndDelay` option is added in pull request #641. The pr will be merged shortly.

NB: the `setMouseDelay` function is removed in the pr.

**Comment by evaneykelen** [comment]
Magnificent!

**Comment by mbraak** [comment]
The pr is merged in the `dev` branch. There is no new release yet.

**Comment by mbraak** [comment]
This is included in release 1.5.3
