### ISSUE TITLE
Folder or file?

### ISSUE THREAD

**Issue by duaneelkins** [mbraak/jqTree#643]
When a user right-clicks on a node I want to detect whether the node is a folder(even if the folder is empty) or a file.

$('#myTree').on(
            'tree.contextmenu',
            function (event) {
                var node = event.node;

                $('#myTree').tree('selectNode', node); //select the node

                //now I want to know if this node is a folder(empty or not) or a file              
            }
        );

Thank you ....

**Comment by mbraak** [comment]
You can set an extra attribute in your data. For example `nodeType`:

```js
var data = [
    {
        name: 'node1', id: 1, nodeType: 'folder',
        children: [
            { name: 'child1', id: 2, nodeType: 'file' },
            { name: 'child2', id: 3, nodeType: 'folder' }
        ]
    }
];

$('#myTree').tree({ data: data });
```

You can access this attribute in the `tree.contextmenu` callback.

```js
$('#myTree').on(
  'tree.contextmenu',
  function (event) {
    var node = event.node;

    console.log(node.nodeType); // file or folder
  }
);
```
