### ISSUE TITLE
Adding/Deleting/Editing and ordering

### ISSUE THREAD

**Issue by duaneelkins** [mbraak/jqTree#644]
I have a unique situation:

My tree is loaded from a db table that looks like this:

Id  	Name  	  Type  	ParentId
1   	Test            folder
4       File1          file           1
8       File2          file           1

and so forth ... you get the idea.

When the page loads we are creating an array of objects that mirror that ... something like:

[{"name":"Test","id":"1","nodeType":"folder","children": [{"name":"File1","id":"4","nodeType":"file"}, ..... etc]

and using that to initially populate the tree.  That all works great.

When a move occurs we are capturing the new structure using:

var tree_json = $('#' + trees[i]).tree('toJson');

and storing it in the db so the next time the page loads we will have the correct order (if there
is stored data ... from a move ... we use that instead of the data coming from the db).

Again ... all that works great.

Here is the rub ..... there are alternate means in place for adding/deleting/editing a tree already in place.  Each time one of those events occur
the page is reloaded.  So ... for example, if I have a folder structure like this:

Folder 1
	File 1
	File 2

and then add a file (File 3) it is created in Folder 1 ... so the db is updated to look like:

Id  	Name  	  Type  	ParentId
1   	Test            folder
4       File1          file           1
8       File2          file           1
9       File3          file           1

the page reloads .... we check to see if there is json data already present for that tree(from a move) ... if there is, we use that instead of the structure coming from the db.  So ... the changes are not reflected but the order is intact.  If we use the newly constructed data then we have the new change but the order is lost.

Does that make sense?  If so .... how can we keep our existing methods in place to add/delete/etc ... but still retain any re-ordering that may have occurred?

Thank you .... Duane

**Comment by mbraak** [comment]
I can tell you what I do in another app ([django-mptt-admin](https://github.com/mbraak/django-mptt-admin)).

When a move occurs, the move info is sent to the server. It doesn't send the whole tree data.

E.g. move node 123 after node 456:

Post to url `/tree/move/123`  // 123 is the id of the moved node

```js
{
  "target_id": 456;  // id of the target node
  "position": "after"; // new position; could also be 'before' or 'inside'
}
```
The [tree.move](https://mbraak.github.io/jqTree/#event-tree-move) event contains the position and the node ids.

The server then executes the move in the database.

Also see https://github.com/mbraak/django-mptt-admin/blob/master/frontend/django_mptt_admin.ts#L88 and 
https://github.com/mbraak/django-mptt-admin/blob/master/django_mptt_admin/django_mptt_admin_mixin.py#L170 (NB: this is a Python Django project)

The django-mptt-admin project uses a library that handles storage of the tree data: [django-mptt](https://django-mptt.readthedocs.io/en/latest/). This is a Python Django library.
Django-mptt makes it easy to move nodes. The `move_to` function in `django_mptt_admin_mixin.py` is from django-mptt.

**Comment by duaneelkins** [comment]
I was thinking along those lines too .... however, I don't see how that would help if there is no "order" column in the table.  If a node is moved from one parent to another then it would work, but if you just move one node below/above another .... then what?

**Comment by mbraak** [comment]
You could do something like this: https://www.sitepoint.com/hierarchical-data-database/ . The django-mptt library mentioned above does exactly that.

**Comment by lordcysiek** [comment]
> I don't see how that would help if there is no "order" column in the table.

Your backend should be able to implement methods like persistAsNextSiblingOf() persistAsPrevSiblingOf(), moveUp(), moveDown(), then there is no problem with ordering. Nested Set implementations usually don't need additional ordering, becouse they are self explaining. This means you are always able to place node in desired location.

@mbraak
This brings me to my question, which is: Why there is no onAppend event? I'm currently implementing this library with symfony nested sets and i can handle reordering with my backed by simply requesting XHR request with parameters of node new position. This is fine. But what is the strategy to handle new nodes? Using built-in functions and events, I have to tree.append() with temporary ID and then wait for tree.refresh event, find node by temporary id, make XHR request with new node parameters (name, location) to save it in DB. My server returns json response with correct ID generated by DB and i have to updateNode() to set this ID, othervise both (back and front) structures are desynchronized.
I don't want to reload tree with XHR request becouse it's unefficient.

With onAppend (or even better - onBeforeAppend) i could simply make XHR request to save new node and apply the correct ID returned from server.
Tell me if I'm wrong or I'm missing something.

Cheers.

**Comment by mbraak** [comment]
Is there a reason you have to wait for the refresh event? I tried the following code:

```js
const parent = $tree.tree("getNodeById", 1);

$tree.tree("appendNode", { name: "new node", id: 999 }, parent);

const newNode = $tree.tree("getNodeById", 999);
$tree.tree("updateNode", newNode, { id: 123 });
```

**Comment by lordcysiek** [comment]
@mbraak 
Hah, yes. I can go this way. You are right i missed this simple conception. The reason to have event is more about code consistency. Being honest, my goal is to wrap this library with [Stimulus](https://stimulus.hotwire.dev/) controller where i want to listen to events so i can provide hooks for my backend application from there. I want to keep this as abstract as possible. There always be some additional JS code like button clicks handlers to add new node, delete node and edit other data in a row, but these functions are just a part of UI customization. 
Master goal is to create standalone component for [Symfony UX initiative](https://github.com/symfony/ux) or at least stay as close as possible.

**Comment by mbraak** [comment]
I'm closing this issue because there hasn't been any recent activity.
