### ISSUE TITLE
"showEmptyNode" is not defined. Correctly, it seems to be showEmptyFolder.

### ISSUE THREAD

**Issue by yasumichi** [mbraak/jqTree#645]
https://mbraak.github.io/jqTree/#options-showemptynode

A tree option "showEmptyNode" is introduced above. 
But, showEmptyNode is not defined.
Correctly, it seems to be showEmptyFolder.

**Comment by mbraak** [comment]
Thanks! I will update the documentation.

**Comment by mbraak** [comment]
fixed
