### ISSUE TITLE
Architecture question for jqTree

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#651]
First off I want to say thank you for a great set of software. It's very well written.

I'm using it to learn a bit.

I have an Architecture question.

I have a set of software of my own where I'm thinking of how to save it into json so I can save it into the database. I'm wanting to save attributes and text from a parent dom element and it's sub-Elements to a defined json structure.

I was wondering from your experience now that you have created this, which you might favor, creating a shadow object and making all the changes to it in the background during event calls or creating the object and the json based on the current parent Dom element and it's sub-Elements just in time just before saving it to the database.

So let's say I'll have 20 to 100 small panels in a parent div and under each of those panels I'll have 3 to 10 items. And I'd like to capture just certain attributes and text of all of this, making the json smaller.

Were there speed considerations you had to think of in doing this for jqTree? Would you have chosen differently? Was wondering if you'd talk about what you chose and why you chose the way you did for jqTree.

Having a shadow object takes up space/storage on the client, but creating the object and json at save time could/might take some time.

I know you are busy, so you don't have to answer this, but I'm intrigued because I haven't run into a lot of people who have done this before around where I am. The toJson part. Most provide the frontend or backend but not both.

Thanks again for your software and thoughts.

**Comment by mbraak** [comment]
I can only say what jqtree does. Jqtree doesn't store any data in the dom, but uses a tree datastructure in javascript. I think that improves the readability of the code. Also, accessing the dom is always slower than using a datastructure.

I hope I have understood your question correctly.

**Comment by WriterStat** [comment]
Thanks! You did! I think. Much appreciated for answering something unrelated to jqTree. And for the response.

So jqtree has a tree data structure in js and the changes are updated/kept there as they occur, then toJson gives a json version of it.

I have done something similar myself in other software. With Bootstrap we have gotten so used to storing data in the dom and with jQuery/javascript manipulating it. That I pass in a json for the creation of the elements under the parent div in my software, but I don't keep a copy for my software(unrelated to jqTree). I probably should.

I have thought of grabbing it back from the dom. But was wondering about the speed.

Thanks again, there's just nothing like having experience and I read through the jqTree code, but wanted to get your take. Much appreciate it. And for your quick return. And the cool software!
