### ISSUE TITLE
Open Child nodes after searching

### ISSUE THREAD

**Issue by vinaykashyap1996** [mbraak/jqTree#654]
Hi guys,

when i search for a folder it does not show the child elements and i am not able to open the folders on search . i have to click them to open. 

I have solved the above issue with help of #282 . Now i have a new one .

when i have autoOpen : false
after search it does not open it automatically. How can this be done ?

Thank you

**Comment by mbraak** [comment]
I think the code from #282 is not the best way to filter nodes. I'll look into a better way to filter nodes.

**Comment by mbraak** [comment]
I added a filter example: https://mbraak.github.io/jqTree/examples/14_filter/ The example only works with the latest version of jqTree (1.6.1)

* If a folder is found it is automatically opened.

**Comment by vinaykashyap1996** [comment]
It is still not working for for me but something new came up 
![Screenshot (6)](https://user-images.githubusercontent.com/41184319/123352226-25ef9600-d55f-11eb-9a77-7798decd09ce.png)
![Screenshot (7)](https://user-images.githubusercontent.com/41184319/123352228-2720c300-d55f-11eb-9d6a-bb0b80bb420a.png)

**Comment by mbraak** [comment]
It's very difficult to see what the problem is without any code. Could you share the code? You could share it on https://codesandbox.io/ for example.

**Comment by vinaykashyap1996** [comment]
after search the tree does not refresh . i can add the code for you as well

**Comment by mbraak** [comment]
Are you using jqTree 1.6.1? The filter example uses the new 'refresh' method, which is only available in the latest version.

**Comment by vinaykashyap1996** [comment]
Yes I am using the latest version only the main is that the tree doesn’t re render after Filter I get true and false values . The tree doesn’t render again to show the filtered values

**Comment by vinaykashyap1996** [comment]
Template.folder.onRendered(function (){
const $tree = $("#tree1");

let foundMatch = false;

$tree.tree({
    autoOpen: false,
    data: ExampleData.exampleData,
    useContextMenu: false,
    onCreateLi: (node, $el) => {
        if (foundMatch && !node.openForMatch && !node.parent.matches) {
            $el.addClass("hidden-node");
        }

        if (node.matches) {
            $el.addClass("highlight-node");
        }
    },
});

$("#filtersearch").on("keyup", () => {
    const searchTerm = $("#filtersearch").val().toLowerCase();

    if (!searchTerm) {
        foundMatch = false;

        tree.iterate((node) => {
            node['openForMatch'] = false;
            node["matches"] = false;
            return true;
        });

        $tree.tree("refresh");
        return;
    }

    const tree = $tree.tree("getTree");
    foundMatch = false;

    tree.iterate((node) => {
        const matches = node.name.toLowerCase().includes(searchTerm);
        node["openForMatch"] = matches;
        node["matches"] = matches;

        if (matches) {
            foundMatch = true;

            if (node.isFolder()) {
                node.is_open = true;
            }

            let parent = node.parent;
            while (parent) {
                parent["openForMatch"] = true;
                parent.is_open = true;
                parent = parent.parent;
            }
        }

        return true;
    });

    $tree.tree("refresh");
});
})

<template ="folders">
<div class="level mt-5">
			<div class="level-item has-text-centered mt-2">
				<input type="text" id="filesearch" name="filesearch" class="input is-rounded">
			</div>
		</div>
<div class="has-background-white mt-4 pl-4 pt-4 pb-4" id="tree1"></div>
</template>

**Comment by mbraak** [comment]
There are some things that you check:

* Add some `console.log` statements to see if the code is executed.
  * Are the classes added in `onCreateLi` ?
* Is the search term correct? `console.log(searchTerm);
* What is the value of `matches`?
* Is the css loaded? There should be css for the classes `hidden-node` and `highlight-node`.

**Comment by vinaykashyap1996** [comment]
Yes , I checked with the console logs as well the li elements are created the matches is also added but css is not being rendered after search .

**Comment by mbraak** [comment]
That's strange. I don't understand how that's possible. Note that [this example](https://mbraak.github.io/jqTree/examples/14_filter/) is almost the same and it does work (at leats on my computer).

**Comment by vinaykashyap1996** [comment]
The main issue for me is that css is not loading

**Comment by vinaykashyap1996** [comment]
$('#filesearch').on("keyup",function () {
                clearTimeout(thread);
                var searchVal = $(this).val();
                if (searchVal.trim().length) {
                var tempData = [];
                var _outputData = jQuery.extend(true, {}, data);
                        _.each(_outputData,
                            function(parent) {
                                var match = _.filter(parent.children,
                                    function(child) {
                                        return (child.name.toLowerCase().indexOf(searchVal.toLowerCase()) > -1);
                                    });
                                var parentObj = parent;
                                parentObj.children = match;
                                if (match.length){
                                    tempData.push(parentObj);
                                } 
                            });
                        thread = setTimeout(function() {
                                $('#tree1').tree('loadData', tempData);
                            },
                            1000);
                    } else {
                        $('#tree1').tree('loadData', data);
                    }
                });

This piece of code works for me . I still need to know how can i search the parent as well with this and open the nodes after search automatically

**Comment by mbraak** [comment]
I wonder what happens if you search multiple times. Does the code search in the original data or in the data that is already filtered?

**Comment by mbraak** [comment]
kermode
