### ISSUE TITLE
No left alignment with "buttonLeft: false"

### ISSUE THREAD

**Issue by odungern** [mbraak/jqTree#662]
When selecting "buttonLeft: false" upon tree creation, all is fine with nodes having children: The icon moves to the right and the text (name) moves to the left. In contrast, the name of nodes without children - having no icon to move - don't move to the left. In the following example the four nodes are on the same hierarchical level, but not aligned to the left:

![grafik](https://user-images.githubusercontent.com/8947971/135630903-fa1238e6-d2e7-4ac7-946d-d768b6789395.png)
 
Used: jqTree v1.6.1 (js, css)

(This is the first problem we ever have found with jqTree. In our team developing the [SpecIF Editor](http://specif.de/apps/edit#import=../examples/Dimmer.specifz) it has a high reputation for functional design and quality. Thanks a lot for your contribution!)

**Comment by mbraak** [comment]
I'll have a look

**Comment by mbraak** [comment]
I added a pr with a possible fix. #664

**Comment by odungern** [comment]
..  thanks a lot for the quick fix. Will have a look shortly!

**Comment by odungern** [comment]
yes, works for me!

https://github.com/mbraak/jqTree/pull/664#issuecomment-932960089

Thanks a lot!
