### ISSUE TITLE
Remove jQuery dependency

### ISSUE THREAD

**Issue by evaneykelen** [mbraak/jqTree#666]
I realize it might be close to heresy but are there plans to drop jqTree's dependency on jQuery? Increasingly jQuery is frowned upon by developers[^1] which might lead to a reduced adoption of jqTree in the long run which would be a shame since jqTree is awesome. In case dropping jQuery as a dependency in indeed planned, is there a way I can support this effort?

[^1]: To be clear, personally I think jQuery still offers clean syntactic sugar to often-used JS constructs in 2021. I am merely observing a growing number of developers who outright dismiss jQuery) for right and wrong reasons.

**Comment by mbraak** [comment]
I agree that jQuery is redundant in 2021. But I don't have plans to remove the dependency. JqTree is in maintenance mode and I'm not planning any big changes. If anyone is willing to do the work, then I would of course welcome a PR.

**Comment by evaneykelen** [comment]
Ah okay, I didn't know it was in maintenance mode. I'll look into sizing the effort of removing jQuery. Will close the issue for now.
