### ISSUE TITLE
Opening a 'load_on_demand' node using the keyboard causes the keyboard-focus to be lost

### ISSUE THREAD

**Issue by Jaccoky** [mbraak/jqTree#669]
I am implementing further keyboard the jqtree component. I am having troubles with opening nodes that are using 'load_on_demand'. The focussed node you open using the keyboard (for example by using the right-arrow key) loses focus (and also the whole tree loses focus). Therefor, you cannot continue navigating using the keyboard. 

If you re-focus the tree and close and re-open the (now loaded) node, the focus remains as expected. 

I tried all kind of things but I just cannot get this to work. I did manage to re-focus the node after loading, but then the key-strokes where not handled correctly anymore (causing the tree to scroll instead of navigating throug nodes).

You can test this at: 
    [https://development.bluepolar.com/TestJQtree/TestJQtree.html](https://development.bluepolar.com/TestJQtree/TestJQtree.html)

Simply navigate through this tree using the keyboard. Each time you open a node for the first time, the focus is lost and you will have to re-focus using the mouse. When you close and re-open an already loaded node, there are no issues.

Any help is welcome.

**Comment by mbraak** [comment]
I will have a look. Thanks for the example.

**Comment by mbraak** [comment]
I have added a pr with a fix: #670

**Comment by Jaccoky** [comment]
This works great! Many thanks for the very fast response.
