### ISSUE TITLE
Is the tree node children property array always needed?

### ISSUE THREAD

**Issue by WriterStat** [mbraak/jqTree#674]
Hi Marco, thought I'd give this another try, but maybe worded better. Hope you are doing well!

example: each tree node gets a `this.children = [];`

Does the children array have to always exist for each tree node? If the tree node won't have any children?

Example:  For a 2 level tree. The second level would never have child nodes in the tree,

Note: The tojson ...children array always includes `children : []` an empty array for every 2nd level tree node when stored in the database.

I know this is in maintenance. So this is more of a question. Thanks! I'm using/editing the debug version.

**Comment by mbraak** [comment]
Internally each `Node` object has a `children` property, which is an array. This property is required.

In the input data the `children` property is optional. E.g. see https://mbraak.github.io/jqTree/#options-data

I'll have a look at the `toJson` function.

**Comment by mbraak** [comment]
I tried the `toJson` function and it doesn't return empty `children` arrays.  Do you get a different result?

E.g.:

```
[{"id":1,"name":"Saurischia","is_open":true,"children":[{"id":2,"name":"Herrerasaurians"},{"id":3,"name":"Theropods","children":[{"id":4,"name":"Coelophysoids"},
```

**Comment by WriterStat** [comment]
I pass in this original from database, `loadDataFromUrl` :

`[{"id":"1","name":"Doc 1","children":[{"id":"2","name":"Text 1","border":"primary","dueDate":"None","doc":43,"desc":""}]}]`

I get this from tojson...

`[{"id":"1","name":"Doc 1","children":[{"id":"2","name":"Text 1","children":[],"border":"primary","dueDate":"None","doc":43,"desc":""}]}]`

Which adds the "children":[] on the second level.

**Comment by WriterStat** [comment]
Using the same as you, passing in from database, `loadDataFromUrl` :

`[{"id":1,"name":"Saurischia","children":[{"id":2,"name":"Herrerasaurians"}]}]`

I get this from tojson...

`[{"id":1,"name":"Saurischia","children":[{"id":2,"name":"Herrerasaurians","children":[]}]}]`

**Comment by WriterStat** [comment]
I'll look at the `toJson` function here as well. Possibly something is messing this up here.

**Comment by WriterStat** [comment]
Found the error. Totally my fault. It wasn't able to find children in...getData...getDataFromNodes

`if (["parent", "children", "element", "tree", "isEmptyFolder"].indexOf(k) === -1 &&
                        Object.prototype.hasOwnProperty.call(node, k)) {`

Because it couldn't find it, it included a children : [] in the `tmpNode`.

Again totally my fault. Fixed. Appreciate you again for your patience and helping me find the error.

**Comment by WriterStat** [comment]
I probably would do better if I used TypeScript, but I like the regular javascript better. Maybe someday. Looking at the 1.6.2 debug version of jqTree it looks quite a bit different from prior debug versions.
