### ISSUE TITLE
Altered CSS for 'buttonleft=false' in case of multi-line entries

### ISSUE THREAD

**Issue by odungern** [mbraak/jqTree#675]
Hi Marco, 
thanks for including the fix for 'buttonleft=false' in 1.6.2.

The default CSS however yields a suboptimal placing of the button, in case the entry does not fit on a single line.

You have given me the following advice:

> This is what I get with the default css:
> 
> [Schermafbeelding 2021-10-20 om 14 56 37](https://user-images.githubusercontent.com/235558/138097311-e51d19c4-fe7d-480f-8952-3ceac6802cb2.png)
> 
> The button is aligned to the right, but only when the title is on multiple lines. I don't know why that is.
> 
> When I remove ```display: flex;``` from the ```ul.jqtree-tree .jqtree-element``` element, I get:
> 
> [Schermafbeelding 2021-10-20 om 15 01 45](https://user-images.githubusercontent.com/235558/138097968-701414c4-a6e5-466d-a309-64385b39c394.png)
> 
> This looks better. Perhaps this is a good option when the button is on the right. Could you try if this works for you?

Yes, this has worked for me .. and I prefer this placing, as well.

**Comment by mbraak** [comment]
I will look into it.

**Comment by odungern** [comment]
... take your time ... for now we are serving a 'private' version of the CSS with the recommended change.

**Comment by odungern** [comment]
.. sorry, to thick a thumb hit the wrong button

**Comment by odungern** [comment]
thanks! Have tried to verify with the latest (1.7.1). Unfortunately it does not work for us ... so we stay with our private CSS for the time being.
I now see that the changelog for 1.7.1 does not list #675 ... so we will wait for the next release ... no worries and no hurry.
![jqtree-button-right-1 7 1](https://github.com/mbraak/jqTree/assets/8947971/44e9d143-0b43-43c6-9a64-84887af44690)

**Comment by mbraak** [comment]
There is a pr with a fix: #748. 

It works on my system and the Chrome browser.

* Set `buttonLeft` to `false`
* Test with a parent node that has a long title and is displayed over two lines
* -> The button is on the second line, after the text.

The only thing that has changes is the css: https://github.com/mbraak/jqTree/blob/toggler-right-with-multiline/jqtree.css

**Comment by mbraak** [comment]
The pr with the fix is merged. There is no new release yet.

**Comment by mbraak** [comment]
The fix is included in release 1.7.4

**Comment by odungern** [comment]
Tested with 1.8.0: Toggler on the right works fine (also in our app) when the line is split to multiple lines. Thanks a lot Marco!
