### ISSUE TITLE
Can I limit the depth of drag drop?

### ISSUE THREAD

**Issue by hoonion90** [mbraak/jqTree#677]
I can't find it in the document.

**Comment by mbraak** [comment]
You can implement this using the [onCanMove](https://mbraak.github.io/jqTree/#options-oncanmove) and [onCanMoveTo](https://mbraak.github.io/jqTree/#options-oncanmoveto) options.

Also useful: the `Node` class has  [getLevel](https://mbraak.github.io/jqTree/#node-functions) method.

Does this answer your question?

**Comment by hoonion90** [comment]
Thank u very much!
