### ISSUE TITLE
Is Pagination Possible...

### ISSUE THREAD

**Issue by Bhumit-t** [mbraak/jqTree#680]
Hello

Thanks for producing this Tree view code.

Can you provide some guidance for paginating the data for each node and showing each page on sliding the range.

**Comment by mbraak** [comment]
Unfortunately there is no support for pagination.

**Comment by Bhumit-t** [comment]
Hello Marco,

Apologies for writing in Issues tab...

I am trying to do pagination using jquery pagination plugin.

For that I need to add an html input element to the DOM
and then change events on this element will be picked up by the jquery code as it comes live.

Tried adding this html element using "onCreateLi" method. But it is not adding it at the desired location

for eg: using "after" method of jquery is adding is inside the div element which is child of the li element of the given node
not able to add this new html element after the div...

tried different ways like getting ul element under the li and adding the input element before it, but not able to 
get the ul element 
and 
adding input element to the object by doing something like: 
''' thisNode.element.children[0].htmlToAdd("input>search</input>") '''

can see the element in object printed in console but not visible in the DOM structure (i mean: on screen or HTML source)

I am not aware how the objects shown in console are getting created and can be changed or not.
Moreover the functions are written in ts so trying to find how elements can be adding in ts
but most examples are based on fetching element by "id" where as in this case 
the id is there in object but not in html tag rendered.

Please guide in this regards,
Thanks a lot !
- Bhumit 


P.S : If there is any alternate channel to reach you please share the same...

**Comment by mbraak** [comment]
Hello,

Could you give an example of the html you want as end result (for a single tree node)?

One thing I should add: it's important to add html elements inside the `jqtree-element` div. It's also important to keep the `jqtree-title` span.

Greetings

**Comment by Bhumit-t** [comment]
Hello Marco,

Please find the image below:

![image](https://user-images.githubusercontent.com/21146160/168653368-f813874f-86a5-455a-865d-07c683ba7c6e.png)


I have added an input filed as 1st li element 
under the ul element 
which is under the main li element of the Node (i.e Networks).

When I am trying to add this using the example give for onCreateLi method in which "edit" link gets created beside the node 
it is getting created after the <div> element in side the main <li> of "Networks" node (hence remains open even when the node is not clicked)
as show in image below:
![image](https://user-images.githubusercontent.com/21146160/168654929-db274ec6-225a-4ec6-b043-14da1a1cb0ae.png)

Thanks Again ...

**Comment by mbraak** [comment]
It's only possible to add html elements inside the `li` (and `jqtree-element` div). If you add elements outside (like the first example above), then jqTree will not work correctly.

**Comment by Bhumit-t** [comment]
is there any way for DOM manipulation like we do in Jquery, where you can pick an element (for eg using id) and then change that element or append other elements?

Apart, "id" is passed to the node but not visible in the html element created
it might be the way typescript works, but is there any way for showing "id" in the html elements ?
