### ISSUE TITLE
Question: Is there a way to know when dragging a node if it's dropped at its same place before dragging or not?

### ISSUE THREAD

**Issue by Amira-Samir** [mbraak/jqTree#689]

**Comment by mbraak** [comment]
I'm afraid that's not possible. There is a `tree.move` event, but it's not triggered when the node is dropped at exactly the place.

Can I ask you where you want to use this for? Do you want to perform a particular action when dragging to the same place?

**Comment by Amira-Samir** [comment]
I need to save dragging updates instantly in DB, so I need to make sure I don't hit the DB unless the node is actually moved from its place

**Comment by mbraak** [comment]
Are you using the `tree.move` event for the updates? In that case it's not an issue because the event is only triggered if the node moves to a different place.

**Comment by Amira-Samir** [comment]
worked fine .. many thanks @mbraak
