### ISSUE TITLE
jqtree with links for nodes

### ISSUE THREAD

**Issue by sjsnipes** [mbraak/jqTree#69]
i am trying to make my nodes as links (as i saw someone else seems to be doing in issue #21 https://github.com/mbraak/jqTree/issues/21), but i cannot get them to work.  All i get in the display is the html text itself.  How do i get the tree to render the html?  I have my data setup with the node label string to be the <a href=... /a>.  Is there something else i need to do - i thought that it should just work?  I even tried copying the exact data and searched for an example that might show how to make it a link... alas i am stuck...  I am thinking about using the onCreateLi to add my handling?

I am fairly new to all of this, so maybe i am missing something?  Also, I am using a backbone.js  view - which shouldn't matter but thought it was worth mentioning.  Thanks in advance for any help.

**Comment by nicholaswmin** [comment]
+1 this should be in the docs
