### ISSUE TITLE
Disable opening folders during drag & drop

### ISSUE THREAD

**Issue by MohamedSaber20** [mbraak/jqTree#692]
Can we have an option to disable opening folders during drag & drop, for example we have an option '**openFolderDelay**' to delay opening folders during drag & drop,  we can make this option accept '_false_' to disable the feature itself during drag & drop?
Also if you have a workaround I will appreciate it.
Thanks.

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
I opened a pull request: #693

**Comment by mbraak** [comment]
The pr is merged. I plan to do a new release this week.

**Comment by MohamedSaber20** [comment]
Sounds great, Thank you.

**Comment by mbraak** [comment]
Version 1.3.6 (with this feature) is released.
