### ISSUE TITLE
Behavior changed with 1.7.0

### ISSUE THREAD

**Issue by odungern** [mbraak/jqTree#740]
We have observed a change in behavior with 1.7.0 and 1.7.1 when using moveDown or openNode. For the moment this is just a notification, because we haven't analyzed it, yet. It is well possible that we use the library in a way it is not designed - but a change in behavior is obvious, as our code doesn't iterate the tree any more as before. So we have gone back to 1.6.3 for the time being. 

We will spend some time on analysis hopefully soon - GfSE is a non-commercial organization as well and resources are scarce ... we ask for understanding.

**Comment by mbraak** [comment]
It could be related to pr #708 (the related issue is #706), which was introduced in version 1.7.0.

That pr changes the behaviour of `getNextNode` and `getPreviousNode`, and not of `moveDown` or `openNode`. At least, as far as I can see.

Please let me know what the change in behaviour is.

**Comment by odungern** [comment]
Thanks for your attention and the hint ... it let's us look more focused. Yes, we will spend some time in the near future on analysing the change and we will let you know.

**Comment by mbraak** [comment]
I'm closing this issue for now because there is no progress. Please reopen when there are new developments.
