### ISSUE TITLE
Inconsistent/incorrect drag & drop node highlighting

### ISSUE THREAD

**Issue by TomDeFord** [mbraak/jqTree#751]
Firstly thanks for a great repro, really appreciate the time and effort that you've put in.

Using "Example 3 - Drag and drop": https://mbraak.github.io/jqTree/examples/03_drag_and_drop/

**Test 1:**
* Expand Theropods
* Click and drag Ceratosaurians (no children) to the right, no destination highlight appears until one moves the selected item up or down and it leaves the dotted blue selected item area. Drag can be cancelled by dropping over the blue dotted selection with no other highlight showing. All good.

**Test 2:**
* Reload the page
* Expand Theropods
* Click and drag Coelurosaurians (has children but is closed) to the right, as previously no destination highlight appears until one moves the selected item up or down and it leaves the dotted blue selected item area. Drag can be cancelled by dropping over the blue dotted selection with no other highlight showing. Still all good.

**Test 3 & 4:**
* Reload the page
* Expand Theropods then expand Coelurosaurians
* Click and drag Coelurosaurians (has children and is open) to the right, unlike before the node above (Carnosaurians) immediately highlights. Only by dragging the selected item down by 2 more nodes (over Ornithomimosaurians) does the highlight disappear. If one keeps dragging down then the insert highlight line appears 2 nodes before actually getting to the insertion point (over Dromaeosaurids).
* I see 2 issues here, the immediate highlighting of the node above without actually being hovered over and 2nd the premature highlighting of the insert line as one drags down.

**Test 5:**
* Reload the page
* Expand Theropods then expand Coelurosaurians
* Click and drag Coelurosaurians (has children and is open) to the right, Carnosaurians highlights, drop inside so that Coelurosaurians is now the first child of Carnosaurians.
Click and drag Coelurosaurians (has children and is open) to the right, it is now impossible (unless one drags out of the tree) to drop Coelurosaurians back onto itself for a no-move drop as wherever one moves an insert highlight appears. Dragging down and the insert line now appears 4 nodes before the actual insert point

Reproduced on Edge Version 117.0.2045.31 (Official build) (64-bit) & Chrome Version 117.0.5938.92 (Official Build) (64-bit) using jqTree V1.7.3

**Comment by mbraak** [comment]
I'll have a look

**Comment by mbraak** [comment]
This is the pr with the possible fix: #752

**Comment by TomDeFord** [comment]
Thanks Marco, from my testing this seems to have resolved all of the above issues. Top marks! Many thanks.

**Comment by mbraak** [comment]
The fix is included in release 1.7.4

**Comment by TomDeFord** [comment]
Hi there, all of the above issues are now back, haven't checked which version this occurred. In addition, using "Example 3 - Drag and drop" as before from the github site:

**Test 6:**

- Drag Theropods (closed with children) onto Herrerasaurians, adding it as a child.
- With Theropods still closed, drag to the right, insert points above and below appear correctly. Leave Theropods where it is.
- Open Theropods, drag to the right, the initial insert point appears above Saurischia, this has 2 issues, the insert point shouldn't appear at all when just dragging to the right still over the source node, secondly the first insert point is one level before above Herrerasaurians.
- Before moving down the insert point moves to above Herrerasaurians
- Keep moving down, the insert point appears above Sauropodomorphs when the drag is still some 2/3 nodes above (over Spinosauroids)
- It is now impossible (unless one drags out of the tree) to drop Theropods back onto itself for a no-move drop as wherever one moves an insert highlight appears above or below.

The above is probably just a variation of Tests 4 & 5. What I've noticed is that with the tree nodes closed the insert points seem to work fine, the problem is when the node is opened with children below.

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
I can reproduce the error. Sorry about this, apparently the original fix was reverted by a refactoring of the dnd code.
I'm fixing it again in #795.

**Comment by mbraak** [comment]
This is fixed in version 1.8.2.

**Comment by TomDeFord** [comment]
Thanks Marco, this has fixed the above test cases. Once again thanks for your diligence and continued effort with this project.
