### ISSUE TITLE
changed documentation?

### ISSUE THREAD

**Issue by odungern** [mbraak/jqTree#788]
A weird observation on https://mbraak.github.io/jqTree/: I am pretty sure I saw 'getNextVisibleNode()' and 'iterate()' yesterday. I don't any more today. In any case both functions are called in our code and seem to work.

Perhaps I have tomatoes on my eyes (as we say in German) ... or something has happened ... (I have deleted my browser cache without any change in what is being displayed).

**Comment by mbraak** [comment]
I'll check. I did update the documentation; maybe something went wrong.
