### ISSUE TITLE
Injection vulnerability because of lodash.template

### ISSUE THREAD

**Issue by cloubout** [mbraak/jqTree#805]
Hi, 

I got a github security alert on your widget. It seems that the version 4.5.0 of lodash.template is vulnerable to injection.

Seems like the last lodash version is 4.17.15. Could be great to upgrade it.

**Comment by mbraak** [comment]
I'll have a look

**Comment by mbraak** [comment]
This is fixed. There is not yet a new release.

**Comment by mbraak** [comment]
Fixed in version 1.8.3
