### ISSUE TITLE
ContextMenuEvent

### ISSUE THREAD

**Issue by HASTJI** [mbraak/jqTree#812]
Hello. Is there any way to implement small context menu with several customizable buttons based on event group? As for now we have only node group info on-right-click, but nor any kind of menu. I made some searches and find out that there was a package https://github.com/DavidUv/jqTreeContextMenu which make that happen, but I can't make it work, due to it oldness and out-of-date, I guess.

**Comment by mbraak** [comment]
I'll have a look.

**Comment by mbraak** [comment]
Displaying a custom menu is outside of the scope of jqTree. JqTree does provide the [tree.contextmenu](https://mbraak.github.io/jqTree/#event-tree-contextmenu) event that you can use to build your own context menu.  Unfortunately I don't have an example for that.

**Comment by HASTJI** [comment]
Rolled back to 1.6.3 release and that extension started to work. Anyway thx for answer!
