### ISSUE TITLE
tree.select

### ISSUE THREAD

**Issue by HASTJI** [mbraak/jqTree#815]
Hello. 
Documentation for that method( tree.select ) is not correct. When we call

`.on('tree.select'....`

and if event node is null(so it not selected on click\button) - previous node is stored in event.previous_node, but not in e.previous_node, as said in the comment on the third line:

```
        else {
            // event.node is null
            // a node was deselected
            // e.previous_node contains the deselected node
        }
```
For e.previous_node it immideatly said that:
`Uncaught ReferenceError: e is not defined`

Pls fix that typo, if it's not too hard, ty.

**Comment by mbraak** [comment]
updated
