### ISSUE TITLE
Vulnerability introduced by ```braces<3.0.3```

### ISSUE THREAD

**Issue by cloubout** [mbraak/jqTree#819]
Hello,

I've got a new alert from github about the dependancy package ```braces``` that should be upgraded to a version >= 3.0.3.

 "The NPM package braces fails to limit the number of characters it can handle, which could lead to Memory Exhaustion. In lib/parse.js, if a malicious user sends "imbalanced braces" as input, the parsing will enter a loop, which will cause the program to start allocating heap memory without freeing it at any moment of the loop. Eventually, the JavaScript heap limit is reached, and the program will crash."

Have a nice day,

Corentin

**Comment by mbraak** [comment]
I plan to release a new version this week with a fix.

**Comment by mbraak** [comment]
This is fixed in version 1.8.4
