### ISSUE TITLE
Github Alert : HTTP Request Smuggling in ruby webrick 

### ISSUE THREAD

**Issue by cloubout** [mbraak/jqTree#830]
Hi, 

Sorry to bother you with every alert, but I have a new alert with the last master version : 

> An issue was discovered in the WEBrick toolkit through 1.8.1 for Ruby. It allows HTTP request smuggling by providing both a Content-Length header and a Transfer-Encoding header, e.g., "GET /admin HTTP/1.1\r\n" inside of a "POST /user HTTP/1.1\r\n" request. NOTE: the supplier's position is "Webrick should not be used in production

Package :  webrick (RubyGems)
Affected versions <= 1.8.1 (1.7)
Patched version : 1.8.2

**Comment by mbraak** [comment]
This is now fixed in the `dev`branch.

**Comment by cloubout** [comment]
[like]  Corentin LOUBOUTIN (EXT) reacted to your message:
________________________________

**Comment by mbraak** [comment]
Version 1.8.5 includes this security update

**Comment by cloubout** [comment]
Thank you very much
