### ISSUE TITLE
Drag'n'drop behaves differently

### ISSUE THREAD

**Issue by odungern** [mbraak/jqTree#852]
Since v1.8.3 the drag'n'drop behavior is different. Given the tree in the image, if selecting 'Consistency' and dragging it to 'System Models' (cursor not visible on the screenshot), then the blue insertion line appears as shown. When releasing (dropping) the item on 'System Models', it is inserted as first element as expected. 

![jqtree-drag'n'drop](https://github.com/user-attachments/assets/230bd546-1ca0-4803-a5c5-0a2eaf727746)

Up until v1.8.2 the blue insertion line is always shown where the item will be inserted, which is in my eyes much more intuitive.

So it is possible to drag'n'drop an item as wished, but it isn't as intuitive as it was before.

No big issue for us, we will continue using v1.8.2 for the time being.

**Comment by mbraak** [comment]
I'll look into it.

**Comment by mbraak** [comment]
I'm working on a fix: #853

**Comment by mbraak** [comment]
This is fixed in version 1.8.7

**Comment by odungern** [comment]
If this wasn't quick, what _is_ quick? We'll try and verify it in the days to come.

**Comment by odungern** [comment]
A team mate was apparently curious and just messaged to me: Tried, verified, solved! 
Thanks a lot!
