### ISSUE TITLE
Disable autoscroll on tree init

### ISSUE THREAD

**Issue by ivan-kolesov** [mbraak/jqTree#865]
Hi. The page uses a tree with a large number of elements.
When opened in a browser with a small screen height, then when opening such a large tree, autoscrolling occurs to the selected item in the tree.
This leads to the fact that the content on the site located at the top becomes hidden for the user.
Is there any way to disable autoscrolling when drawing the tree?
window.scrollTo({ top: 0, left: 0 }); does not seem like a better idea.

**Comment by mbraak** [comment]
The browser scrolls to the selected node because the selected node gets the focus. You can try to change that by setting the `tabIndex` option to `undefined`.

I haven't tried it myself yet.

Also see https://mbraak.github.io/jqTree/#tabIndex-slide
